In [2]:
import os
from onekey_algo.regression.run_regression import main as reg_main
from collections import namedtuple
from onekey_algo import get_param_in_cwd

# 设置参数
task_type = 'C'
root = get_param_in_cwd('radio_dir')
for cv in range(3, 4):
    for model_name in ['resnet50', 'resnet18', 'resnet101', 'densenet121', 'vgg19', 'inception_v3'][1:]:
        train_f = os.path.join('split_info', f'train-RND-{cv}.txt')
        val_f = os.path.join('split_info', f'val-RND-{cv}.txt')
        labels_f = os.path.join('split_info', 'labels.txt')
        data_pattern = os.path.join(root, task_type)
        params = dict(train=train_f,
                      valid=val_f,
                      labels_file=labels_f,
                      in_channels=3,
                      data_pattern=data_pattern,
                      j=6,
                      max2use=None,
                      val_max2use=None,
                      batch_balance=False,
                      normalize_method='imagenet',
                      model_name=model_name,
                      gpus=[0],
                      batch_size=16,
                      epochs=32 if model_name not in ['TwinsSVT', 'CrossFormer', 'SimpleViT'] else 96,
                      init_lr=0.005 if model_name not in ['TwinsSVT', 'CrossFormer', 'SimpleViT'] else 0.001,
                      optimizer='sgd',
                      retrain='',
                      model_root= os.path.join(root, 'models', f"CV-{cv}"),
                      iters_start=0,
                      iters_verbose=4,
                      save_per_epoch=True,
                      add_date=False,
                      pretrained=True)
        # 训练模型
        Args = namedtuple("Args", params)
        reg_main(Args(**params))

[2026-01-14 20:14:27 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-3.txt
[2026-01-14 20:14:27 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-3.txt
[2026-01-14 20:14:27 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-3.txt
[2026-01-14 20:14:27 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-3.txt
[2026-01-14 20:14:27 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-01-14 20:14:27 - about_log.py: 149]	INFO		Number of samples: 134
[2026-01-14 20:14:27 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\C
[2026-01-14 20:14:27 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task1\split_info\labels.txt
[2026-01-14 20:14:27 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-01-14 20:14:27 - about_log.py: 149]	INFO		Number of samples: 101
[2026-01-14 20:14:27 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\C
[2026-01-14 20:14:27 - run_regression.py: 305]	INFO	Creating model resnet18...
[2026-01-14 20:14:27 - resnet.py: 271]	INFO	Pretrained model loaded!
[2026-01-14 20:14:27 - run_regression.py: 352]	INFO	Start training...
[2026-01-14 20:14:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.478,4	LR: 0.004997	Loss: 536.680	Speed: 4.32 img/s	Time: 0hrs:0min
[2026-01-14 20:14:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.955,8	LR: 0.004989	Loss: 7508.018	Speed: 722.55 img/s	Time: 0hrs:0min
[2026-01-14 20:14:58 - run_regression.py: 233]	INFO	Phase: valid	loss:276801493661.1485	MSE: 252736953280.390	Speed: 6.6551img/s	Time: 15.18s

         MSE  Epoch Cohort
0  3.841e+03      0  Train
0  2.527e+11      0   Test

[2026-01-14 20:15:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.552,13	LR: 0.004971	Loss: 11.804	Speed: 2.11 img/s	Time: 0hrs:0min
[2026-01-14 20:15:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.030,17	LR: 0.004951	Loss: 4.820	Speed: 703.12 img/s	Time: 0hrs:0min
[2026-01-14 20:15:28 - run_regression.py: 233]	INFO	Phase: valid	loss:111285.7618	MSE: 84418.253	Speed: 6.6464img/s	Time: 15.20s

         MSE  Epoch Cohort
0      8.334      1  Train
0  84418.253      1   Test

[2026-01-14 20:15:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.627,22	LR: 0.004917	Loss: 2.015	Speed: 2.10 img/s	Time: 0hrs:1min
[2026-01-14 20:15:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.104,26	LR: 0.004885	Loss: 2.195	Speed: 705.58 img/s	Time: 0hrs:1min
[2026-01-14 20:15:59 - run_regression.py: 233]	INFO	Phase: valid	loss:1019.7055	MSE: 1003.847	Speed: 6.5766img/s	Time: 15.36s

        MSE  Epoch Cohort
0     2.095      2  Train
0  1003.847      2   Test

[2026-01-14 20:16:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.701,31	LR: 0.004837	Loss: 1.864	Speed: 2.07 img/s	Time: 0hrs:1min
[2026-01-14 20:16:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.179,35	LR: 0.004793	Loss: 1.399	Speed: 694.28 img/s	Time: 0hrs:1min
[2026-01-14 20:16:30 - run_regression.py: 233]	INFO	Phase: valid	loss:51.1655	MSE: 51.350	Speed: 6.6382img/s	Time: 15.22s

      MSE  Epoch Cohort
0   1.473      3  Train
0  51.350      3   Test

[2026-01-14 20:16:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.776,40	LR: 0.004730	Loss: 1.598	Speed: 2.10 img/s	Time: 0hrs:2min
[2026-01-14 20:16:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.254,44	LR: 0.004675	Loss: 1.271	Speed: 746.95 img/s	Time: 0hrs:2min
[2026-01-14 20:17:00 - run_regression.py: 233]	INFO	Phase: valid	loss:4.8278	MSE: 5.082	Speed: 6.6050img/s	Time: 15.29s

     MSE  Epoch Cohort
0  1.446      4  Train
0  5.082      4   Test

[2026-01-14 20:17:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.851,49	LR: 0.004599	Loss: 1.385	Speed: 2.08 img/s	Time: 0hrs:2min
[2026-01-14 20:17:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.328,53	LR: 0.004533	Loss: 1.440	Speed: 718.30 img/s	Time: 0hrs:2min
[2026-01-14 20:17:31 - run_regression.py: 233]	INFO	Phase: valid	loss:2.9773	MSE: 3.047	Speed: 6.7278img/s	Time: 15.01s

     MSE  Epoch Cohort
0  1.208      5  Train
0  3.047      5   Test

[2026-01-14 20:17:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.925,58	LR: 0.004444	Loss: 1.367	Speed: 2.10 img/s	Time: 0hrs:3min
[2026-01-14 20:17:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.403,62	LR: 0.004368	Loss: 1.007	Speed: 689.18 img/s	Time: 0hrs:3min
[2026-01-14 20:18:02 - run_regression.py: 233]	INFO	Phase: valid	loss:2.0634	MSE: 1.974	Speed: 6.6468img/s	Time: 15.20s

     MSE  Epoch Cohort
0  1.182      6  Train
0  1.974      6   Test

[2026-01-14 20:18:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.000,67	LR: 0.004268	Loss: 1.353	Speed: 2.10 img/s	Time: 0hrs:3min
[2026-01-14 20:18:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.478,71	LR: 0.004183	Loss: 1.447	Speed: 522.92 img/s	Time: 0hrs:3min
[2026-01-14 20:18:32 - run_regression.py: 233]	INFO	Phase: valid	loss:2.2690	MSE: 2.262	Speed: 6.6961img/s	Time: 15.08s

     MSE  Epoch Cohort
0  1.531      7  Train
0  2.262      7   Test

[2026-01-14 20:18:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.075,76	LR: 0.004072	Loss: 1.062	Speed: 2.10 img/s	Time: 0hrs:4min
[2026-01-14 20:18:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.552,80	LR: 0.003979	Loss: 1.393	Speed: 734.17 img/s	Time: 0hrs:4min
[2026-01-14 20:19:03 - run_regression.py: 233]	INFO	Phase: valid	loss:2.9126	MSE: 3.014	Speed: 6.6386img/s	Time: 15.21s

     MSE  Epoch Cohort
0  1.264      8  Train
0  3.014      8   Test

[2026-01-14 20:19:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.149,85	LR: 0.003858	Loss: 1.092	Speed: 2.08 img/s	Time: 0hrs:4min
[2026-01-14 20:19:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.627,89	LR: 0.003758	Loss: 1.277	Speed: 720.46 img/s	Time: 0hrs:4min
[2026-01-14 20:19:33 - run_regression.py: 233]	INFO	Phase: valid	loss:1.7402	MSE: 1.636	Speed: 6.7241img/s	Time: 15.02s

     MSE  Epoch Cohort
0  1.255      9  Train
0  1.636      9   Test

[2026-01-14 20:19:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.224,94	LR: 0.003630	Loss: 0.992	Speed: 2.11 img/s	Time: 0hrs:5min
[2026-01-14 20:19:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.701,98	LR: 0.003524	Loss: 1.272	Speed: 719.45 img/s	Time: 0hrs:5min
[2026-01-14 20:20:04 - run_regression.py: 233]	INFO	Phase: valid	loss:1.9957	MSE: 2.011	Speed: 6.7335img/s	Time: 15.00s

     MSE  Epoch Cohort
0  1.166     10  Train
0  2.011     10   Test

[2026-01-14 20:20:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.299,103	LR: 0.003389	Loss: 1.360	Speed: 2.11 img/s	Time: 0hrs:5min
[2026-01-14 20:20:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.776,107	LR: 0.003278	Loss: 0.821	Speed: 722.53 img/s	Time: 0hrs:5min
[2026-01-14 20:20:34 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0684	MSE: 1.002	Speed: 6.7342img/s	Time: 15.00s

     MSE  Epoch Cohort
0  1.854     11  Train
0  1.002     11   Test

[2026-01-14 20:20:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.373,112	LR: 0.003138	Loss: 1.225	Speed: 2.11 img/s	Time: 0hrs:6min
[2026-01-14 20:20:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.851,116	LR: 0.003024	Loss: 0.978	Speed: 730.23 img/s	Time: 0hrs:6min
[2026-01-14 20:21:05 - run_regression.py: 233]	INFO	Phase: valid	loss:1.2728	MSE: 1.281	Speed: 6.6494img/s	Time: 15.19s

     MSE  Epoch Cohort
0  1.222     12  Train
0  1.281     12   Test

[2026-01-14 20:21:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.448,121	LR: 0.002880	Loss: 1.186	Speed: 2.10 img/s	Time: 0hrs:6min
[2026-01-14 20:21:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.925,125	LR: 0.002763	Loss: 1.024	Speed: 659.32 img/s	Time: 0hrs:6min
[2026-01-14 20:21:35 - run_regression.py: 233]	INFO	Phase: valid	loss:1.7327	MSE: 1.691	Speed: 6.6413img/s	Time: 15.21s

     MSE  Epoch Cohort
0  1.049     13  Train
0  1.691     13   Test

[2026-01-14 20:21:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 15.522,130	LR: 0.002617	Loss: 1.092	Speed: 2.10 img/s	Time: 0hrs:7min
[2026-01-14 20:21:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.000,134	LR: 0.002500	Loss: 1.199	Speed: 723.46 img/s	Time: 0hrs:7min
[2026-01-14 20:22:06 - run_regression.py: 233]	INFO	Phase: valid	loss:2.8171	MSE: 2.211	Speed: 6.5641img/s	Time: 15.39s

     MSE  Epoch Cohort
0  1.102     14  Train
0  2.211     14   Test

[2026-01-14 20:22:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.597,139	LR: 0.002354	Loss: 1.137	Speed: 2.08 img/s	Time: 0hrs:7min
[2026-01-14 20:22:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.075,143	LR: 0.002237	Loss: 1.281	Speed: 725.29 img/s	Time: 0hrs:7min
[2026-01-14 20:22:37 - run_regression.py: 233]	INFO	Phase: valid	loss:2.9812	MSE: 2.926	Speed: 6.6373img/s	Time: 15.22s

     MSE  Epoch Cohort
0  1.219     15  Train
0  2.926     15   Test

[2026-01-14 20:22:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.672,148	LR: 0.002092	Loss: 1.413	Speed: 2.11 img/s	Time: 0hrs:8min
[2026-01-14 20:22:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.149,152	LR: 0.001976	Loss: 1.211	Speed: 734.90 img/s	Time: 0hrs:8min
[2026-01-14 20:23:07 - run_regression.py: 233]	INFO	Phase: valid	loss:4.7654	MSE: 5.135	Speed: 6.5928img/s	Time: 15.32s

     MSE  Epoch Cohort
0  1.234     16  Train
0  5.135     16   Test

[2026-01-14 20:23:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.746,157	LR: 0.001834	Loss: 0.951	Speed: 2.09 img/s	Time: 0hrs:8min
[2026-01-14 20:23:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.224,161	LR: 0.001722	Loss: 1.123	Speed: 728.65 img/s	Time: 0hrs:8min
[2026-01-14 20:23:38 - run_regression.py: 233]	INFO	Phase: valid	loss:4.4815	MSE: 2.732	Speed: 6.6408img/s	Time: 15.21s

     MSE  Epoch Cohort
0  1.025     17  Train
0  2.732     17   Test

[2026-01-14 20:23:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.821,166	LR: 0.001584	Loss: 1.116	Speed: 2.11 img/s	Time: 0hrs:9min
[2026-01-14 20:23:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.299,170	LR: 0.001476	Loss: 1.179	Speed: 737.52 img/s	Time: 0hrs:9min
[2026-01-14 20:24:08 - run_regression.py: 233]	INFO	Phase: valid	loss:2.2437	MSE: 2.355	Speed: 6.6482img/s	Time: 15.19s

     MSE  Epoch Cohort
0  1.230     18  Train
0  2.355     18   Test

[2026-01-14 20:24:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.896,175	LR: 0.001344	Loss: 1.199	Speed: 2.10 img/s	Time: 0hrs:9min
[2026-01-14 20:24:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.373,179	LR: 0.001242	Loss: 1.091	Speed: 712.96 img/s	Time: 0hrs:9min
[2026-01-14 20:24:39 - run_regression.py: 233]	INFO	Phase: valid	loss:3.4526	MSE: 2.170	Speed: 6.5801img/s	Time: 15.35s

     MSE  Epoch Cohort
0  1.152     19  Train
0  2.170     19   Test

[2026-01-14 20:24:54 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.970,184	LR: 0.001117	Loss: 1.229	Speed: 2.07 img/s	Time: 0hrs:10min
[2026-01-14 20:24:54 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.448,188	LR: 0.001021	Loss: 0.885	Speed: 705.88 img/s	Time: 0hrs:10min
[2026-01-14 20:25:10 - run_regression.py: 233]	INFO	Phase: valid	loss:1.6610	MSE: 1.629	Speed: 6.5619img/s	Time: 15.39s

     MSE  Epoch Cohort
0  1.114     20  Train
0  1.629     20   Test

[2026-01-14 20:25:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.045,193	LR: 0.000906	Loss: 1.007	Speed: 2.08 img/s	Time: 0hrs:10min
[2026-01-14 20:25:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.522,197	LR: 0.000817	Loss: 1.118	Speed: 752.60 img/s	Time: 0hrs:10min
[2026-01-14 20:25:41 - run_regression.py: 233]	INFO	Phase: valid	loss:1.5472	MSE: 1.566	Speed: 6.6437img/s	Time: 15.20s

     MSE  Epoch Cohort
0  1.107     21  Train
0  1.566     21   Test

[2026-01-14 20:25:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.119,202	LR: 0.000712	Loss: 1.155	Speed: 2.10 img/s	Time: 0hrs:11min
[2026-01-14 20:25:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.597,206	LR: 0.000632	Loss: 1.017	Speed: 719.13 img/s	Time: 0hrs:11min
[2026-01-14 20:26:11 - run_regression.py: 233]	INFO	Phase: valid	loss:1.9235	MSE: 1.901	Speed: 6.6461img/s	Time: 15.20s

     MSE  Epoch Cohort
0  1.078     22  Train
0  1.901     22   Test

[2026-01-14 20:26:26 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.194,211	LR: 0.000538	Loss: 0.957	Speed: 2.10 img/s	Time: 0hrs:11min
[2026-01-14 20:26:26 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.672,215	LR: 0.000467	Loss: 1.171	Speed: 703.69 img/s	Time: 0hrs:11min
[2026-01-14 20:26:42 - run_regression.py: 233]	INFO	Phase: valid	loss:2.5115	MSE: 2.626	Speed: 6.7353img/s	Time: 15.00s

     MSE  Epoch Cohort
0  1.075     23  Train
0  2.626     23   Test

[2026-01-14 20:26:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.269,220	LR: 0.000385	Loss: 1.200	Speed: 2.11 img/s	Time: 0hrs:12min
[2026-01-14 20:26:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.746,224	LR: 0.000325	Loss: 1.026	Speed: 730.42 img/s	Time: 0hrs:12min
[2026-01-14 20:27:12 - run_regression.py: 233]	INFO	Phase: valid	loss:3.1728	MSE: 2.265	Speed: 6.6470img/s	Time: 15.19s

     MSE  Epoch Cohort
0  1.137     24  Train
0  2.265     24   Test

[2026-01-14 20:27:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.343,229	LR: 0.000257	Loss: 1.025	Speed: 2.10 img/s	Time: 0hrs:12min
[2026-01-14 20:27:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.821,233	LR: 0.000207	Loss: 1.154	Speed: 700.95 img/s	Time: 0hrs:13min
[2026-01-14 20:27:43 - run_regression.py: 233]	INFO	Phase: valid	loss:2.2002	MSE: 2.291	Speed: 6.5641img/s	Time: 15.39s

     MSE  Epoch Cohort
0  1.725     25  Train
0  2.291     25   Test

[2026-01-14 20:27:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.418,238	LR: 0.000153	Loss: 1.173	Speed: 2.07 img/s	Time: 0hrs:13min
[2026-01-14 20:27:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.896,242	LR: 0.000115	Loss: 0.928	Speed: 706.77 img/s	Time: 0hrs:13min
[2026-01-14 20:28:14 - run_regression.py: 233]	INFO	Phase: valid	loss:1.7911	MSE: 1.777	Speed: 6.6473img/s	Time: 15.19s

     MSE  Epoch Cohort
0  0.948     26  Train
0  1.777     26   Test

[2026-01-14 20:28:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.493,247	LR: 0.000075	Loss: 1.253	Speed: 2.10 img/s	Time: 0hrs:14min
[2026-01-14 20:28:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.970,251	LR: 0.000049	Loss: 1.065	Speed: 674.91 img/s	Time: 0hrs:14min
[2026-01-14 20:28:44 - run_regression.py: 233]	INFO	Phase: valid	loss:1.8424	MSE: 1.749	Speed: 6.6504img/s	Time: 15.19s

     MSE  Epoch Cohort
0  1.018     27  Train
0  1.749     27   Test

[2026-01-14 20:28:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.567,256	LR: 0.000025	Loss: 1.056	Speed: 2.10 img/s	Time: 0hrs:14min
[2026-01-14 20:28:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.045,260	LR: 0.000011	Loss: 1.131	Speed: 750.10 img/s	Time: 0hrs:14min
[2026-01-14 20:29:15 - run_regression.py: 233]	INFO	Phase: valid	loss:2.4766	MSE: 2.481	Speed: 6.6413img/s	Time: 15.21s

     MSE  Epoch Cohort
0  1.063     28  Train
0  2.481     28   Test

[2026-01-14 20:29:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.642,265	LR: 0.000002	Loss: 0.866	Speed: 2.10 img/s	Time: 0hrs:15min
[2026-01-14 20:29:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.119,269	LR: 0.000000	Loss: 1.126	Speed: 739.14 img/s	Time: 0hrs:15min
[2026-01-14 20:29:46 - run_regression.py: 233]	INFO	Phase: valid	loss:3.5392	MSE: 3.690	Speed: 6.6540img/s	Time: 15.18s

     MSE  Epoch Cohort
0  1.037     29  Train
0  3.690     29   Test

[2026-01-14 20:30:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.716,274	LR: 0.000006	Loss: 1.152	Speed: 2.10 img/s	Time: 0hrs:15min
[2026-01-14 20:30:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.194,278	LR: 0.000017	Loss: 1.084	Speed: 703.76 img/s	Time: 0hrs:15min
[2026-01-14 20:30:16 - run_regression.py: 233]	INFO	Phase: valid	loss:2.2513	MSE: 2.359	Speed: 6.6409img/s	Time: 15.21s

     MSE  Epoch Cohort
0  1.017     30  Train
0  2.359     30   Test

[2026-01-14 20:30:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.791,283	LR: 0.000039	Loss: 0.889	Speed: 2.10 img/s	Time: 0hrs:16min
[2026-01-14 20:30:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.269,287	LR: 0.000062	Loss: 1.169	Speed: 731.47 img/s	Time: 0hrs:16min
[2026-01-14 20:30:47 - run_regression.py: 233]	INFO	Phase: valid	loss:1.9178	MSE: 1.995	Speed: 6.6437img/s	Time: 15.20s

     MSE  Epoch Cohort
0  0.956     31  Train
0  1.995     31   Test

[2026-01-14 20:30:47 - run_regression.py: 369]	INFO	Done for training. Best metric is 252736953280.38992@1 epoch. Average for last 5 iters is 2.4548464134076933
[2026-01-14 20:30:47 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-3.txt
[2026-01-14 20:30:47 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-3.txt
[2026-01-14 20:30:47 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-3.txt
[2026-01-14 20:30:47 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-3.txt
[2026-01-14 20:30:47 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-01-14 20:30:47 - about_log.py: 149]	INFO		Number of samples: 134
[2026-01-14 20:30:47 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\C
[2026-01-14 20:30:47 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task1\split_info\labels.txt
[2026-01-14 20:30:47 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-01-14 20:30:47 - about_log.py: 149]	INFO		Number of samples: 101
[2026-01-14 20:30:47 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\C
[2026-01-14 20:30:47 - run_regression.py: 305]	INFO	Creating model resnet101...
[2026-01-14 20:30:48 - resnet.py: 271]	INFO	Pretrained model loaded!
[2026-01-14 20:30:48 - run_regression.py: 352]	INFO	Start training...
[2026-01-14 20:31:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.478,4	LR: 0.004997	Loss: 505.134	Speed: 4.24 img/s	Time: 0hrs:0min
[2026-01-14 20:31:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.955,8	LR: 0.004989	Loss: 1999.892	Speed: 193.34 img/s	Time: 0hrs:0min
[2026-01-14 20:31:19 - run_regression.py: 233]	INFO	Phase: valid	loss:850293621639103175983104.0000	MSE: 832699345390915750461440.000	Speed: 6.5478img/s	Time: 15.43s

         MSE  Epoch Cohort
0  1.195e+03      0  Train
0  8.327e+23      0   Test

[2026-01-14 20:31:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.552,13	LR: 0.004971	Loss: 1.987	Speed: 2.05 img/s	Time: 0hrs:0min
[2026-01-14 20:31:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.030,17	LR: 0.004951	Loss: 1.953	Speed: 200.80 img/s	Time: 0hrs:0min
[2026-01-14 20:31:51 - run_regression.py: 233]	INFO	Phase: valid	loss:269017994.2364	MSE: 269005528.455	Speed: 6.5334img/s	Time: 15.46s

         MSE  Epoch Cohort
0  2.007e+00      1  Train
0  2.690e+08      1   Test

[2026-01-14 20:32:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.627,22	LR: 0.004917	Loss: 1.519	Speed: 2.06 img/s	Time: 0hrs:1min
[2026-01-14 20:32:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.104,26	LR: 0.004885	Loss: 1.414	Speed: 198.87 img/s	Time: 0hrs:1min
[2026-01-14 20:32:23 - run_regression.py: 233]	INFO	Phase: valid	loss:30762.9887	MSE: 30734.990	Speed: 6.4682img/s	Time: 15.61s

         MSE  Epoch Cohort
0      1.771      2  Train
0  30734.990      2   Test

[2026-01-14 20:32:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.701,31	LR: 0.004837	Loss: 1.469	Speed: 2.04 img/s	Time: 0hrs:1min
[2026-01-14 20:32:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.179,35	LR: 0.004793	Loss: 1.134	Speed: 199.05 img/s	Time: 0hrs:1min
[2026-01-14 20:32:54 - run_regression.py: 233]	INFO	Phase: valid	loss:101.1918	MSE: 98.713	Speed: 6.5906img/s	Time: 15.32s

      MSE  Epoch Cohort
0   1.356      3  Train
0  98.713      3   Test

[2026-01-14 20:33:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.776,40	LR: 0.004730	Loss: 1.257	Speed: 2.07 img/s	Time: 0hrs:2min
[2026-01-14 20:33:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.254,44	LR: 0.004675	Loss: 1.203	Speed: 202.04 img/s	Time: 0hrs:2min
[2026-01-14 20:33:25 - run_regression.py: 233]	INFO	Phase: valid	loss:5.4148	MSE: 5.090	Speed: 6.5093img/s	Time: 15.52s

     MSE  Epoch Cohort
0  1.166      4  Train
0  5.090      4   Test

[2026-01-14 20:33:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.851,49	LR: 0.004599	Loss: 0.960	Speed: 2.05 img/s	Time: 0hrs:2min
[2026-01-14 20:33:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.328,53	LR: 0.004533	Loss: 1.052	Speed: 206.61 img/s	Time: 0hrs:2min
[2026-01-14 20:33:57 - run_regression.py: 233]	INFO	Phase: valid	loss:4.3247	MSE: 3.821	Speed: 6.5579img/s	Time: 15.40s

     MSE  Epoch Cohort
0  1.115      5  Train
0  3.821      5   Test

[2026-01-14 20:34:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.925,58	LR: 0.004444	Loss: 0.926	Speed: 2.06 img/s	Time: 0hrs:3min
[2026-01-14 20:34:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.403,62	LR: 0.004368	Loss: 1.080	Speed: 198.76 img/s	Time: 0hrs:3min
[2026-01-14 20:34:28 - run_regression.py: 233]	INFO	Phase: valid	loss:10.0453	MSE: 9.525	Speed: 6.6355img/s	Time: 15.22s

     MSE  Epoch Cohort
0  0.877      6  Train
0  9.525      6   Test

[2026-01-14 20:34:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.000,67	LR: 0.004268	Loss: 0.988	Speed: 2.06 img/s	Time: 0hrs:3min
[2026-01-14 20:34:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.478,71	LR: 0.004183	Loss: 0.874	Speed: 199.45 img/s	Time: 0hrs:3min
[2026-01-14 20:35:00 - run_regression.py: 233]	INFO	Phase: valid	loss:2.8123	MSE: 2.488	Speed: 6.5992img/s	Time: 15.30s

     MSE  Epoch Cohort
0  1.043      7  Train
0  2.488      7   Test

[2026-01-14 20:35:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.075,76	LR: 0.004072	Loss: 1.202	Speed: 2.06 img/s	Time: 0hrs:4min
[2026-01-14 20:35:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.552,80	LR: 0.003979	Loss: 0.839	Speed: 180.44 img/s	Time: 0hrs:4min
[2026-01-14 20:35:31 - run_regression.py: 233]	INFO	Phase: valid	loss:1.3536	MSE: 1.198	Speed: 6.6186img/s	Time: 15.26s

     MSE  Epoch Cohort
0  1.050      8  Train
0  1.198      8   Test

[2026-01-14 20:35:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.149,85	LR: 0.003858	Loss: 0.952	Speed: 2.08 img/s	Time: 0hrs:4min
[2026-01-14 20:35:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.627,89	LR: 0.003758	Loss: 0.851	Speed: 210.42 img/s	Time: 0hrs:4min
[2026-01-14 20:36:02 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1760	MSE: 1.071	Speed: 6.5912img/s	Time: 15.32s

     MSE  Epoch Cohort
0  1.026      9  Train
0  1.071      9   Test

[2026-01-14 20:36:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.224,94	LR: 0.003630	Loss: 0.776	Speed: 2.07 img/s	Time: 0hrs:5min
[2026-01-14 20:36:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.701,98	LR: 0.003524	Loss: 1.081	Speed: 193.92 img/s	Time: 0hrs:5min
[2026-01-14 20:36:33 - run_regression.py: 233]	INFO	Phase: valid	loss:19.3695	MSE: 18.567	Speed: 6.6384img/s	Time: 15.21s

      MSE  Epoch Cohort
0   1.632     10  Train
0  18.567     10   Test

[2026-01-14 20:36:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.299,103	LR: 0.003389	Loss: 1.131	Speed: 2.09 img/s	Time: 0hrs:6min
[2026-01-14 20:36:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.776,107	LR: 0.003278	Loss: 0.888	Speed: 210.09 img/s	Time: 0hrs:6min
[2026-01-14 20:37:04 - run_regression.py: 233]	INFO	Phase: valid	loss:1.7507	MSE: 1.564	Speed: 6.7022img/s	Time: 15.07s

     MSE  Epoch Cohort
0  1.028     11  Train
0  1.564     11   Test

[2026-01-14 20:37:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.373,112	LR: 0.003138	Loss: 0.921	Speed: 2.10 img/s	Time: 0hrs:6min
[2026-01-14 20:37:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.851,116	LR: 0.003024	Loss: 0.994	Speed: 207.16 img/s	Time: 0hrs:6min
[2026-01-14 20:37:35 - run_regression.py: 233]	INFO	Phase: valid	loss:1.3269	MSE: 1.161	Speed: 6.6967img/s	Time: 15.08s

     MSE  Epoch Cohort
0  0.925     12  Train
0  1.161     12   Test

[2026-01-14 20:37:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.448,121	LR: 0.002880	Loss: 0.878	Speed: 2.09 img/s	Time: 0hrs:7min
[2026-01-14 20:37:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.925,125	LR: 0.002763	Loss: 1.027	Speed: 206.40 img/s	Time: 0hrs:7min
[2026-01-14 20:38:06 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0483	MSE: 0.939	Speed: 6.6608img/s	Time: 15.16s

     MSE  Epoch Cohort
0  0.910     13  Train
0  0.939     13   Test

[2026-01-14 20:38:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 15.522,130	LR: 0.002617	Loss: 0.897	Speed: 2.09 img/s	Time: 0hrs:7min
[2026-01-14 20:38:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.000,134	LR: 0.002500	Loss: 0.835	Speed: 211.19 img/s	Time: 0hrs:7min
[2026-01-14 20:38:37 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0958	MSE: 0.959	Speed: 6.6620img/s	Time: 15.16s

     MSE  Epoch Cohort
0  0.879     14  Train
0  0.959     14   Test

[2026-01-14 20:38:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.597,139	LR: 0.002354	Loss: 1.090	Speed: 2.10 img/s	Time: 0hrs:8min
[2026-01-14 20:38:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.075,143	LR: 0.002237	Loss: 0.809	Speed: 207.88 img/s	Time: 0hrs:8min
[2026-01-14 20:39:08 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1762	MSE: 1.053	Speed: 6.6880img/s	Time: 15.10s

     MSE  Epoch Cohort
0  0.947     15  Train
0  1.053     15   Test

[2026-01-14 20:39:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.672,148	LR: 0.002092	Loss: 0.986	Speed: 2.10 img/s	Time: 0hrs:8min
[2026-01-14 20:39:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.149,152	LR: 0.001976	Loss: 0.856	Speed: 209.57 img/s	Time: 0hrs:8min
[2026-01-14 20:39:38 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0571	MSE: 0.949	Speed: 6.6936img/s	Time: 15.09s

     MSE  Epoch Cohort
0  0.916     16  Train
0  0.949     16   Test

[2026-01-14 20:39:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.746,157	LR: 0.001834	Loss: 0.938	Speed: 2.09 img/s	Time: 0hrs:9min
[2026-01-14 20:39:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.224,161	LR: 0.001722	Loss: 0.911	Speed: 207.93 img/s	Time: 0hrs:9min
[2026-01-14 20:40:09 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1491	MSE: 1.025	Speed: 6.6802img/s	Time: 15.12s

     MSE  Epoch Cohort
0  0.996     17  Train
0  1.025     17   Test

[2026-01-14 20:40:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.821,166	LR: 0.001584	Loss: 0.883	Speed: 2.09 img/s	Time: 0hrs:9min
[2026-01-14 20:40:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.299,170	LR: 0.001476	Loss: 1.024	Speed: 210.08 img/s	Time: 0hrs:9min
[2026-01-14 20:40:41 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1576	MSE: 0.975	Speed: 6.6103img/s	Time: 15.28s

     MSE  Epoch Cohort
0  0.968     18  Train
0  0.975     18   Test

[2026-01-14 20:40:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.896,175	LR: 0.001344	Loss: 0.796	Speed: 2.07 img/s	Time: 0hrs:10min
[2026-01-14 20:40:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.373,179	LR: 0.001242	Loss: 1.048	Speed: 208.95 img/s	Time: 0hrs:10min
[2026-01-14 20:41:12 - run_regression.py: 233]	INFO	Phase: valid	loss:1.4262	MSE: 1.223	Speed: 6.6189img/s	Time: 15.26s

     MSE  Epoch Cohort
0  0.976     19  Train
0  1.223     19   Test

[2026-01-14 20:41:26 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.970,184	LR: 0.001117	Loss: 0.963	Speed: 2.07 img/s	Time: 0hrs:10min
[2026-01-14 20:41:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.448,188	LR: 0.001021	Loss: 0.878	Speed: 210.73 img/s	Time: 0hrs:10min
[2026-01-14 20:41:43 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1847	MSE: 1.069	Speed: 6.6015img/s	Time: 15.30s

     MSE  Epoch Cohort
0  0.968     20  Train
0  1.069     20   Test

[2026-01-14 20:41:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.045,193	LR: 0.000906	Loss: 0.952	Speed: 2.06 img/s	Time: 0hrs:11min
[2026-01-14 20:41:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.522,197	LR: 0.000817	Loss: 0.818	Speed: 209.83 img/s	Time: 0hrs:11min
[2026-01-14 20:42:14 - run_regression.py: 233]	INFO	Phase: valid	loss:1.2001	MSE: 0.922	Speed: 6.5810img/s	Time: 15.35s

     MSE  Epoch Cohort
0  0.902     21  Train
0  0.922     21   Test

[2026-01-14 20:42:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.119,202	LR: 0.000712	Loss: 0.812	Speed: 2.06 img/s	Time: 0hrs:11min
[2026-01-14 20:42:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.597,206	LR: 0.000632	Loss: 0.879	Speed: 210.48 img/s	Time: 0hrs:11min
[2026-01-14 20:42:46 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0725	MSE: 0.903	Speed: 6.5794img/s	Time: 15.35s

     MSE  Epoch Cohort
0  0.884     22  Train
0  0.903     22   Test

[2026-01-14 20:43:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.194,211	LR: 0.000538	Loss: 0.925	Speed: 2.07 img/s	Time: 0hrs:12min
[2026-01-14 20:43:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.672,215	LR: 0.000467	Loss: 0.901	Speed: 201.19 img/s	Time: 0hrs:12min
[2026-01-14 20:43:17 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1107	MSE: 0.927	Speed: 6.6814img/s	Time: 15.12s

     MSE  Epoch Cohort
0  0.986     23  Train
0  0.927     23   Test

[2026-01-14 20:43:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.269,220	LR: 0.000385	Loss: 1.132	Speed: 2.09 img/s	Time: 0hrs:12min
[2026-01-14 20:43:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.746,224	LR: 0.000325	Loss: 0.704	Speed: 206.89 img/s	Time: 0hrs:12min
[2026-01-14 20:43:48 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1704	MSE: 1.007	Speed: 6.6199img/s	Time: 15.26s

     MSE  Epoch Cohort
0  1.103     24  Train
0  1.007     24   Test

[2026-01-14 20:44:02 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.343,229	LR: 0.000257	Loss: 0.884	Speed: 2.09 img/s	Time: 0hrs:13min
[2026-01-14 20:44:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.821,233	LR: 0.000207	Loss: 0.880	Speed: 208.90 img/s	Time: 0hrs:13min
[2026-01-14 20:44:18 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1146	MSE: 0.923	Speed: 6.7887img/s	Time: 14.88s

     MSE  Epoch Cohort
0  0.950     25  Train
0  0.923     25   Test

[2026-01-14 20:44:33 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.418,238	LR: 0.000153	Loss: 1.011	Speed: 2.10 img/s	Time: 0hrs:13min
[2026-01-14 20:44:33 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.896,242	LR: 0.000115	Loss: 0.752	Speed: 209.40 img/s	Time: 0hrs:13min
[2026-01-14 20:44:49 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0775	MSE: 0.919	Speed: 6.7664img/s	Time: 14.93s

     MSE  Epoch Cohort
0  0.871     26  Train
0  0.919     26   Test

[2026-01-14 20:45:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.493,247	LR: 0.000075	Loss: 0.929	Speed: 2.11 img/s	Time: 0hrs:14min
[2026-01-14 20:45:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.970,251	LR: 0.000049	Loss: 0.885	Speed: 212.24 img/s	Time: 0hrs:14min
[2026-01-14 20:45:20 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0110	MSE: 0.913	Speed: 6.6969img/s	Time: 15.08s

     MSE  Epoch Cohort
0  0.957     27  Train
0  0.913     27   Test

[2026-01-14 20:45:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.567,256	LR: 0.000025	Loss: 0.731	Speed: 2.10 img/s	Time: 0hrs:14min
[2026-01-14 20:45:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.045,260	LR: 0.000011	Loss: 0.903	Speed: 197.11 img/s	Time: 0hrs:14min
[2026-01-14 20:45:51 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9758	MSE: 0.912	Speed: 6.6985img/s	Time: 15.08s

     MSE  Epoch Cohort
0  0.902     28  Train
0  0.912     28   Test

[2026-01-14 20:46:05 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.642,265	LR: 0.000002	Loss: 0.757	Speed: 2.10 img/s	Time: 0hrs:15min
[2026-01-14 20:46:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.119,269	LR: 0.000000	Loss: 1.020	Speed: 209.64 img/s	Time: 0hrs:15min
[2026-01-14 20:46:22 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9980	MSE: 0.901	Speed: 6.6650img/s	Time: 15.15s

     MSE  Epoch Cohort
0  0.829     29  Train
0  0.901     29   Test

[2026-01-14 20:46:36 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.716,274	LR: 0.000006	Loss: 0.768	Speed: 2.09 img/s	Time: 0hrs:15min
[2026-01-14 20:46:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.194,278	LR: 0.000017	Loss: 0.877	Speed: 209.64 img/s	Time: 0hrs:15min
[2026-01-14 20:46:53 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0532	MSE: 0.911	Speed: 6.6865img/s	Time: 15.10s

     MSE  Epoch Cohort
0  0.839     30  Train
0  0.911     30   Test

[2026-01-14 20:47:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.791,283	LR: 0.000039	Loss: 0.996	Speed: 2.09 img/s	Time: 0hrs:16min
[2026-01-14 20:47:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.269,287	LR: 0.000062	Loss: 0.742	Speed: 213.22 img/s	Time: 0hrs:16min
[2026-01-14 20:47:24 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9800	MSE: 0.903	Speed: 6.6906img/s	Time: 15.10s

     MSE  Epoch Cohort
0  0.860     31  Train
0  0.903     31   Test

[2026-01-14 20:47:24 - run_regression.py: 369]	INFO	Done for training. Best metric is 8.326993453909158e+23@1 epoch. Average for last 5 iters is 0.9079046140294752
[2026-01-14 20:47:24 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-3.txt
[2026-01-14 20:47:24 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-3.txt
[2026-01-14 20:47:24 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-3.txt
[2026-01-14 20:47:24 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-3.txt
[2026-01-14 20:47:24 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-01-14 20:47:24 - about_log.py: 149]	INFO		Number of samples: 134
[2026-01-14 20:47:24 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\C
[2026-01-14 20:47:24 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task1\split_info\labels.txt
[2026-01-14 20:47:24 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-01-14 20:47:24 - about_log.py: 149]	INFO		Number of samples: 101
[2026-01-14 20:47:24 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\C
[2026-01-14 20:47:24 - run_regression.py: 305]	INFO	Creating model densenet121...
[2026-01-14 20:47:24 - densenet.py: 260]	INFO	loading pretrained model
[2026-01-14 20:47:24 - run_regression.py: 352]	INFO	Start training...
[2026-01-14 20:47:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.478,4	LR: 0.004997	Loss: 0.790	Speed: 4.32 img/s	Time: 0hrs:0min
[2026-01-14 20:47:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.955,8	LR: 0.004989	Loss: 1.085	Speed: 160.53 img/s	Time: 0hrs:0min
[2026-01-14 20:47:55 - run_regression.py: 233]	INFO	Phase: valid	loss:1.6858	MSE: 1.403	Speed: 6.6204img/s	Time: 15.26s

     MSE  Epoch Cohort
0  0.947      0  Train
0  1.403      0   Test

[2026-01-14 20:48:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.552,13	LR: 0.004971	Loss: 1.636	Speed: 2.09 img/s	Time: 0hrs:0min
[2026-01-14 20:48:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.030,17	LR: 0.004951	Loss: 1.407	Speed: 198.84 img/s	Time: 0hrs:0min
[2026-01-14 20:48:26 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0431	MSE: 0.959	Speed: 6.6225img/s	Time: 15.25s

     MSE  Epoch Cohort
0  1.485      1  Train
0  0.959      1   Test

[2026-01-14 20:48:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.627,22	LR: 0.004917	Loss: 1.162	Speed: 2.09 img/s	Time: 0hrs:1min
[2026-01-14 20:48:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.104,26	LR: 0.004885	Loss: 0.772	Speed: 178.69 img/s	Time: 0hrs:1min
[2026-01-14 20:48:57 - run_regression.py: 233]	INFO	Phase: valid	loss:1.6341	MSE: 1.386	Speed: 6.6522img/s	Time: 15.18s

     MSE  Epoch Cohort
0  1.031      2  Train
0  1.386      2   Test

[2026-01-14 20:49:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.701,31	LR: 0.004837	Loss: 1.058	Speed: 2.10 img/s	Time: 0hrs:1min
[2026-01-14 20:49:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.179,35	LR: 0.004793	Loss: 1.205	Speed: 173.74 img/s	Time: 0hrs:1min
[2026-01-14 20:49:28 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8415	MSE: 0.780	Speed: 6.7288img/s	Time: 15.01s

     MSE  Epoch Cohort
0  1.107      3  Train
0  0.780      3   Test

[2026-01-14 20:49:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.776,40	LR: 0.004730	Loss: 0.887	Speed: 2.11 img/s	Time: 0hrs:2min
[2026-01-14 20:49:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.254,44	LR: 0.004675	Loss: 1.082	Speed: 179.51 img/s	Time: 0hrs:2min
[2026-01-14 20:49:59 - run_regression.py: 233]	INFO	Phase: valid	loss:2.0229	MSE: 1.993	Speed: 6.7622img/s	Time: 14.94s

     MSE  Epoch Cohort
0  0.949      4  Train
0  1.993      4   Test

[2026-01-14 20:50:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.851,49	LR: 0.004599	Loss: 1.637	Speed: 2.12 img/s	Time: 0hrs:2min
[2026-01-14 20:50:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.328,53	LR: 0.004533	Loss: 2.035	Speed: 187.61 img/s	Time: 0hrs:2min
[2026-01-14 20:50:29 - run_regression.py: 233]	INFO	Phase: valid	loss:2.1807	MSE: 1.949	Speed: 6.7355img/s	Time: 15.00s

     MSE  Epoch Cohort
0  1.892      5  Train
0  1.949      5   Test

[2026-01-14 20:50:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.925,58	LR: 0.004444	Loss: 0.946	Speed: 2.12 img/s	Time: 0hrs:3min
[2026-01-14 20:50:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.403,62	LR: 0.004368	Loss: 0.782	Speed: 180.69 img/s	Time: 0hrs:3min
[2026-01-14 20:51:00 - run_regression.py: 233]	INFO	Phase: valid	loss:1.3144	MSE: 1.104	Speed: 6.7701img/s	Time: 14.92s

     MSE  Epoch Cohort
0  0.842      6  Train
0  1.104      6   Test

[2026-01-14 20:51:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.000,67	LR: 0.004268	Loss: 1.166	Speed: 2.12 img/s	Time: 0hrs:3min
[2026-01-14 20:51:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.478,71	LR: 0.004183	Loss: 0.863	Speed: 177.03 img/s	Time: 0hrs:3min
[2026-01-14 20:51:31 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0575	MSE: 0.893	Speed: 6.6598img/s	Time: 15.17s

     MSE  Epoch Cohort
0  0.998      7  Train
0  0.893      7   Test

[2026-01-14 20:51:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.075,76	LR: 0.004072	Loss: 1.198	Speed: 2.08 img/s	Time: 0hrs:4min
[2026-01-14 20:51:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.552,80	LR: 0.003979	Loss: 0.745	Speed: 177.13 img/s	Time: 0hrs:4min
[2026-01-14 20:52:02 - run_regression.py: 233]	INFO	Phase: valid	loss:1.6490	MSE: 1.491	Speed: 6.6652img/s	Time: 15.15s

     MSE  Epoch Cohort
0  1.001      8  Train
0  1.491      8   Test

[2026-01-14 20:52:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.149,85	LR: 0.003858	Loss: 1.084	Speed: 2.09 img/s	Time: 0hrs:4min
[2026-01-14 20:52:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.627,89	LR: 0.003758	Loss: 0.780	Speed: 174.66 img/s	Time: 0hrs:4min
[2026-01-14 20:52:33 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9429	MSE: 0.794	Speed: 6.6761img/s	Time: 15.13s

     MSE  Epoch Cohort
0  0.929      9  Train
0  0.794      9   Test

[2026-01-14 20:52:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.224,94	LR: 0.003630	Loss: 0.794	Speed: 2.09 img/s	Time: 0hrs:5min
[2026-01-14 20:52:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.701,98	LR: 0.003524	Loss: 0.880	Speed: 171.11 img/s	Time: 0hrs:5min
[2026-01-14 20:53:04 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1006	MSE: 1.001	Speed: 6.5982img/s	Time: 15.31s

     MSE  Epoch Cohort
0  0.854     10  Train
0  1.001     10   Test

[2026-01-14 20:53:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.299,103	LR: 0.003389	Loss: 0.820	Speed: 2.08 img/s	Time: 0hrs:5min
[2026-01-14 20:53:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.776,107	LR: 0.003278	Loss: 1.176	Speed: 169.48 img/s	Time: 0hrs:5min
[2026-01-14 20:53:35 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0288	MSE: 0.887	Speed: 6.6748img/s	Time: 15.13s

     MSE  Epoch Cohort
0  0.978     11  Train
0  0.887     11   Test

[2026-01-14 20:53:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.373,112	LR: 0.003138	Loss: 1.024	Speed: 2.10 img/s	Time: 0hrs:6min
[2026-01-14 20:53:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.851,116	LR: 0.003024	Loss: 0.704	Speed: 182.43 img/s	Time: 0hrs:6min
[2026-01-14 20:54:05 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0921	MSE: 0.937	Speed: 6.7532img/s	Time: 14.96s

     MSE  Epoch Cohort
0  0.822     12  Train
0  0.937     12   Test

[2026-01-14 20:54:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.448,121	LR: 0.002880	Loss: 0.844	Speed: 2.12 img/s	Time: 0hrs:6min
[2026-01-14 20:54:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.925,125	LR: 0.002763	Loss: 0.995	Speed: 175.57 img/s	Time: 0hrs:6min
[2026-01-14 20:54:36 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0095	MSE: 0.877	Speed: 6.6891img/s	Time: 15.10s

     MSE  Epoch Cohort
0  0.923     13  Train
0  0.877     13   Test

[2026-01-14 20:54:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 15.522,130	LR: 0.002617	Loss: 0.882	Speed: 2.10 img/s	Time: 0hrs:7min
[2026-01-14 20:54:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.000,134	LR: 0.002500	Loss: 0.888	Speed: 178.10 img/s	Time: 0hrs:7min
[2026-01-14 20:55:07 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9228	MSE: 0.760	Speed: 6.6854img/s	Time: 15.11s

     MSE  Epoch Cohort
0  0.872     14  Train
0  0.760     14   Test

[2026-01-14 20:55:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.597,139	LR: 0.002354	Loss: 0.738	Speed: 2.10 img/s	Time: 0hrs:7min
[2026-01-14 20:55:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.075,143	LR: 0.002237	Loss: 0.969	Speed: 162.51 img/s	Time: 0hrs:7min
[2026-01-14 20:55:38 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0545	MSE: 0.965	Speed: 6.6050img/s	Time: 15.29s

     MSE  Epoch Cohort
0  0.886     15  Train
0  0.965     15   Test

[2026-01-14 20:55:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.672,148	LR: 0.002092	Loss: 0.957	Speed: 2.08 img/s	Time: 0hrs:8min
[2026-01-14 20:55:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.149,152	LR: 0.001976	Loss: 0.825	Speed: 182.49 img/s	Time: 0hrs:8min
[2026-01-14 20:56:09 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8260	MSE: 0.727	Speed: 6.6377img/s	Time: 15.22s

     MSE  Epoch Cohort
0  0.840     16  Train
0  0.727     16   Test

[2026-01-14 20:56:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.746,157	LR: 0.001834	Loss: 0.731	Speed: 2.09 img/s	Time: 0hrs:8min
[2026-01-14 20:56:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.224,161	LR: 0.001722	Loss: 0.924	Speed: 191.56 img/s	Time: 0hrs:9min
[2026-01-14 20:56:40 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9942	MSE: 0.869	Speed: 6.7390img/s	Time: 14.99s

     MSE  Epoch Cohort
0  0.821     17  Train
0  0.869     17   Test

[2026-01-14 20:56:54 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.821,166	LR: 0.001584	Loss: 0.928	Speed: 2.11 img/s	Time: 0hrs:9min
[2026-01-14 20:56:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.299,170	LR: 0.001476	Loss: 0.734	Speed: 173.22 img/s	Time: 0hrs:9min
[2026-01-14 20:57:10 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9688	MSE: 0.740	Speed: 6.7795img/s	Time: 14.90s

     MSE  Epoch Cohort
0  0.837     18  Train
0  0.740     18   Test

[2026-01-14 20:57:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.896,175	LR: 0.001344	Loss: 0.906	Speed: 2.12 img/s	Time: 0hrs:10min
[2026-01-14 20:57:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.373,179	LR: 0.001242	Loss: 0.764	Speed: 181.03 img/s	Time: 0hrs:10min
[2026-01-14 20:57:41 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8617	MSE: 0.731	Speed: 6.7500img/s	Time: 14.96s

     MSE  Epoch Cohort
0  0.799     19  Train
0  0.731     19   Test

[2026-01-14 20:57:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.970,184	LR: 0.001117	Loss: 0.710	Speed: 2.09 img/s	Time: 0hrs:10min
[2026-01-14 20:57:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.448,188	LR: 0.001021	Loss: 0.973	Speed: 173.59 img/s	Time: 0hrs:10min
[2026-01-14 20:58:12 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8436	MSE: 0.749	Speed: 6.5704img/s	Time: 15.37s

     MSE  Epoch Cohort
0  0.831     20  Train
0  0.749     20   Test

[2026-01-14 20:58:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.045,193	LR: 0.000906	Loss: 0.911	Speed: 2.08 img/s	Time: 0hrs:11min
[2026-01-14 20:58:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.522,197	LR: 0.000817	Loss: 0.811	Speed: 182.94 img/s	Time: 0hrs:11min
[2026-01-14 20:58:43 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8818	MSE: 0.737	Speed: 6.6646img/s	Time: 15.15s

     MSE  Epoch Cohort
0  0.810     21  Train
0  0.737     21   Test

[2026-01-14 20:58:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.119,202	LR: 0.000712	Loss: 0.787	Speed: 2.09 img/s	Time: 0hrs:11min
[2026-01-14 20:58:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.597,206	LR: 0.000632	Loss: 0.876	Speed: 181.87 img/s	Time: 0hrs:11min
[2026-01-14 20:59:14 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8519	MSE: 0.735	Speed: 6.6532img/s	Time: 15.18s

     MSE  Epoch Cohort
0  0.821     22  Train
0  0.735     22   Test

[2026-01-14 20:59:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.194,211	LR: 0.000538	Loss: 0.845	Speed: 2.09 img/s	Time: 0hrs:12min
[2026-01-14 20:59:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.672,215	LR: 0.000467	Loss: 0.885	Speed: 162.76 img/s	Time: 0hrs:12min
[2026-01-14 20:59:45 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8504	MSE: 0.734	Speed: 6.7177img/s	Time: 15.04s

     MSE  Epoch Cohort
0  0.846     23  Train
0  0.734     23   Test

[2026-01-14 21:00:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.269,220	LR: 0.000385	Loss: 0.988	Speed: 2.12 img/s	Time: 0hrs:12min
[2026-01-14 21:00:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.746,224	LR: 0.000325	Loss: 0.717	Speed: 187.37 img/s	Time: 0hrs:12min
[2026-01-14 21:00:16 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8757	MSE: 0.731	Speed: 6.8546img/s	Time: 14.73s

     MSE  Epoch Cohort
0  0.817     24  Train
0  0.731     24   Test

[2026-01-14 21:00:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.343,229	LR: 0.000257	Loss: 0.728	Speed: 2.14 img/s	Time: 0hrs:13min
[2026-01-14 21:00:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.821,233	LR: 0.000207	Loss: 0.901	Speed: 166.82 img/s	Time: 0hrs:13min
[2026-01-14 21:00:46 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8655	MSE: 0.728	Speed: 6.7693img/s	Time: 14.92s

     MSE  Epoch Cohort
0  0.812     25  Train
0  0.728     25   Test

[2026-01-14 21:01:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.418,238	LR: 0.000153	Loss: 0.707	Speed: 2.13 img/s	Time: 0hrs:13min
[2026-01-14 21:01:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.896,242	LR: 0.000115	Loss: 0.955	Speed: 184.97 img/s	Time: 0hrs:13min
[2026-01-14 21:01:16 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8416	MSE: 0.724	Speed: 6.7410img/s	Time: 14.98s

     MSE  Epoch Cohort
0  0.821     26  Train
0  0.724     26   Test

[2026-01-14 21:01:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.493,247	LR: 0.000075	Loss: 0.945	Speed: 2.14 img/s	Time: 0hrs:14min
[2026-01-14 21:01:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.970,251	LR: 0.000049	Loss: 0.602	Speed: 185.02 img/s	Time: 0hrs:14min
[2026-01-14 21:01:46 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8525	MSE: 0.725	Speed: 6.8206img/s	Time: 14.81s

     MSE  Epoch Cohort
0  0.834     27  Train
0  0.725     27   Test

[2026-01-14 21:02:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.567,256	LR: 0.000025	Loss: 0.882	Speed: 2.12 img/s	Time: 0hrs:14min
[2026-01-14 21:02:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.045,260	LR: 0.000011	Loss: 0.767	Speed: 179.92 img/s	Time: 0hrs:14min
[2026-01-14 21:02:17 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8242	MSE: 0.721	Speed: 6.8285img/s	Time: 14.79s

     MSE  Epoch Cohort
0  0.804     28  Train
0  0.721     28   Test

[2026-01-14 21:02:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.642,265	LR: 0.000002	Loss: 0.653	Speed: 2.12 img/s	Time: 0hrs:15min
[2026-01-14 21:02:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.119,269	LR: 0.000000	Loss: 1.020	Speed: 170.24 img/s	Time: 0hrs:15min
[2026-01-14 21:02:48 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7855	MSE: 0.719	Speed: 6.6453img/s	Time: 15.20s

     MSE  Epoch Cohort
0  0.805     29  Train
0  0.719     29   Test

[2026-01-14 21:03:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.716,274	LR: 0.000006	Loss: 0.834	Speed: 2.08 img/s	Time: 0hrs:15min
[2026-01-14 21:03:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.194,278	LR: 0.000017	Loss: 0.834	Speed: 164.94 img/s	Time: 0hrs:15min
[2026-01-14 21:03:19 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8240	MSE: 0.724	Speed: 6.6502img/s	Time: 15.19s

     MSE  Epoch Cohort
0  0.778     30  Train
0  0.724     30   Test

[2026-01-14 21:03:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.791,283	LR: 0.000039	Loss: 0.620	Speed: 2.08 img/s	Time: 0hrs:16min
[2026-01-14 21:03:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.269,287	LR: 0.000062	Loss: 0.947	Speed: 207.59 img/s	Time: 0hrs:16min
[2026-01-14 21:03:50 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8272	MSE: 0.728	Speed: 6.6800img/s	Time: 15.12s

     MSE  Epoch Cohort
0  0.819     31  Train
0  0.728     31   Test

[2026-01-14 21:03:50 - run_regression.py: 369]	INFO	Done for training. Best metric is 1.9927470118274948@5 epoch. Average for last 5 iters is 0.7234201161720496
[2026-01-14 21:03:50 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-3.txt
[2026-01-14 21:03:50 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-3.txt
[2026-01-14 21:03:50 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-3.txt
[2026-01-14 21:03:50 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-3.txt
[2026-01-14 21:03:50 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-01-14 21:03:50 - about_log.py: 149]	INFO		Number of samples: 134
[2026-01-14 21:03:50 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\C
[2026-01-14 21:03:50 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task1\split_info\labels.txt
[2026-01-14 21:03:50 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-01-14 21:03:50 - about_log.py: 149]	INFO		Number of samples: 101
[2026-01-14 21:03:50 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\C
[2026-01-14 21:03:50 - run_regression.py: 305]	INFO	Creating model vgg19...
[2026-01-14 21:03:51 - run_regression.py: 352]	INFO	Start training...
[2026-01-14 21:04:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.478,4	LR: 0.004997	Loss: 0.952	Speed: 4.27 img/s	Time: 0hrs:0min
[2026-01-14 21:04:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.955,8	LR: 0.004989	Loss: 1.214	Speed: 200.09 img/s	Time: 0hrs:0min
[2026-01-14 21:04:23 - run_regression.py: 233]	INFO	Phase: valid	loss:1.2619	MSE: 1.114	Speed: 6.6727img/s	Time: 15.14s

     MSE  Epoch Cohort
0  1.057      0  Train
0  1.114      0   Test

[2026-01-14 21:04:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.552,13	LR: 0.004971	Loss: 0.976	Speed: 2.06 img/s	Time: 0hrs:0min
[2026-01-14 21:04:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.030,17	LR: 0.004951	Loss: 0.877	Speed: 207.74 img/s	Time: 0hrs:0min
[2026-01-14 21:04:55 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8069	MSE: 0.804	Speed: 6.6268img/s	Time: 15.24s

     MSE  Epoch Cohort
0  0.937      1  Train
0  0.804      1   Test

[2026-01-14 21:05:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.627,22	LR: 0.004917	Loss: 0.894	Speed: 2.07 img/s	Time: 0hrs:1min
[2026-01-14 21:05:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.104,26	LR: 0.004885	Loss: 0.677	Speed: 211.71 img/s	Time: 0hrs:1min
[2026-01-14 21:05:26 - run_regression.py: 233]	INFO	Phase: valid	loss:1.4551	MSE: 1.417	Speed: 6.7032img/s	Time: 15.07s

     MSE  Epoch Cohort
0  0.830      2  Train
0  1.417      2   Test

[2026-01-14 21:05:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.701,31	LR: 0.004837	Loss: 1.142	Speed: 2.06 img/s	Time: 0hrs:1min
[2026-01-14 21:05:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.179,35	LR: 0.004793	Loss: 0.951	Speed: 199.34 img/s	Time: 0hrs:1min
[2026-01-14 21:05:57 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8403	MSE: 0.770	Speed: 6.7059img/s	Time: 15.06s

     MSE  Epoch Cohort
0  1.045      3  Train
0  0.770      3   Test

[2026-01-14 21:06:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.776,40	LR: 0.004730	Loss: 0.738	Speed: 2.06 img/s	Time: 0hrs:2min
[2026-01-14 21:06:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.254,44	LR: 0.004675	Loss: 0.928	Speed: 207.73 img/s	Time: 0hrs:2min
[2026-01-14 21:06:28 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8063	MSE: 0.773	Speed: 6.6811img/s	Time: 15.12s

     MSE  Epoch Cohort
0  0.846      4  Train
0  0.773      4   Test

[2026-01-14 21:06:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.851,49	LR: 0.004599	Loss: 0.853	Speed: 2.07 img/s	Time: 0hrs:2min
[2026-01-14 21:06:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.328,53	LR: 0.004533	Loss: 0.852	Speed: 210.44 img/s	Time: 0hrs:2min
[2026-01-14 21:07:00 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8577	MSE: 0.773	Speed: 6.6989img/s	Time: 15.08s

     MSE  Epoch Cohort
0  0.857      5  Train
0  0.773      5   Test

[2026-01-14 21:07:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.925,58	LR: 0.004444	Loss: 0.751	Speed: 2.07 img/s	Time: 0hrs:3min
[2026-01-14 21:07:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.403,62	LR: 0.004368	Loss: 0.821	Speed: 211.05 img/s	Time: 0hrs:3min
[2026-01-14 21:07:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8230	MSE: 0.797	Speed: 6.6906img/s	Time: 15.10s

     MSE  Epoch Cohort
0  0.794      6  Train
0  0.797      6   Test

[2026-01-14 21:07:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.000,67	LR: 0.004268	Loss: 0.898	Speed: 2.07 img/s	Time: 0hrs:3min
[2026-01-14 21:07:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.478,71	LR: 0.004183	Loss: 0.790	Speed: 209.98 img/s	Time: 0hrs:3min
[2026-01-14 21:08:02 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8927	MSE: 0.782	Speed: 6.6783img/s	Time: 15.12s

     MSE  Epoch Cohort
0  0.839      7  Train
0  0.782      7   Test

[2026-01-14 21:08:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.075,76	LR: 0.004072	Loss: 1.044	Speed: 2.07 img/s	Time: 0hrs:4min
[2026-01-14 21:08:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.552,80	LR: 0.003979	Loss: 0.624	Speed: 204.30 img/s	Time: 0hrs:4min
[2026-01-14 21:08:33 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8153	MSE: 0.794	Speed: 6.7194img/s	Time: 15.03s

     MSE  Epoch Cohort
0  0.837      8  Train
0  0.794      8   Test

[2026-01-14 21:08:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.149,85	LR: 0.003858	Loss: 0.719	Speed: 2.06 img/s	Time: 0hrs:4min
[2026-01-14 21:08:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.627,89	LR: 0.003758	Loss: 0.981	Speed: 207.35 img/s	Time: 0hrs:4min
[2026-01-14 21:09:05 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9217	MSE: 0.797	Speed: 6.6884img/s	Time: 15.10s

     MSE  Epoch Cohort
0  0.856      9  Train
0  0.797      9   Test

[2026-01-14 21:09:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.224,94	LR: 0.003630	Loss: 0.825	Speed: 2.06 img/s	Time: 0hrs:5min
[2026-01-14 21:09:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.701,98	LR: 0.003524	Loss: 0.830	Speed: 202.63 img/s	Time: 0hrs:5min
[2026-01-14 21:09:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8229	MSE: 0.765	Speed: 6.6069img/s	Time: 15.29s

     MSE  Epoch Cohort
0  0.833     10  Train
0  0.765     10   Test

[2026-01-14 21:09:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.299,103	LR: 0.003389	Loss: 0.793	Speed: 2.05 img/s	Time: 0hrs:5min
[2026-01-14 21:09:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.776,107	LR: 0.003278	Loss: 0.816	Speed: 204.99 img/s	Time: 0hrs:5min
[2026-01-14 21:10:08 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7900	MSE: 0.765	Speed: 6.7058img/s	Time: 15.06s

     MSE  Epoch Cohort
0  0.823     11  Train
0  0.765     11   Test

[2026-01-14 21:10:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.373,112	LR: 0.003138	Loss: 0.866	Speed: 2.06 img/s	Time: 0hrs:6min
[2026-01-14 21:10:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.851,116	LR: 0.003024	Loss: 0.771	Speed: 209.59 img/s	Time: 0hrs:6min
[2026-01-14 21:10:39 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8137	MSE: 0.775	Speed: 6.6090img/s	Time: 15.28s

     MSE  Epoch Cohort
0  0.796     12  Train
0  0.775     12   Test

[2026-01-14 21:10:54 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.448,121	LR: 0.002880	Loss: 0.738	Speed: 2.05 img/s	Time: 0hrs:7min
[2026-01-14 21:10:54 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.925,125	LR: 0.002763	Loss: 0.879	Speed: 211.40 img/s	Time: 0hrs:7min
[2026-01-14 21:11:11 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8049	MSE: 0.760	Speed: 6.7110img/s	Time: 15.05s

     MSE  Epoch Cohort
0  0.832     13  Train
0  0.760     13   Test

[2026-01-14 21:11:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 15.522,130	LR: 0.002617	Loss: 0.869	Speed: 2.07 img/s	Time: 0hrs:7min
[2026-01-14 21:11:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.000,134	LR: 0.002500	Loss: 0.793	Speed: 209.11 img/s	Time: 0hrs:7min
[2026-01-14 21:11:42 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8055	MSE: 0.762	Speed: 6.6894img/s	Time: 15.10s

     MSE  Epoch Cohort
0  0.797     14  Train
0  0.762     14   Test

[2026-01-14 21:11:57 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.597,139	LR: 0.002354	Loss: 0.804	Speed: 2.06 img/s	Time: 0hrs:8min
[2026-01-14 21:11:57 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.075,143	LR: 0.002237	Loss: 0.860	Speed: 205.24 img/s	Time: 0hrs:8min
[2026-01-14 21:12:13 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8213	MSE: 0.768	Speed: 6.6842img/s	Time: 15.11s

     MSE  Epoch Cohort
0  0.813     15  Train
0  0.768     15   Test

[2026-01-14 21:12:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.672,148	LR: 0.002092	Loss: 0.741	Speed: 2.06 img/s	Time: 0hrs:8min
[2026-01-14 21:12:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.149,152	LR: 0.001976	Loss: 0.929	Speed: 207.11 img/s	Time: 0hrs:8min
[2026-01-14 21:12:44 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8359	MSE: 0.761	Speed: 6.7676img/s	Time: 14.92s

     MSE  Epoch Cohort
0  0.805     16  Train
0  0.761     16   Test

[2026-01-14 21:12:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.746,157	LR: 0.001834	Loss: 0.833	Speed: 2.09 img/s	Time: 0hrs:9min
[2026-01-14 21:12:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.224,161	LR: 0.001722	Loss: 0.790	Speed: 208.61 img/s	Time: 0hrs:9min
[2026-01-14 21:13:16 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8131	MSE: 0.760	Speed: 6.6891img/s	Time: 15.10s

     MSE  Epoch Cohort
0  0.802     17  Train
0  0.760     17   Test

[2026-01-14 21:13:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.821,166	LR: 0.001584	Loss: 0.733	Speed: 2.07 img/s	Time: 0hrs:9min
[2026-01-14 21:13:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.299,170	LR: 0.001476	Loss: 0.908	Speed: 207.13 img/s	Time: 0hrs:9min
[2026-01-14 21:13:47 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8254	MSE: 0.758	Speed: 6.7018img/s	Time: 15.07s

     MSE  Epoch Cohort
0  0.823     18  Train
0  0.758     18   Test

[2026-01-14 21:14:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.896,175	LR: 0.001344	Loss: 0.940	Speed: 2.06 img/s	Time: 0hrs:10min
[2026-01-14 21:14:02 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.373,179	LR: 0.001242	Loss: 0.676	Speed: 210.66 img/s	Time: 0hrs:10min
[2026-01-14 21:14:18 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8114	MSE: 0.762	Speed: 6.6768img/s	Time: 15.13s

     MSE  Epoch Cohort
0  0.803     19  Train
0  0.762     19   Test

[2026-01-14 21:14:33 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.970,184	LR: 0.001117	Loss: 0.806	Speed: 2.06 img/s	Time: 0hrs:10min
[2026-01-14 21:14:33 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.448,188	LR: 0.001021	Loss: 0.827	Speed: 210.55 img/s	Time: 0hrs:10min
[2026-01-14 21:14:50 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8033	MSE: 0.764	Speed: 6.6842img/s	Time: 15.11s

     MSE  Epoch Cohort
0  0.807     20  Train
0  0.764     20   Test

[2026-01-14 21:15:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.045,193	LR: 0.000906	Loss: 0.787	Speed: 2.06 img/s	Time: 0hrs:11min
[2026-01-14 21:15:05 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.522,197	LR: 0.000817	Loss: 0.838	Speed: 210.78 img/s	Time: 0hrs:11min
[2026-01-14 21:15:21 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8197	MSE: 0.763	Speed: 6.7176img/s	Time: 15.04s

     MSE  Epoch Cohort
0  0.832     21  Train
0  0.763     21   Test

[2026-01-14 21:15:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.119,202	LR: 0.000712	Loss: 0.915	Speed: 2.07 img/s	Time: 0hrs:11min
[2026-01-14 21:15:36 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.597,206	LR: 0.000632	Loss: 0.738	Speed: 198.96 img/s	Time: 0hrs:11min
[2026-01-14 21:15:52 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8327	MSE: 0.763	Speed: 6.7505img/s	Time: 14.96s

     MSE  Epoch Cohort
0  0.800     22  Train
0  0.763     22   Test

[2026-01-14 21:16:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.194,211	LR: 0.000538	Loss: 1.013	Speed: 2.09 img/s	Time: 0hrs:12min
[2026-01-14 21:16:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.672,215	LR: 0.000467	Loss: 0.637	Speed: 195.98 img/s	Time: 0hrs:12min
[2026-01-14 21:16:23 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8332	MSE: 0.763	Speed: 6.8801img/s	Time: 14.68s

     MSE  Epoch Cohort
0  0.819     23  Train
0  0.763     23   Test

[2026-01-14 21:16:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.269,220	LR: 0.000385	Loss: 0.819	Speed: 2.07 img/s	Time: 0hrs:12min
[2026-01-14 21:16:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.746,224	LR: 0.000325	Loss: 0.829	Speed: 209.08 img/s	Time: 0hrs:12min
[2026-01-14 21:16:54 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8057	MSE: 0.762	Speed: 6.6357img/s	Time: 15.22s

     MSE  Epoch Cohort
0  0.788     24  Train
0  0.762     24   Test

[2026-01-14 21:17:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.343,229	LR: 0.000257	Loss: 0.731	Speed: 2.06 img/s	Time: 0hrs:13min
[2026-01-14 21:17:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.821,233	LR: 0.000207	Loss: 0.889	Speed: 205.33 img/s	Time: 0hrs:13min
[2026-01-14 21:17:26 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8255	MSE: 0.762	Speed: 6.7658img/s	Time: 14.93s

     MSE  Epoch Cohort
0  0.793     25  Train
0  0.762     25   Test

[2026-01-14 21:17:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.418,238	LR: 0.000153	Loss: 0.814	Speed: 2.10 img/s	Time: 0hrs:13min
[2026-01-14 21:17:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.896,242	LR: 0.000115	Loss: 0.799	Speed: 208.40 img/s	Time: 0hrs:13min
[2026-01-14 21:17:56 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8041	MSE: 0.762	Speed: 6.8908img/s	Time: 14.66s

     MSE  Epoch Cohort
0  0.808     26  Train
0  0.762     26   Test

[2026-01-14 21:18:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.493,247	LR: 0.000075	Loss: 0.912	Speed: 2.11 img/s	Time: 0hrs:14min
[2026-01-14 21:18:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.970,251	LR: 0.000049	Loss: 0.676	Speed: 203.02 img/s	Time: 0hrs:14min
[2026-01-14 21:18:27 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9401	MSE: 0.762	Speed: 6.8104img/s	Time: 14.83s

     MSE  Epoch Cohort
0  0.816     27  Train
0  0.762     27   Test

[2026-01-14 21:18:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.567,256	LR: 0.000025	Loss: 0.734	Speed: 2.11 img/s	Time: 0hrs:14min
[2026-01-14 21:18:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.045,260	LR: 0.000011	Loss: 0.902	Speed: 211.18 img/s	Time: 0hrs:14min
[2026-01-14 21:18:57 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8282	MSE: 0.762	Speed: 6.8095img/s	Time: 14.83s

     MSE  Epoch Cohort
0  0.817     28  Train
0  0.762     28   Test

[2026-01-14 21:19:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.642,265	LR: 0.000002	Loss: 0.889	Speed: 2.10 img/s	Time: 0hrs:15min
[2026-01-14 21:19:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.119,269	LR: 0.000000	Loss: 0.706	Speed: 210.58 img/s	Time: 0hrs:15min
[2026-01-14 21:19:28 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8125	MSE: 0.762	Speed: 6.8737img/s	Time: 14.69s

     MSE  Epoch Cohort
0  0.794     29  Train
0  0.762     29   Test

[2026-01-14 21:19:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.716,274	LR: 0.000006	Loss: 0.854	Speed: 2.11 img/s	Time: 0hrs:15min
[2026-01-14 21:19:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.194,278	LR: 0.000017	Loss: 0.766	Speed: 209.91 img/s	Time: 0hrs:15min
[2026-01-14 21:19:59 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8150	MSE: 0.762	Speed: 6.8698img/s	Time: 14.70s

     MSE  Epoch Cohort
0  0.805     30  Train
0  0.762     30   Test

[2026-01-14 21:20:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.791,283	LR: 0.000039	Loss: 0.726	Speed: 2.11 img/s	Time: 0hrs:16min
[2026-01-14 21:20:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.269,287	LR: 0.000062	Loss: 0.899	Speed: 209.09 img/s	Time: 0hrs:16min
[2026-01-14 21:20:29 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8306	MSE: 0.761	Speed: 6.8909img/s	Time: 14.66s

     MSE  Epoch Cohort
0  0.801     31  Train
0  0.761     31   Test

[2026-01-14 21:20:30 - run_regression.py: 369]	INFO	Done for training. Best metric is 1.4171286734116533@3 epoch. Average for last 5 iters is 0.7615438251700695
[2026-01-14 21:20:30 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-3.txt
[2026-01-14 21:20:30 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-3.txt
[2026-01-14 21:20:30 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-3.txt
[2026-01-14 21:20:30 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-3.txt
[2026-01-14 21:20:30 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-01-14 21:20:30 - about_log.py: 149]	INFO		Number of samples: 134
[2026-01-14 21:20:30 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\C
[2026-01-14 21:20:30 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task1\split_info\labels.txt
[2026-01-14 21:20:30 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-01-14 21:20:30 - about_log.py: 149]	INFO		Number of samples: 101
[2026-01-14 21:20:30 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\C
[2026-01-14 21:20:30 - run_regression.py: 305]	INFO	Creating model inception_v3...
[2026-01-14 21:20:31 - run_regression.py: 352]	INFO	Start training...
[2026-01-14 21:20:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.478,4	LR: 0.004997	Loss: 7.625	Speed: 4.42 img/s	Time: 0hrs:0min
[2026-01-14 21:20:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.955,8	LR: 0.004989	Loss: 12.975	Speed: 202.21 img/s	Time: 0hrs:0min
[2026-01-14 21:21:02 - run_regression.py: 233]	INFO	Phase: valid	loss:3.2983	MSE: 3.000	Speed: 6.8370img/s	Time: 14.77s

     MSE  Epoch Cohort
0  10.26      0  Train
0   3.00      0   Test

[2026-01-14 21:21:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.552,13	LR: 0.004971	Loss: 2.091	Speed: 2.16 img/s	Time: 0hrs:0min
[2026-01-14 21:21:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.030,17	LR: 0.004951	Loss: 1.137	Speed: 190.05 img/s	Time: 0hrs:0min
[2026-01-14 21:21:32 - run_regression.py: 233]	INFO	Phase: valid	loss:2.1542	MSE: 1.993	Speed: 6.8177img/s	Time: 14.81s

     MSE  Epoch Cohort
0  1.177      1  Train
0  1.993      1   Test

[2026-01-14 21:21:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.627,22	LR: 0.004917	Loss: 1.525	Speed: 2.14 img/s	Time: 0hrs:1min
[2026-01-14 21:21:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.104,26	LR: 0.004885	Loss: 1.411	Speed: 201.15 img/s	Time: 0hrs:1min
[2026-01-14 21:22:02 - run_regression.py: 233]	INFO	Phase: valid	loss:2.1862	MSE: 2.053	Speed: 6.8288img/s	Time: 14.79s

     MSE  Epoch Cohort
0  1.306      2  Train
0  2.053      2   Test

[2026-01-14 21:22:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.701,31	LR: 0.004837	Loss: 1.495	Speed: 2.14 img/s	Time: 0hrs:1min
[2026-01-14 21:22:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.179,35	LR: 0.004793	Loss: 1.179	Speed: 199.39 img/s	Time: 0hrs:1min
[2026-01-14 21:22:32 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8236	MSE: 0.792	Speed: 6.8378img/s	Time: 14.77s

     MSE  Epoch Cohort
0  1.005      3  Train
0  0.792      3   Test

[2026-01-14 21:22:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.776,40	LR: 0.004730	Loss: 1.449	Speed: 2.14 img/s	Time: 0hrs:2min
[2026-01-14 21:22:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.254,44	LR: 0.004675	Loss: 1.349	Speed: 200.59 img/s	Time: 0hrs:2min
[2026-01-14 21:23:02 - run_regression.py: 233]	INFO	Phase: valid	loss:1.2788	MSE: 1.073	Speed: 6.8559img/s	Time: 14.73s

     MSE  Epoch Cohort
0  1.037      4  Train
0  1.073      4   Test

[2026-01-14 21:23:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.851,49	LR: 0.004599	Loss: 1.729	Speed: 2.16 img/s	Time: 0hrs:2min
[2026-01-14 21:23:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.328,53	LR: 0.004533	Loss: 1.385	Speed: 189.87 img/s	Time: 0hrs:2min
[2026-01-14 21:23:32 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0294	MSE: 0.979	Speed: 6.8565img/s	Time: 14.73s

     MSE  Epoch Cohort
0  1.303      5  Train
0  0.979      5   Test

[2026-01-14 21:23:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.925,58	LR: 0.004444	Loss: 1.407	Speed: 2.13 img/s	Time: 0hrs:3min
[2026-01-14 21:23:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.403,62	LR: 0.004368	Loss: 1.324	Speed: 196.19 img/s	Time: 0hrs:3min
[2026-01-14 21:24:03 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0446	MSE: 0.829	Speed: 6.7751img/s	Time: 14.91s

     MSE  Epoch Cohort
0  1.020      6  Train
0  0.829      6   Test

[2026-01-14 21:24:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.000,67	LR: 0.004268	Loss: 1.331	Speed: 2.13 img/s	Time: 0hrs:3min
[2026-01-14 21:24:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.478,71	LR: 0.004183	Loss: 1.378	Speed: 201.89 img/s	Time: 0hrs:3min
[2026-01-14 21:24:33 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8534	MSE: 0.800	Speed: 6.8565img/s	Time: 14.73s

     MSE  Epoch Cohort
0  1.086      7  Train
0  0.800      7   Test

[2026-01-14 21:24:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.075,76	LR: 0.004072	Loss: 1.381	Speed: 2.16 img/s	Time: 0hrs:4min
[2026-01-14 21:24:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.552,80	LR: 0.003979	Loss: 1.633	Speed: 196.93 img/s	Time: 0hrs:4min
[2026-01-14 21:25:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9998	MSE: 0.941	Speed: 6.8546img/s	Time: 14.73s

     MSE  Epoch Cohort
0  1.216      8  Train
0  0.941      8   Test

[2026-01-14 21:25:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.149,85	LR: 0.003858	Loss: 1.383	Speed: 2.16 img/s	Time: 0hrs:4min
[2026-01-14 21:25:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.627,89	LR: 0.003758	Loss: 1.340	Speed: 203.34 img/s	Time: 0hrs:4min
[2026-01-14 21:25:33 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8576	MSE: 0.783	Speed: 6.8442img/s	Time: 14.76s

     MSE  Epoch Cohort
0  1.065      9  Train
0  0.783      9   Test

[2026-01-14 21:25:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.224,94	LR: 0.003630	Loss: 1.282	Speed: 2.14 img/s	Time: 0hrs:5min
[2026-01-14 21:25:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.701,98	LR: 0.003524	Loss: 1.448	Speed: 202.30 img/s	Time: 0hrs:5min
[2026-01-14 21:26:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8297	MSE: 0.763	Speed: 6.7876img/s	Time: 14.88s

     MSE  Epoch Cohort
0  0.963     10  Train
0  0.763     10   Test

[2026-01-14 21:26:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.299,103	LR: 0.003389	Loss: 1.479	Speed: 2.13 img/s	Time: 0hrs:5min
[2026-01-14 21:26:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.776,107	LR: 0.003278	Loss: 1.354	Speed: 210.88 img/s	Time: 0hrs:5min
[2026-01-14 21:26:34 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8110	MSE: 0.771	Speed: 6.7518img/s	Time: 14.96s

     MSE  Epoch Cohort
0  1.040     11  Train
0  0.771     11   Test

[2026-01-14 21:26:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.373,112	LR: 0.003138	Loss: 1.281	Speed: 2.11 img/s	Time: 0hrs:6min
[2026-01-14 21:26:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.851,116	LR: 0.003024	Loss: 1.429	Speed: 210.18 img/s	Time: 0hrs:6min
[2026-01-14 21:27:04 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8393	MSE: 0.779	Speed: 6.7472img/s	Time: 14.97s

     MSE  Epoch Cohort
0  0.926     12  Train
0  0.779     12   Test

[2026-01-14 21:27:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.448,121	LR: 0.002880	Loss: 1.442	Speed: 2.11 img/s	Time: 0hrs:6min
[2026-01-14 21:27:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.925,125	LR: 0.002763	Loss: 1.209	Speed: 211.54 img/s	Time: 0hrs:6min
[2026-01-14 21:27:35 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8547	MSE: 0.751	Speed: 6.7041img/s	Time: 15.07s

     MSE  Epoch Cohort
0  1.014     13  Train
0  0.751     13   Test

[2026-01-14 21:27:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 15.522,130	LR: 0.002617	Loss: 1.412	Speed: 2.11 img/s	Time: 0hrs:7min
[2026-01-14 21:27:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.000,134	LR: 0.002500	Loss: 1.118	Speed: 212.45 img/s	Time: 0hrs:7min
[2026-01-14 21:28:05 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8558	MSE: 0.744	Speed: 6.7206img/s	Time: 15.03s

     MSE  Epoch Cohort
0  0.846     14  Train
0  0.744     14   Test

[2026-01-14 21:28:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.597,139	LR: 0.002354	Loss: 1.083	Speed: 2.11 img/s	Time: 0hrs:7min
[2026-01-14 21:28:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.075,143	LR: 0.002237	Loss: 1.500	Speed: 198.95 img/s	Time: 0hrs:7min
[2026-01-14 21:28:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8752	MSE: 0.796	Speed: 6.7388img/s	Time: 14.99s

     MSE  Epoch Cohort
0  1.061     15  Train
0  0.796     15   Test

[2026-01-14 21:28:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.672,148	LR: 0.002092	Loss: 1.206	Speed: 2.11 img/s	Time: 0hrs:8min
[2026-01-14 21:28:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.149,152	LR: 0.001976	Loss: 1.296	Speed: 200.06 img/s	Time: 0hrs:8min
[2026-01-14 21:29:07 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8678	MSE: 0.787	Speed: 6.7432img/s	Time: 14.98s

     MSE  Epoch Cohort
0  0.941     16  Train
0  0.787     16   Test

[2026-01-14 21:29:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.746,157	LR: 0.001834	Loss: 1.524	Speed: 2.10 img/s	Time: 0hrs:8min
[2026-01-14 21:29:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.224,161	LR: 0.001722	Loss: 1.264	Speed: 200.80 img/s	Time: 0hrs:8min
[2026-01-14 21:29:38 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7976	MSE: 0.760	Speed: 6.6509img/s	Time: 15.19s

     MSE  Epoch Cohort
0  1.096     17  Train
0  0.760     17   Test

[2026-01-14 21:29:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.821,166	LR: 0.001584	Loss: 1.191	Speed: 2.09 img/s	Time: 0hrs:9min
[2026-01-14 21:29:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.299,170	LR: 0.001476	Loss: 1.495	Speed: 210.12 img/s	Time: 0hrs:9min
[2026-01-14 21:30:09 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8625	MSE: 0.789	Speed: 6.6492img/s	Time: 15.19s

     MSE  Epoch Cohort
0  1.111     18  Train
0  0.789     18   Test

[2026-01-14 21:30:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.896,175	LR: 0.001344	Loss: 1.209	Speed: 2.10 img/s	Time: 0hrs:9min
[2026-01-14 21:30:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.373,179	LR: 0.001242	Loss: 1.477	Speed: 210.92 img/s	Time: 0hrs:9min
[2026-01-14 21:30:39 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8298	MSE: 0.762	Speed: 6.7335img/s	Time: 15.00s

     MSE  Epoch Cohort
0  1.070     19  Train
0  0.762     19   Test

[2026-01-14 21:30:54 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.970,184	LR: 0.001117	Loss: 1.284	Speed: 2.11 img/s	Time: 0hrs:10min
[2026-01-14 21:30:54 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.448,188	LR: 0.001021	Loss: 1.106	Speed: 199.39 img/s	Time: 0hrs:10min
[2026-01-14 21:31:10 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8096	MSE: 0.759	Speed: 6.7671img/s	Time: 14.93s

     MSE  Epoch Cohort
0  0.865     20  Train
0  0.759     20   Test

[2026-01-14 21:31:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.045,193	LR: 0.000906	Loss: 1.365	Speed: 2.12 img/s	Time: 0hrs:10min
[2026-01-14 21:31:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.522,197	LR: 0.000817	Loss: 1.543	Speed: 210.66 img/s	Time: 0hrs:10min
[2026-01-14 21:31:41 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8132	MSE: 0.762	Speed: 6.6613img/s	Time: 15.16s

     MSE  Epoch Cohort
0  1.103     21  Train
0  0.762     21   Test

[2026-01-14 21:31:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.119,202	LR: 0.000712	Loss: 1.325	Speed: 2.10 img/s	Time: 0hrs:11min
[2026-01-14 21:31:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.597,206	LR: 0.000632	Loss: 1.108	Speed: 210.47 img/s	Time: 0hrs:11min
[2026-01-14 21:32:11 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7890	MSE: 0.760	Speed: 6.7300img/s	Time: 15.01s

     MSE  Epoch Cohort
0  1.064     22  Train
0  0.760     22   Test

[2026-01-14 21:32:26 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.194,211	LR: 0.000538	Loss: 1.198	Speed: 2.11 img/s	Time: 0hrs:11min
[2026-01-14 21:32:26 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.672,215	LR: 0.000467	Loss: 1.361	Speed: 207.18 img/s	Time: 0hrs:11min
[2026-01-14 21:32:42 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7997	MSE: 0.753	Speed: 6.7381img/s	Time: 14.99s

     MSE  Epoch Cohort
0  0.954     23  Train
0  0.753     23   Test

[2026-01-14 21:32:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.269,220	LR: 0.000385	Loss: 1.501	Speed: 2.12 img/s	Time: 0hrs:12min
[2026-01-14 21:32:57 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.746,224	LR: 0.000325	Loss: 1.327	Speed: 208.29 img/s	Time: 0hrs:12min
[2026-01-14 21:33:12 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8069	MSE: 0.753	Speed: 6.7436img/s	Time: 14.98s

     MSE  Epoch Cohort
0  1.019     24  Train
0  0.753     24   Test

[2026-01-14 21:33:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.343,229	LR: 0.000257	Loss: 1.427	Speed: 2.11 img/s	Time: 0hrs:12min
[2026-01-14 21:33:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.821,233	LR: 0.000207	Loss: 1.122	Speed: 212.86 img/s	Time: 0hrs:12min
[2026-01-14 21:33:43 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8132	MSE: 0.753	Speed: 6.7426img/s	Time: 14.98s

     MSE  Epoch Cohort
0  0.972     25  Train
0  0.753     25   Test

[2026-01-14 21:33:57 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.418,238	LR: 0.000153	Loss: 1.328	Speed: 2.11 img/s	Time: 0hrs:13min
[2026-01-14 21:33:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.896,242	LR: 0.000115	Loss: 1.428	Speed: 211.30 img/s	Time: 0hrs:13min
[2026-01-14 21:34:14 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8968	MSE: 0.754	Speed: 6.7374img/s	Time: 14.99s

     MSE  Epoch Cohort
0  1.056     26  Train
0  0.754     26   Test

[2026-01-14 21:34:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.493,247	LR: 0.000075	Loss: 1.148	Speed: 2.11 img/s	Time: 0hrs:13min
[2026-01-14 21:34:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.970,251	LR: 0.000049	Loss: 1.305	Speed: 201.89 img/s	Time: 0hrs:13min
[2026-01-14 21:34:44 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8667	MSE: 0.753	Speed: 6.6725img/s	Time: 15.14s

     MSE  Epoch Cohort
0  0.939     27  Train
0  0.753     27   Test

[2026-01-14 21:34:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.567,256	LR: 0.000025	Loss: 1.298	Speed: 2.10 img/s	Time: 0hrs:14min
[2026-01-14 21:34:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.045,260	LR: 0.000011	Loss: 1.112	Speed: 199.53 img/s	Time: 0hrs:14min
[2026-01-14 21:35:15 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8788	MSE: 0.756	Speed: 6.7440img/s	Time: 14.98s

     MSE  Epoch Cohort
0  0.922     28  Train
0  0.756     28   Test

[2026-01-14 21:35:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.642,265	LR: 0.000002	Loss: 1.234	Speed: 2.11 img/s	Time: 0hrs:14min
[2026-01-14 21:35:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.119,269	LR: 0.000000	Loss: 1.194	Speed: 200.32 img/s	Time: 0hrs:14min
[2026-01-14 21:35:46 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8098	MSE: 0.753	Speed: 6.6675img/s	Time: 15.15s

     MSE  Epoch Cohort
0  0.902     29  Train
0  0.753     29   Test

[2026-01-14 21:36:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.716,274	LR: 0.000006	Loss: 1.443	Speed: 2.10 img/s	Time: 0hrs:15min
[2026-01-14 21:36:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.194,278	LR: 0.000017	Loss: 1.174	Speed: 208.98 img/s	Time: 0hrs:15min
[2026-01-14 21:36:16 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8007	MSE: 0.756	Speed: 6.7197img/s	Time: 15.03s

     MSE  Epoch Cohort
0  0.811     30  Train
0  0.756     30   Test

[2026-01-14 21:36:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.791,283	LR: 0.000039	Loss: 1.237	Speed: 2.10 img/s	Time: 0hrs:15min
[2026-01-14 21:36:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.269,287	LR: 0.000062	Loss: 1.296	Speed: 208.82 img/s	Time: 0hrs:16min
[2026-01-14 21:36:47 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8046	MSE: 0.753	Speed: 6.7364img/s	Time: 14.99s

     MSE  Epoch Cohort
0  0.927     31  Train
0  0.753     31   Test

[2026-01-14 21:36:47 - run_regression.py: 369]	INFO	Done for training. Best metric is 3.000278907867099@1 epoch. Average for last 5 iters is 0.7540860164334356