In [ ]:
import os
from onekey_algo.regression.run_regression import main as reg_main
from collections import namedtuple
from onekey_algo import get_param_in_cwd

# 设置参数
task_type = 'L'
root = get_param_in_cwd('radio_dir')
for cv in range(0, 1):
    for model_name in ['resnet50', 'resnet18', 'resnet101', 'densenet121', 'vgg19', 'inception_v3']:
        train_f = os.path.join('split_info', f'train-RND-{cv}.txt')
        val_f = os.path.join('split_info', f'val-RND-{cv}.txt')
        labels_f = os.path.join('split_info', 'labels.txt')
        data_pattern = os.path.join(root, task_type)
        params = dict(train=train_f,
                      valid=val_f,
                      labels_file=labels_f,
                      in_channels=3,
                      data_pattern=data_pattern,
                      j=6,
                      max2use=None,
                      val_max2use=None,
                      batch_balance=False,
                      normalize_method='imagenet',
                      model_name=model_name,
                      gpus=[0],
                      batch_size=16,
                      epochs=64 if model_name not in ['TwinsSVT', 'CrossFormer', 'SimpleViT'] else 96,
                      init_lr=0.001 if model_name not in ['TwinsSVT', 'CrossFormer', 'SimpleViT'] else 0.001,
                      optimizer='sgd',
                      retrain='',
                      model_root= os.path.join(root, 'Lmodels', f"CV-{cv}"),
                      iters_start=0,
                      iters_verbose=4,
                      save_per_epoch=True,
                      add_date=False,
                      pretrained=True)
        # 训练模型
        Args = namedtuple("Args", params)
        reg_main(Args(**params))

[2026-02-10 22:37:40 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-0.txt
[2026-02-10 22:37:40 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-0.txt
[2026-02-10 22:37:40 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-0.txt
[2026-02-10 22:37:40 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-0.txt
[2026-02-10 22:37:40 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-02-10 22:37:40 - about_log.py: 149]	INFO		Number of samples: 169
[2026-02-10 22:37:40 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-10 22:37:40 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task2\split_info\labels.txt
[2026-02-10 22:37:40 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-02-10 22:37:40 - about_log.py: 149]	INFO		Number of samples: 120
[2026-02-10 22:37:40 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-10 22:37:40 - run_regression.py: 305]	INFO	Creating model resnet50...
[2026-02-10 22:37:40 - resnet.py: 271]	INFO	Pretrained model loaded!
[2026-02-10 22:37:40 - run_regression.py: 352]	INFO	Start training...
[2026-02-10 22:37:41 - common.py: 113]	INFO	Successfully delete directory D:\\20251014-fenghexin_fuxin\Lmodels\CV-0\resnet50\train
[2026-02-10 22:37:41 - common.py: 113]	INFO	Successfully delete directory D:\\20251014-fenghexin_fuxin\Lmodels\CV-0\resnet50\valid
[2026-02-10 22:37:41 - common.py: 113]	INFO	Successfully delete directory D:\\20251014-fenghexin_fuxin\Lmodels\CV-0\resnet50\viz
[2026-02-10 22:37:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.379,4	LR: 0.001000	Loss: 0.966	Speed: 3.66 img/s	Time: 0hrs:0min
[2026-02-10 22:37:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.757,8	LR: 0.001000	Loss: 0.843	Speed: 413.15 img/s	Time: 0hrs:0min
[2026-02-10 22:38:13 - run_regression.py: 233]	INFO	Phase: valid	loss:1.4764	MSE: 1.394	Speed: 8.2575img/s	Time: 14.53s

     MSE  Epoch Cohort
0  0.962      0  Train
0  1.394      0   Test

[2026-02-10 22:38:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.420,15	LR: 0.000999	Loss: 1.183	Speed: 2.19 img/s	Time: 0hrs:0min
[2026-02-10 22:38:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.799,19	LR: 0.000998	Loss: 1.077	Speed: 418.85 img/s	Time: 0hrs:0min
[2026-02-10 22:38:42 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9564	MSE: 0.898	Speed: 8.3097img/s	Time: 14.44s

     MSE  Epoch Cohort
0  1.005      1  Train
0  0.898      1   Test

[2026-02-10 22:38:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.462,26	LR: 0.000996	Loss: 0.984	Speed: 2.20 img/s	Time: 0hrs:1min
[2026-02-10 22:38:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.840,30	LR: 0.000995	Loss: 0.950	Speed: 417.23 img/s	Time: 0hrs:1min
[2026-02-10 22:39:11 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8421	MSE: 0.781	Speed: 8.3209img/s	Time: 14.42s

     MSE  Epoch Cohort
0  0.893      2  Train
0  0.781      2   Test

[2026-02-10 22:39:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.503,37	LR: 0.000993	Loss: 0.926	Speed: 2.20 img/s	Time: 0hrs:1min
[2026-02-10 22:39:26 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.882,41	LR: 0.000991	Loss: 0.984	Speed: 417.71 img/s	Time: 0hrs:1min
[2026-02-10 22:39:41 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8262	MSE: 0.784	Speed: 8.3377img/s	Time: 14.39s

     MSE  Epoch Cohort
0  0.922      3  Train
0  0.784      3   Test

[2026-02-10 22:39:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.544,48	LR: 0.000988	Loss: 0.735	Speed: 2.20 img/s	Time: 0hrs:2min
[2026-02-10 22:39:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.923,52	LR: 0.000985	Loss: 1.013	Speed: 416.05 img/s	Time: 0hrs:2min
[2026-02-10 22:40:10 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7906	MSE: 0.785	Speed: 8.3154img/s	Time: 14.43s

     MSE  Epoch Cohort
0  0.913      4  Train
0  0.785      4   Test

[2026-02-10 22:40:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.586,59	LR: 0.000981	Loss: 1.028	Speed: 2.20 img/s	Time: 0hrs:2min
[2026-02-10 22:40:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.964,63	LR: 0.000979	Loss: 1.021	Speed: 424.94 img/s	Time: 0hrs:2min
[2026-02-10 22:40:39 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8086	MSE: 0.783	Speed: 8.3287img/s	Time: 14.41s

     MSE  Epoch Cohort
0  0.921      5  Train
0  0.783      5   Test

[2026-02-10 22:40:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.627,70	LR: 0.000974	Loss: 0.923	Speed: 2.20 img/s	Time: 0hrs:3min
[2026-02-10 22:40:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.006,74	LR: 0.000971	Loss: 0.843	Speed: 416.83 img/s	Time: 0hrs:3min
[2026-02-10 22:41:08 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8202	MSE: 0.792	Speed: 8.3192img/s	Time: 14.42s

     MSE  Epoch Cohort
0  0.913      6  Train
0  0.792      6   Test

[2026-02-10 22:41:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.669,81	LR: 0.000965	Loss: 0.883	Speed: 2.20 img/s	Time: 0hrs:3min
[2026-02-10 22:41:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.047,85	LR: 0.000961	Loss: 0.981	Speed: 424.09 img/s	Time: 0hrs:3min
[2026-02-10 22:41:37 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8607	MSE: 0.818	Speed: 8.3433img/s	Time: 14.38s

     MSE  Epoch Cohort
0  0.874      7  Train
0  0.818      7   Test

[2026-02-10 22:41:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.710,92	LR: 0.000955	Loss: 0.862	Speed: 2.20 img/s	Time: 0hrs:4min
[2026-02-10 22:41:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.089,96	LR: 0.000951	Loss: 0.896	Speed: 427.00 img/s	Time: 0hrs:4min
[2026-02-10 22:42:06 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8041	MSE: 0.776	Speed: 8.4293img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.873      8  Train
0  0.776      8   Test

[2026-02-10 22:42:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.751,103	LR: 0.000944	Loss: 0.834	Speed: 2.22 img/s	Time: 0hrs:4min
[2026-02-10 22:42:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.130,107	LR: 0.000939	Loss: 0.876	Speed: 422.72 img/s	Time: 0hrs:4min
[2026-02-10 22:42:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8315	MSE: 0.780	Speed: 8.2086img/s	Time: 14.62s

     MSE  Epoch Cohort
0  0.916      9  Train
0  0.780      9   Test

[2026-02-10 22:42:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.793,114	LR: 0.000931	Loss: 0.942	Speed: 2.19 img/s	Time: 0hrs:5min
[2026-02-10 22:42:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.172,118	LR: 0.000927	Loss: 0.772	Speed: 416.01 img/s	Time: 0hrs:5min
[2026-02-10 22:43:05 - run_regression.py: 233]	INFO	Phase: valid	loss:1.2608	MSE: 1.202	Speed: 8.3428img/s	Time: 14.38s

     MSE  Epoch Cohort
0  0.864     10  Train
0  1.202     10   Test

[2026-02-10 22:43:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.834,125	LR: 0.000918	Loss: 0.999	Speed: 2.20 img/s	Time: 0hrs:5min
[2026-02-10 22:43:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.213,129	LR: 0.000913	Loss: 0.922	Speed: 417.54 img/s	Time: 0hrs:5min
[2026-02-10 22:43:34 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7872	MSE: 0.774	Speed: 8.3247img/s	Time: 14.41s

     MSE  Epoch Cohort
0  0.946     11  Train
0  0.774     11   Test

[2026-02-10 22:43:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.876,136	LR: 0.000903	Loss: 0.816	Speed: 2.20 img/s	Time: 0hrs:6min
[2026-02-10 22:43:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.254,140	LR: 0.000898	Loss: 0.971	Speed: 426.92 img/s	Time: 0hrs:6min
[2026-02-10 22:44:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8436	MSE: 0.824	Speed: 8.3271img/s	Time: 14.41s

     MSE  Epoch Cohort
0  0.934     12  Train
0  0.824     12   Test

[2026-02-10 22:44:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.917,147	LR: 0.000888	Loss: 0.992	Speed: 2.20 img/s	Time: 0hrs:6min
[2026-02-10 22:44:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.296,151	LR: 0.000882	Loss: 0.853	Speed: 426.66 img/s	Time: 0hrs:6min
[2026-02-10 22:44:33 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8822	MSE: 0.861	Speed: 8.2874img/s	Time: 14.48s

     MSE  Epoch Cohort
0  0.885     13  Train
0  0.861     13   Test

[2026-02-10 22:44:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.959,158	LR: 0.000871	Loss: 1.117	Speed: 2.19 img/s	Time: 0hrs:7min
[2026-02-10 22:44:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 15.337,162	LR: 0.000865	Loss: 0.789	Speed: 418.27 img/s	Time: 0hrs:7min
[2026-02-10 22:45:02 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8199	MSE: 0.763	Speed: 8.3116img/s	Time: 14.44s

     MSE  Epoch Cohort
0  0.947     14  Train
0  0.763     14   Test

[2026-02-10 22:45:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.000,169	LR: 0.000854	Loss: 0.928	Speed: 2.21 img/s	Time: 0hrs:7min
[2026-02-10 22:45:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.379,173	LR: 0.000847	Loss: 0.863	Speed: 421.69 img/s	Time: 0hrs:7min
[2026-02-10 22:45:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8035	MSE: 0.784	Speed: 8.2161img/s	Time: 14.61s

     MSE  Epoch Cohort
0  0.910     15  Train
0  0.784     15   Test

[2026-02-10 22:45:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.041,180	LR: 0.000835	Loss: 0.884	Speed: 2.19 img/s	Time: 0hrs:8min
[2026-02-10 22:45:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.420,184	LR: 0.000828	Loss: 0.875	Speed: 417.97 img/s	Time: 0hrs:8min
[2026-02-10 22:46:00 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9481	MSE: 0.898	Speed: 8.3219img/s	Time: 14.42s

     MSE  Epoch Cohort
0  0.899     16  Train
0  0.898     16   Test

[2026-02-10 22:46:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.083,191	LR: 0.000816	Loss: 0.823	Speed: 2.20 img/s	Time: 0hrs:8min
[2026-02-10 22:46:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.462,195	LR: 0.000808	Loss: 1.072	Speed: 422.48 img/s	Time: 0hrs:8min
[2026-02-10 22:46:30 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8501	MSE: 0.777	Speed: 8.3269img/s	Time: 14.41s

     MSE  Epoch Cohort
0  0.928     17  Train
0  0.777     17   Test

[2026-02-10 22:46:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.124,202	LR: 0.000795	Loss: 0.839	Speed: 2.20 img/s	Time: 0hrs:9min
[2026-02-10 22:46:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.503,206	LR: 0.000788	Loss: 0.929	Speed: 423.03 img/s	Time: 0hrs:9min
[2026-02-10 22:46:59 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7918	MSE: 0.770	Speed: 8.3328img/s	Time: 14.40s

     MSE  Epoch Cohort
0  0.897     18  Train
0  0.770     18   Test

[2026-02-10 22:47:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.166,213	LR: 0.000774	Loss: 1.044	Speed: 2.20 img/s	Time: 0hrs:9min
[2026-02-10 22:47:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.544,217	LR: 0.000767	Loss: 0.974	Speed: 414.79 img/s	Time: 0hrs:9min
[2026-02-10 22:47:28 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7873	MSE: 0.758	Speed: 8.3032img/s	Time: 14.45s

     MSE  Epoch Cohort
0  0.925     19  Train
0  0.758     19   Test

[2026-02-10 22:47:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.207,224	LR: 0.000753	Loss: 0.879	Speed: 2.20 img/s	Time: 0hrs:10min
[2026-02-10 22:47:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.586,228	LR: 0.000745	Loss: 0.968	Speed: 421.94 img/s	Time: 0hrs:10min
[2026-02-10 22:47:57 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7901	MSE: 0.754	Speed: 8.3082img/s	Time: 14.44s

     MSE  Epoch Cohort
0  0.915     20  Train
0  0.754     20   Test

[2026-02-10 22:48:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.249,235	LR: 0.000730	Loss: 0.655	Speed: 2.20 img/s	Time: 0hrs:10min
[2026-02-10 22:48:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.627,239	LR: 0.000722	Loss: 0.967	Speed: 429.48 img/s	Time: 0hrs:10min
[2026-02-10 22:48:26 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0567	MSE: 1.014	Speed: 8.4438img/s	Time: 14.21s

     MSE  Epoch Cohort
0  0.873     21  Train
0  1.014     21   Test

[2026-02-10 22:48:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.290,246	LR: 0.000707	Loss: 0.873	Speed: 2.22 img/s	Time: 0hrs:11min
[2026-02-10 22:48:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.669,250	LR: 0.000699	Loss: 0.972	Speed: 426.13 img/s	Time: 0hrs:11min
[2026-02-10 22:48:55 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8365	MSE: 0.805	Speed: 8.3273img/s	Time: 14.41s

     MSE  Epoch Cohort
0  0.931     22  Train
0  0.805     22   Test

[2026-02-10 22:49:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.331,257	LR: 0.000684	Loss: 0.914	Speed: 2.20 img/s	Time: 0hrs:11min
[2026-02-10 22:49:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.710,261	LR: 0.000675	Loss: 0.895	Speed: 424.92 img/s	Time: 0hrs:11min
[2026-02-10 22:49:25 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8516	MSE: 0.803	Speed: 8.3255img/s	Time: 14.41s

     MSE  Epoch Cohort
0  0.894     23  Train
0  0.803     23   Test

[2026-02-10 22:49:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.373,268	LR: 0.000660	Loss: 0.842	Speed: 2.20 img/s	Time: 0hrs:11min
[2026-02-10 22:49:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.751,272	LR: 0.000651	Loss: 0.956	Speed: 411.69 img/s	Time: 0hrs:11min
[2026-02-10 22:49:54 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7772	MSE: 0.745	Speed: 8.4200img/s	Time: 14.25s

     MSE  Epoch Cohort
0  0.892     24  Train
0  0.745     24   Test

[2026-02-10 22:50:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.414,279	LR: 0.000635	Loss: 0.773	Speed: 2.22 img/s	Time: 0hrs:12min
[2026-02-10 22:50:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.793,283	LR: 0.000626	Loss: 0.910	Speed: 418.23 img/s	Time: 0hrs:12min
[2026-02-10 22:50:23 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0742	MSE: 1.002	Speed: 8.3123img/s	Time: 14.44s

     MSE  Epoch Cohort
0  0.883     25  Train
0  1.002     25   Test

[2026-02-10 22:50:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.456,290	LR: 0.000611	Loss: 0.866	Speed: 2.19 img/s	Time: 0hrs:12min
[2026-02-10 22:50:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.834,294	LR: 0.000602	Loss: 1.029	Speed: 412.68 img/s	Time: 0hrs:12min
[2026-02-10 22:50:53 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7727	MSE: 0.744	Speed: 8.1253img/s	Time: 14.77s

     MSE  Epoch Cohort
0  0.886     26  Train
0  0.744     26   Test

[2026-02-10 22:51:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.497,301	LR: 0.000586	Loss: 0.909	Speed: 2.16 img/s	Time: 0hrs:13min
[2026-02-10 22:51:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.876,305	LR: 0.000576	Loss: 0.815	Speed: 404.77 img/s	Time: 0hrs:13min
[2026-02-10 22:51:22 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7977	MSE: 0.753	Speed: 8.1929img/s	Time: 14.65s

     MSE  Epoch Cohort
0  0.860     27  Train
0  0.753     27   Test

[2026-02-10 22:51:36 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.538,312	LR: 0.000560	Loss: 0.799	Speed: 2.17 img/s	Time: 0hrs:13min
[2026-02-10 22:51:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.917,316	LR: 0.000551	Loss: 0.863	Speed: 415.45 img/s	Time: 0hrs:13min
[2026-02-10 22:51:52 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8552	MSE: 0.827	Speed: 7.9888img/s	Time: 15.02s

     MSE  Epoch Cohort
0  0.882     28  Train
0  0.827     28   Test

[2026-02-10 22:52:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.580,323	LR: 0.000535	Loss: 0.687	Speed: 2.15 img/s	Time: 0hrs:14min
[2026-02-10 22:52:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.959,327	LR: 0.000526	Loss: 0.965	Speed: 429.83 img/s	Time: 0hrs:14min
[2026-02-10 22:52:22 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8195	MSE: 0.743	Speed: 8.1862img/s	Time: 14.66s

     MSE  Epoch Cohort
0  0.880     29  Train
0  0.743     29   Test

[2026-02-10 22:52:36 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.621,334	LR: 0.000509	Loss: 0.923	Speed: 2.16 img/s	Time: 0hrs:14min
[2026-02-10 22:52:36 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.000,338	LR: 0.000500	Loss: 0.814	Speed: 422.12 img/s	Time: 0hrs:14min
[2026-02-10 22:52:52 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8443	MSE: 0.793	Speed: 8.1941img/s	Time: 14.64s

     MSE  Epoch Cohort
0  0.874     30  Train
0  0.793     30   Test

[2026-02-10 22:53:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.663,345	LR: 0.000484	Loss: 0.891	Speed: 2.16 img/s	Time: 0hrs:15min
[2026-02-10 22:53:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.041,349	LR: 0.000474	Loss: 0.896	Speed: 390.69 img/s	Time: 0hrs:15min
[2026-02-10 22:53:21 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8167	MSE: 0.748	Speed: 8.3249img/s	Time: 14.41s

     MSE  Epoch Cohort
0  0.858     31  Train
0  0.748     31   Test

[2026-02-10 22:53:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.704,356	LR: 0.000458	Loss: 0.852	Speed: 2.19 img/s	Time: 0hrs:15min
[2026-02-10 22:53:36 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.083,360	LR: 0.000449	Loss: 0.890	Speed: 422.82 img/s	Time: 0hrs:15min
[2026-02-10 22:53:51 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8146	MSE: 0.759	Speed: 8.2912img/s	Time: 14.47s

     MSE  Epoch Cohort
0  0.866     32  Train
0  0.759     32   Test

[2026-02-10 22:54:05 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.746,367	LR: 0.000433	Loss: 0.748	Speed: 2.17 img/s	Time: 0hrs:16min
[2026-02-10 22:54:05 - run_regression.py: 178]	INFO	Phase: train	Epoch: 35.124,371	LR: 0.000424	Loss: 0.997	Speed: 396.68 img/s	Time: 0hrs:16min
[2026-02-10 22:54:21 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7845	MSE: 0.748	Speed: 8.0835img/s	Time: 14.85s

     MSE  Epoch Cohort
0  0.901     33  Train
0  0.748     33   Test

[2026-02-10 22:54:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 35.787,378	LR: 0.000408	Loss: 0.826	Speed: 2.15 img/s	Time: 0hrs:16min
[2026-02-10 22:54:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 36.166,382	LR: 0.000398	Loss: 0.964	Speed: 437.28 img/s	Time: 0hrs:16min
[2026-02-10 22:54:50 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7862	MSE: 0.746	Speed: 8.2184img/s	Time: 14.60s

     MSE  Epoch Cohort
0  0.878     34  Train
0  0.746     34   Test

[2026-02-10 22:55:05 - run_regression.py: 178]	INFO	Phase: train	Epoch: 36.828,389	LR: 0.000383	Loss: 0.913	Speed: 2.17 img/s	Time: 0hrs:17min
[2026-02-10 22:55:05 - run_regression.py: 178]	INFO	Phase: train	Epoch: 37.207,393	LR: 0.000374	Loss: 0.907	Speed: 420.05 img/s	Time: 0hrs:17min
[2026-02-10 22:55:20 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7633	MSE: 0.738	Speed: 8.2535img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.885     35  Train
0  0.738     35   Test

[2026-02-10 22:55:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 37.870,400	LR: 0.000358	Loss: 0.705	Speed: 2.16 img/s	Time: 0hrs:17min
[2026-02-10 22:55:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 38.249,404	LR: 0.000349	Loss: 0.958	Speed: 428.06 img/s	Time: 0hrs:17min
[2026-02-10 22:55:50 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8393	MSE: 0.801	Speed: 8.2133img/s	Time: 14.61s

     MSE  Epoch Cohort
0  0.875     36  Train
0  0.801     36   Test

[2026-02-10 22:56:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 38.911,411	LR: 0.000334	Loss: 0.922	Speed: 2.17 img/s	Time: 0hrs:18min
[2026-02-10 22:56:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 39.290,415	LR: 0.000325	Loss: 0.861	Speed: 419.14 img/s	Time: 0hrs:18min
[2026-02-10 22:56:19 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8045	MSE: 0.771	Speed: 8.2104img/s	Time: 14.62s

     MSE  Epoch Cohort
0  0.841     37  Train
0  0.771     37   Test

[2026-02-10 22:56:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 39.953,422	LR: 0.000310	Loss: 0.935	Speed: 2.18 img/s	Time: 0hrs:18min
[2026-02-10 22:56:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 40.331,426	LR: 0.000301	Loss: 0.787	Speed: 431.80 img/s	Time: 0hrs:18min
[2026-02-10 22:56:49 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8392	MSE: 0.756	Speed: 8.0565img/s	Time: 14.89s

     MSE  Epoch Cohort
0  0.872     38  Train
0  0.756     38   Test

[2026-02-10 22:57:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 40.994,433	LR: 0.000286	Loss: 0.909	Speed: 2.13 img/s	Time: 0hrs:19min
[2026-02-10 22:57:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 41.373,437	LR: 0.000278	Loss: 0.819	Speed: 422.16 img/s	Time: 0hrs:19min
[2026-02-10 22:57:19 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7763	MSE: 0.748	Speed: 8.0288img/s	Time: 14.95s

     MSE  Epoch Cohort
0  0.879     39  Train
0  0.748     39   Test

[2026-02-10 22:57:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 42.036,444	LR: 0.000264	Loss: 0.926	Speed: 2.13 img/s	Time: 0hrs:19min
[2026-02-10 22:57:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 42.414,448	LR: 0.000255	Loss: 0.864	Speed: 426.38 img/s	Time: 0hrs:19min
[2026-02-10 22:57:49 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7802	MSE: 0.747	Speed: 8.3835img/s	Time: 14.31s

     MSE  Epoch Cohort
0  0.886     40  Train
0  0.747     40   Test

[2026-02-10 22:58:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 43.077,455	LR: 0.000241	Loss: 0.886	Speed: 2.19 img/s	Time: 0hrs:20min
[2026-02-10 22:58:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 43.456,459	LR: 0.000233	Loss: 0.855	Speed: 433.33 img/s	Time: 0hrs:20min
[2026-02-10 22:58:19 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8045	MSE: 0.747	Speed: 8.3030img/s	Time: 14.45s

     MSE  Epoch Cohort
0  0.886     41  Train
0  0.747     41   Test

[2026-02-10 22:58:33 - run_regression.py: 178]	INFO	Phase: train	Epoch: 44.118,466	LR: 0.000220	Loss: 0.907	Speed: 2.19 img/s	Time: 0hrs:20min
[2026-02-10 22:58:33 - run_regression.py: 178]	INFO	Phase: train	Epoch: 44.497,470	LR: 0.000212	Loss: 0.839	Speed: 429.66 img/s	Time: 0hrs:20min
[2026-02-10 22:58:48 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7963	MSE: 0.767	Speed: 8.2054img/s	Time: 14.62s

     MSE  Epoch Cohort
0  0.876     42  Train
0  0.767     42   Test

[2026-02-10 22:59:02 - run_regression.py: 178]	INFO	Phase: train	Epoch: 45.160,477	LR: 0.000199	Loss: 0.899	Speed: 2.17 img/s	Time: 0hrs:21min
[2026-02-10 22:59:02 - run_regression.py: 178]	INFO	Phase: train	Epoch: 45.538,481	LR: 0.000192	Loss: 0.889	Speed: 435.74 img/s	Time: 0hrs:21min
[2026-02-10 22:59:18 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7759	MSE: 0.751	Speed: 8.2080img/s	Time: 14.62s

     MSE  Epoch Cohort
0  0.889     43  Train
0  0.751     43   Test

[2026-02-10 22:59:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 46.201,488	LR: 0.000179	Loss: 0.806	Speed: 2.15 img/s	Time: 0hrs:21min
[2026-02-10 22:59:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 46.580,492	LR: 0.000172	Loss: 0.989	Speed: 421.41 img/s	Time: 0hrs:21min
[2026-02-10 22:59:48 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7736	MSE: 0.755	Speed: 8.2007img/s	Time: 14.63s

     MSE  Epoch Cohort
0  0.856     44  Train
0  0.755     44   Test

[2026-02-10 23:00:02 - run_regression.py: 178]	INFO	Phase: train	Epoch: 47.243,499	LR: 0.000160	Loss: 0.799	Speed: 2.17 img/s	Time: 0hrs:22min
[2026-02-10 23:00:02 - run_regression.py: 178]	INFO	Phase: train	Epoch: 47.621,503	LR: 0.000153	Loss: 0.904	Speed: 418.29 img/s	Time: 0hrs:22min
[2026-02-10 23:00:17 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7788	MSE: 0.754	Speed: 8.1901img/s	Time: 14.65s

     MSE  Epoch Cohort
0  0.876     45  Train
0  0.754     45   Test

[2026-02-10 23:00:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 48.284,510	LR: 0.000142	Loss: 0.792	Speed: 2.13 img/s	Time: 0hrs:22min
[2026-02-10 23:00:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 48.663,514	LR: 0.000135	Loss: 0.807	Speed: 394.49 img/s	Time: 0hrs:22min
[2026-02-10 23:00:47 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7844	MSE: 0.753	Speed: 8.2762img/s	Time: 14.50s

     MSE  Epoch Cohort
0  0.873     46  Train
0  0.753     46   Test

[2026-02-10 23:01:02 - run_regression.py: 178]	INFO	Phase: train	Epoch: 49.325,521	LR: 0.000124	Loss: 0.940	Speed: 2.16 img/s	Time: 0hrs:23min
[2026-02-10 23:01:02 - run_regression.py: 178]	INFO	Phase: train	Epoch: 49.704,525	LR: 0.000118	Loss: 0.833	Speed: 408.57 img/s	Time: 0hrs:23min
[2026-02-10 23:01:17 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8237	MSE: 0.758	Speed: 8.1046img/s	Time: 14.81s

     MSE  Epoch Cohort
0  0.896     47  Train
0  0.758     47   Test

[2026-02-10 23:01:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 50.367,532	LR: 0.000108	Loss: 0.908	Speed: 2.16 img/s	Time: 0hrs:23min
[2026-02-10 23:01:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 50.746,536	LR: 0.000102	Loss: 0.863	Speed: 426.97 img/s	Time: 0hrs:23min
[2026-02-10 23:01:47 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7934	MSE: 0.752	Speed: 8.2059img/s	Time: 14.62s

     MSE  Epoch Cohort
0  0.849     48  Train
0  0.752     48   Test

[2026-02-10 23:02:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 51.408,543	LR: 0.000093	Loss: 0.884	Speed: 2.17 img/s	Time: 0hrs:24min
[2026-02-10 23:02:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 51.787,547	LR: 0.000087	Loss: 0.938	Speed: 434.10 img/s	Time: 0hrs:24min
[2026-02-10 23:02:17 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7891	MSE: 0.749	Speed: 8.2192img/s	Time: 14.60s

     MSE  Epoch Cohort
0  0.882     49  Train
0  0.749     49   Test

[2026-02-10 23:02:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 52.450,554	LR: 0.000078	Loss: 0.880	Speed: 2.14 img/s	Time: 0hrs:24min
[2026-02-10 23:02:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 52.828,558	LR: 0.000073	Loss: 0.913	Speed: 433.10 img/s	Time: 0hrs:24min
[2026-02-10 23:02:47 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7894	MSE: 0.753	Speed: 8.2250img/s	Time: 14.59s

     MSE  Epoch Cohort
0  0.853     50  Train
0  0.753     50   Test

[2026-02-10 23:03:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 53.491,565	LR: 0.000065	Loss: 0.776	Speed: 2.16 img/s	Time: 0hrs:25min
[2026-02-10 23:03:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 53.870,569	LR: 0.000061	Loss: 0.903	Speed: 430.24 img/s	Time: 0hrs:25min
[2026-02-10 23:03:17 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7789	MSE: 0.751	Speed: 8.1158img/s	Time: 14.79s

     MSE  Epoch Cohort
0  0.866     51  Train
0  0.751     51   Test

[2026-02-10 23:03:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 54.533,576	LR: 0.000053	Loss: 0.844	Speed: 2.16 img/s	Time: 0hrs:25min
[2026-02-10 23:03:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 54.911,580	LR: 0.000049	Loss: 0.845	Speed: 432.37 img/s	Time: 0hrs:25min
[2026-02-10 23:03:46 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7880	MSE: 0.752	Speed: 8.1942img/s	Time: 14.64s

     MSE  Epoch Cohort
0  0.859     52  Train
0  0.752     52   Test

[2026-02-10 23:04:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 55.574,587	LR: 0.000042	Loss: 0.907	Speed: 2.17 img/s	Time: 0hrs:26min
[2026-02-10 23:04:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 55.953,591	LR: 0.000039	Loss: 0.803	Speed: 409.95 img/s	Time: 0hrs:26min
[2026-02-10 23:04:16 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8193	MSE: 0.754	Speed: 8.2382img/s	Time: 14.57s

     MSE  Epoch Cohort
0  0.866     53  Train
0  0.754     53   Test

[2026-02-10 23:04:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 56.615,598	LR: 0.000032	Loss: 0.860	Speed: 2.19 img/s	Time: 0hrs:26min
[2026-02-10 23:04:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 56.994,602	LR: 0.000029	Loss: 0.969	Speed: 434.20 img/s	Time: 0hrs:26min
[2026-02-10 23:04:45 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8033	MSE: 0.757	Speed: 8.2026img/s	Time: 14.63s

     MSE  Epoch Cohort
0  0.869     54  Train
0  0.757     54   Test

[2026-02-10 23:05:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 57.657,609	LR: 0.000024	Loss: 0.809	Speed: 2.16 img/s	Time: 0hrs:27min
[2026-02-10 23:05:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 58.036,613	LR: 0.000021	Loss: 0.921	Speed: 428.49 img/s	Time: 0hrs:27min
[2026-02-10 23:05:15 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8005	MSE: 0.758	Speed: 8.0781img/s	Time: 14.86s

     MSE  Epoch Cohort
0  0.866     55  Train
0  0.758     55   Test

[2026-02-10 23:05:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 58.698,620	LR: 0.000017	Loss: 0.884	Speed: 2.16 img/s	Time: 0hrs:27min
[2026-02-10 23:05:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 59.077,624	LR: 0.000015	Loss: 0.876	Speed: 386.91 img/s	Time: 0hrs:27min
[2026-02-10 23:05:45 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8025	MSE: 0.755	Speed: 8.2201img/s	Time: 14.60s

     MSE  Epoch Cohort
0  0.856     56  Train
0  0.755     56   Test

[2026-02-10 23:05:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 59.740,631	LR: 0.000011	Loss: 0.834	Speed: 2.17 img/s	Time: 0hrs:28min
[2026-02-10 23:05:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 60.118,635	LR: 0.000009	Loss: 0.899	Speed: 394.54 img/s	Time: 0hrs:28min
[2026-02-10 23:06:15 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7957	MSE: 0.756	Speed: 8.1404img/s	Time: 14.74s

     MSE  Epoch Cohort
0  0.852     57  Train
0  0.756     57   Test

[2026-02-10 23:06:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 60.781,642	LR: 0.000006	Loss: 0.838	Speed: 2.15 img/s	Time: 0hrs:28min
[2026-02-10 23:06:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 61.160,646	LR: 0.000005	Loss: 0.872	Speed: 397.30 img/s	Time: 0hrs:28min
[2026-02-10 23:06:45 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7961	MSE: 0.758	Speed: 8.0173img/s	Time: 14.97s

     MSE  Epoch Cohort
0  0.876     58  Train
0  0.758     58   Test

[2026-02-10 23:06:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 61.822,653	LR: 0.000003	Loss: 0.869	Speed: 2.12 img/s	Time: 0hrs:29min
[2026-02-10 23:06:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 62.201,657	LR: 0.000002	Loss: 0.947	Speed: 425.74 img/s	Time: 0hrs:29min
[2026-02-10 23:07:15 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7998	MSE: 0.756	Speed: 8.2015img/s	Time: 14.63s

     MSE  Epoch Cohort
0  0.869     59  Train
0  0.756     59   Test

[2026-02-10 23:07:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 62.864,664	LR: 0.000001	Loss: 0.827	Speed: 2.17 img/s	Time: 0hrs:29min
[2026-02-10 23:07:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 63.243,668	LR: 0.000000	Loss: 0.789	Speed: 428.77 img/s	Time: 0hrs:29min
[2026-02-10 23:07:44 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8071	MSE: 0.760	Speed: 8.1059img/s	Time: 14.80s

     MSE  Epoch Cohort
0  0.867     60  Train
0  0.760     60   Test

[2026-02-10 23:07:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 63.905,675	LR: 0.000000	Loss: 0.779	Speed: 2.14 img/s	Time: 0hrs:30min
[2026-02-10 23:07:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 64.284,679	LR: 0.000000	Loss: 0.862	Speed: 410.12 img/s	Time: 0hrs:30min
[2026-02-10 23:08:15 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8027	MSE: 0.757	Speed: 8.0257img/s	Time: 14.95s

     MSE  Epoch Cohort
0  0.852     61  Train
0  0.757     61   Test

[2026-02-10 23:08:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 64.947,686	LR: 0.000001	Loss: 0.883	Speed: 2.13 img/s	Time: 0hrs:30min
[2026-02-10 23:08:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 65.325,690	LR: 0.000001	Loss: 0.933	Speed: 408.16 img/s	Time: 0hrs:30min
[2026-02-10 23:08:45 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8104	MSE: 0.755	Speed: 8.0309img/s	Time: 14.94s

     MSE  Epoch Cohort
0  0.878     62  Train
0  0.755     62   Test

[2026-02-10 23:08:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 65.988,697	LR: 0.000002	Loss: 1.020	Speed: 2.17 img/s	Time: 0hrs:31min
[2026-02-10 23:08:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 66.367,701	LR: 0.000003	Loss: 0.703	Speed: 438.32 img/s	Time: 0hrs:31min
[2026-02-10 23:09:14 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7849	MSE: 0.757	Speed: 8.2222img/s	Time: 14.59s

     MSE  Epoch Cohort
0  0.865     63  Train
0  0.757     63   Test

[2026-02-10 23:09:14 - run_regression.py: 369]	INFO	Done for training. Best metric is 1.3937509913903752@1 epoch. Average for last 5 iters is 0.7569031105103751
[2026-02-10 23:09:14 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-0.txt
[2026-02-10 23:09:14 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-0.txt
[2026-02-10 23:09:14 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-0.txt
[2026-02-10 23:09:14 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-0.txt
[2026-02-10 23:09:14 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-02-10 23:09:14 - about_log.py: 149]	INFO		Number of samples: 169
[2026-02-10 23:09:14 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-10 23:09:14 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task2\split_info\labels.txt
[2026-02-10 23:09:14 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-02-10 23:09:14 - about_log.py: 149]	INFO		Number of samples: 120
[2026-02-10 23:09:14 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-10 23:09:14 - run_regression.py: 305]	INFO	Creating model resnet18...
[2026-02-10 23:09:14 - resnet.py: 271]	INFO	Pretrained model loaded!
[2026-02-10 23:09:14 - run_regression.py: 352]	INFO	Start training...
[2026-02-10 23:09:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.379,4	LR: 0.001000	Loss: 1.727	Speed: 4.54 img/s	Time: 0hrs:0min
[2026-02-10 23:09:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.757,8	LR: 0.001000	Loss: 1.021	Speed: 1086.14 img/s	Time: 0hrs:0min
[2026-02-10 23:09:44 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0717	MSE: 1.097	Speed: 8.0812img/s	Time: 14.85s

     MSE  Epoch Cohort
0  1.336      0  Train
0  1.097      0   Test

[2026-02-10 23:09:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.420,15	LR: 0.000999	Loss: 1.072	Speed: 2.17 img/s	Time: 0hrs:0min
[2026-02-10 23:09:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.799,19	LR: 0.000998	Loss: 0.980	Speed: 1079.99 img/s	Time: 0hrs:0min
[2026-02-10 23:10:13 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9917	MSE: 1.001	Speed: 8.3498img/s	Time: 14.37s

     MSE  Epoch Cohort
0  1.058      1  Train
0  1.001      1   Test

[2026-02-10 23:10:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.462,26	LR: 0.000996	Loss: 1.008	Speed: 2.21 img/s	Time: 0hrs:1min
[2026-02-10 23:10:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.840,30	LR: 0.000995	Loss: 0.948	Speed: 1069.40 img/s	Time: 0hrs:1min
[2026-02-10 23:10:42 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8860	MSE: 0.910	Speed: 8.4105img/s	Time: 14.27s

     MSE  Epoch Cohort
0  1.074      2  Train
0  0.910      2   Test

[2026-02-10 23:10:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.503,37	LR: 0.000993	Loss: 0.959	Speed: 2.24 img/s	Time: 0hrs:1min
[2026-02-10 23:10:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.882,41	LR: 0.000991	Loss: 1.017	Speed: 1090.45 img/s	Time: 0hrs:1min
[2026-02-10 23:11:10 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8582	MSE: 0.870	Speed: 8.4331img/s	Time: 14.23s

     MSE  Epoch Cohort
0  0.989      3  Train
0  0.870      3   Test

[2026-02-10 23:11:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.544,48	LR: 0.000988	Loss: 1.082	Speed: 2.24 img/s	Time: 0hrs:2min
[2026-02-10 23:11:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.923,52	LR: 0.000985	Loss: 0.952	Speed: 1072.01 img/s	Time: 0hrs:2min
[2026-02-10 23:11:39 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8478	MSE: 0.845	Speed: 8.3536img/s	Time: 14.37s

     MSE  Epoch Cohort
0  1.041      4  Train
0  0.845      4   Test

[2026-02-10 23:11:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.586,59	LR: 0.000981	Loss: 1.127	Speed: 2.23 img/s	Time: 0hrs:2min
[2026-02-10 23:11:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.964,63	LR: 0.000979	Loss: 0.871	Speed: 1084.83 img/s	Time: 0hrs:2min
[2026-02-10 23:12:08 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8242	MSE: 0.822	Speed: 8.4354img/s	Time: 14.23s

     MSE  Epoch Cohort
0  1.004      5  Train
0  0.822      5   Test

[2026-02-10 23:12:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.627,70	LR: 0.000974	Loss: 1.190	Speed: 2.24 img/s	Time: 0hrs:3min
[2026-02-10 23:12:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.006,74	LR: 0.000971	Loss: 0.832	Speed: 1097.24 img/s	Time: 0hrs:3min
[2026-02-10 23:12:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8389	MSE: 0.824	Speed: 8.4282img/s	Time: 14.24s

     MSE  Epoch Cohort
0  1.040      6  Train
0  0.824      6   Test

[2026-02-10 23:12:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.669,81	LR: 0.000965	Loss: 0.989	Speed: 2.24 img/s	Time: 0hrs:3min
[2026-02-10 23:12:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.047,85	LR: 0.000961	Loss: 0.969	Speed: 1047.52 img/s	Time: 0hrs:3min
[2026-02-10 23:13:05 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8642	MSE: 0.865	Speed: 8.4287img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.990      7  Train
0  0.865      7   Test

[2026-02-10 23:13:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.710,92	LR: 0.000955	Loss: 0.984	Speed: 2.23 img/s	Time: 0hrs:4min
[2026-02-10 23:13:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.089,96	LR: 0.000951	Loss: 0.801	Speed: 1102.39 img/s	Time: 0hrs:4min
[2026-02-10 23:13:34 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8863	MSE: 0.811	Speed: 8.4262img/s	Time: 14.24s

     MSE  Epoch Cohort
0  1.043      8  Train
0  0.811      8   Test

[2026-02-10 23:13:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.751,103	LR: 0.000944	Loss: 0.889	Speed: 2.24 img/s	Time: 0hrs:4min
[2026-02-10 23:13:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.130,107	LR: 0.000939	Loss: 0.996	Speed: 1069.22 img/s	Time: 0hrs:4min
[2026-02-10 23:14:02 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8463	MSE: 0.804	Speed: 8.3200img/s	Time: 14.42s

     MSE  Epoch Cohort
0  1.017      9  Train
0  0.804      9   Test

[2026-02-10 23:14:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.793,114	LR: 0.000931	Loss: 0.901	Speed: 2.23 img/s	Time: 0hrs:5min
[2026-02-10 23:14:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.172,118	LR: 0.000927	Loss: 0.934	Speed: 1083.45 img/s	Time: 0hrs:5min
[2026-02-10 23:14:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8100	MSE: 0.800	Speed: 8.3193img/s	Time: 14.42s

     MSE  Epoch Cohort
0  0.873     10  Train
0  0.800     10   Test

[2026-02-10 23:14:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.834,125	LR: 0.000918	Loss: 0.957	Speed: 2.23 img/s	Time: 0hrs:5min
[2026-02-10 23:14:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.213,129	LR: 0.000913	Loss: 0.933	Speed: 1043.18 img/s	Time: 0hrs:5min
[2026-02-10 23:15:00 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0000	MSE: 0.930	Speed: 8.4336img/s	Time: 14.23s

    MSE  Epoch Cohort
0  0.94     11  Train
0  0.93     11   Test

[2026-02-10 23:15:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.876,136	LR: 0.000903	Loss: 0.979	Speed: 2.23 img/s	Time: 0hrs:5min
[2026-02-10 23:15:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.254,140	LR: 0.000898	Loss: 1.062	Speed: 1073.65 img/s	Time: 0hrs:5min
[2026-02-10 23:15:29 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8774	MSE: 0.785	Speed: 8.3026img/s	Time: 14.45s

     MSE  Epoch Cohort
0  1.045     12  Train
0  0.785     12   Test

[2026-02-10 23:15:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.917,147	LR: 0.000888	Loss: 0.818	Speed: 2.18 img/s	Time: 0hrs:6min
[2026-02-10 23:15:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.296,151	LR: 0.000882	Loss: 0.956	Speed: 1092.32 img/s	Time: 0hrs:6min
[2026-02-10 23:15:59 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7856	MSE: 0.789	Speed: 7.9877img/s	Time: 15.02s

     MSE  Epoch Cohort
0  0.937     13  Train
0  0.789     13   Test

[2026-02-10 23:16:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.959,158	LR: 0.000871	Loss: 1.042	Speed: 2.15 img/s	Time: 0hrs:6min
[2026-02-10 23:16:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 15.337,162	LR: 0.000865	Loss: 0.869	Speed: 1064.07 img/s	Time: 0hrs:6min
[2026-02-10 23:16:28 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9877	MSE: 0.969	Speed: 8.3160img/s	Time: 14.43s

     MSE  Epoch Cohort
0  0.910     14  Train
0  0.969     14   Test

[2026-02-10 23:16:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.000,169	LR: 0.000854	Loss: 0.914	Speed: 2.21 img/s	Time: 0hrs:7min
[2026-02-10 23:16:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.379,173	LR: 0.000847	Loss: 0.877	Speed: 1090.30 img/s	Time: 0hrs:7min
[2026-02-10 23:16:57 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0214	MSE: 0.962	Speed: 8.4236img/s	Time: 14.25s

     MSE  Epoch Cohort
0  0.916     15  Train
0  0.962     15   Test

[2026-02-10 23:17:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.041,180	LR: 0.000835	Loss: 1.031	Speed: 2.24 img/s	Time: 0hrs:7min
[2026-02-10 23:17:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.420,184	LR: 0.000828	Loss: 0.866	Speed: 1098.52 img/s	Time: 0hrs:7min
[2026-02-10 23:17:25 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9759	MSE: 0.908	Speed: 8.4229img/s	Time: 14.25s

     MSE  Epoch Cohort
0  0.946     16  Train
0  0.908     16   Test

[2026-02-10 23:17:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.083,191	LR: 0.000816	Loss: 0.987	Speed: 2.24 img/s	Time: 0hrs:8min
[2026-02-10 23:17:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.462,195	LR: 0.000808	Loss: 0.901	Speed: 1062.51 img/s	Time: 0hrs:8min
[2026-02-10 23:17:54 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8243	MSE: 0.800	Speed: 8.4554img/s	Time: 14.19s

     MSE  Epoch Cohort
0  0.963     17  Train
0  0.800     17   Test

[2026-02-10 23:18:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.124,202	LR: 0.000795	Loss: 0.983	Speed: 2.24 img/s	Time: 0hrs:8min
[2026-02-10 23:18:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.503,206	LR: 0.000788	Loss: 0.791	Speed: 1090.47 img/s	Time: 0hrs:8min
[2026-02-10 23:18:23 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8595	MSE: 0.781	Speed: 8.3291img/s	Time: 14.41s

     MSE  Epoch Cohort
0  0.956     18  Train
0  0.781     18   Test

[2026-02-10 23:18:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.166,213	LR: 0.000774	Loss: 1.062	Speed: 2.23 img/s	Time: 0hrs:9min
[2026-02-10 23:18:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.544,217	LR: 0.000767	Loss: 0.841	Speed: 1043.72 img/s	Time: 0hrs:9min
[2026-02-10 23:18:52 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8178	MSE: 0.781	Speed: 8.3176img/s	Time: 14.43s

     MSE  Epoch Cohort
0  0.933     19  Train
0  0.781     19   Test

[2026-02-10 23:19:05 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.207,224	LR: 0.000753	Loss: 0.893	Speed: 2.23 img/s	Time: 0hrs:9min
[2026-02-10 23:19:05 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.586,228	LR: 0.000745	Loss: 0.811	Speed: 1089.44 img/s	Time: 0hrs:9min
[2026-02-10 23:19:20 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9001	MSE: 0.846	Speed: 8.4337img/s	Time: 14.23s

     MSE  Epoch Cohort
0  0.913     20  Train
0  0.846     20   Test

[2026-02-10 23:19:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.249,235	LR: 0.000730	Loss: 0.891	Speed: 2.23 img/s	Time: 0hrs:10min
[2026-02-10 23:19:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.627,239	LR: 0.000722	Loss: 0.944	Speed: 1070.23 img/s	Time: 0hrs:10min
[2026-02-10 23:19:49 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9148	MSE: 0.815	Speed: 8.4121img/s	Time: 14.27s

     MSE  Epoch Cohort
0  0.945     21  Train
0  0.815     21   Test

[2026-02-10 23:20:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.290,246	LR: 0.000707	Loss: 0.850	Speed: 2.24 img/s	Time: 0hrs:10min
[2026-02-10 23:20:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.669,250	LR: 0.000699	Loss: 0.924	Speed: 1040.63 img/s	Time: 0hrs:10min
[2026-02-10 23:20:18 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9735	MSE: 0.878	Speed: 8.4396img/s	Time: 14.22s

     MSE  Epoch Cohort
0  0.886     22  Train
0  0.878     22   Test

[2026-02-10 23:20:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.331,257	LR: 0.000684	Loss: 0.962	Speed: 2.23 img/s	Time: 0hrs:11min
[2026-02-10 23:20:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.710,261	LR: 0.000675	Loss: 0.865	Speed: 1095.77 img/s	Time: 0hrs:11min
[2026-02-10 23:20:46 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8104	MSE: 0.797	Speed: 8.4394img/s	Time: 14.22s

     MSE  Epoch Cohort
0  0.951     23  Train
0  0.797     23   Test

[2026-02-10 23:21:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.373,268	LR: 0.000660	Loss: 0.861	Speed: 2.24 img/s	Time: 0hrs:11min
[2026-02-10 23:21:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.751,272	LR: 0.000651	Loss: 1.006	Speed: 1016.14 img/s	Time: 0hrs:11min
[2026-02-10 23:21:15 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7843	MSE: 0.793	Speed: 8.3338img/s	Time: 14.40s

     MSE  Epoch Cohort
0  0.955     24  Train
0  0.793     24   Test

[2026-02-10 23:21:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.414,279	LR: 0.000635	Loss: 1.004	Speed: 2.21 img/s	Time: 0hrs:12min
[2026-02-10 23:21:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.793,283	LR: 0.000626	Loss: 0.906	Speed: 1085.50 img/s	Time: 0hrs:12min
[2026-02-10 23:21:44 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9173	MSE: 0.865	Speed: 8.3080img/s	Time: 14.44s

     MSE  Epoch Cohort
0  0.938     25  Train
0  0.865     25   Test

[2026-02-10 23:21:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.456,290	LR: 0.000611	Loss: 1.007	Speed: 2.21 img/s	Time: 0hrs:12min
[2026-02-10 23:21:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.834,294	LR: 0.000602	Loss: 1.020	Speed: 1081.80 img/s	Time: 0hrs:12min
[2026-02-10 23:22:13 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8042	MSE: 0.803	Speed: 8.4319img/s	Time: 14.23s

     MSE  Epoch Cohort
0  1.010     26  Train
0  0.803     26   Test

[2026-02-10 23:22:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.497,301	LR: 0.000586	Loss: 0.926	Speed: 2.24 img/s	Time: 0hrs:13min
[2026-02-10 23:22:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.876,305	LR: 0.000576	Loss: 0.852	Speed: 1098.90 img/s	Time: 0hrs:13min
[2026-02-10 23:22:42 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8818	MSE: 0.851	Speed: 8.4374img/s	Time: 14.22s

     MSE  Epoch Cohort
0  0.912     27  Train
0  0.851     27   Test

[2026-02-10 23:22:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.538,312	LR: 0.000560	Loss: 0.890	Speed: 2.24 img/s	Time: 0hrs:13min
[2026-02-10 23:22:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.917,316	LR: 0.000551	Loss: 0.933	Speed: 1037.97 img/s	Time: 0hrs:13min
[2026-02-10 23:23:10 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8607	MSE: 0.805	Speed: 8.3203img/s	Time: 14.42s

     MSE  Epoch Cohort
0  0.879     28  Train
0  0.805     28   Test

[2026-02-10 23:23:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.580,323	LR: 0.000535	Loss: 0.871	Speed: 2.23 img/s	Time: 0hrs:14min
[2026-02-10 23:23:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.959,327	LR: 0.000526	Loss: 1.021	Speed: 1110.85 img/s	Time: 0hrs:14min
[2026-02-10 23:23:39 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8318	MSE: 0.792	Speed: 8.3137img/s	Time: 14.43s

     MSE  Epoch Cohort
0  0.884     29  Train
0  0.792     29   Test

[2026-02-10 23:23:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.621,334	LR: 0.000509	Loss: 0.999	Speed: 2.23 img/s	Time: 0hrs:14min
[2026-02-10 23:23:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.000,338	LR: 0.000500	Loss: 0.911	Speed: 1085.09 img/s	Time: 0hrs:14min
[2026-02-10 23:24:08 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7867	MSE: 0.786	Speed: 8.4211img/s	Time: 14.25s

     MSE  Epoch Cohort
0  0.930     30  Train
0  0.786     30   Test

[2026-02-10 23:24:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.663,345	LR: 0.000484	Loss: 0.872	Speed: 2.23 img/s	Time: 0hrs:15min
[2026-02-10 23:24:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.041,349	LR: 0.000474	Loss: 1.028	Speed: 1060.74 img/s	Time: 0hrs:15min
[2026-02-10 23:24:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8091	MSE: 0.795	Speed: 8.4245img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.936     31  Train
0  0.795     31   Test

[2026-02-10 23:24:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.704,356	LR: 0.000458	Loss: 0.997	Speed: 2.24 img/s	Time: 0hrs:15min
[2026-02-10 23:24:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.083,360	LR: 0.000449	Loss: 0.844	Speed: 1003.43 img/s	Time: 0hrs:15min
[2026-02-10 23:25:05 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8165	MSE: 0.786	Speed: 8.4271img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.906     32  Train
0  0.786     32   Test

[2026-02-10 23:25:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.746,367	LR: 0.000433	Loss: 0.820	Speed: 2.24 img/s	Time: 0hrs:16min
[2026-02-10 23:25:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 35.124,371	LR: 0.000424	Loss: 0.968	Speed: 1094.09 img/s	Time: 0hrs:16min
[2026-02-10 23:25:34 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7984	MSE: 0.789	Speed: 8.4271img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.910     33  Train
0  0.789     33   Test

[2026-02-10 23:25:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 35.787,378	LR: 0.000408	Loss: 0.817	Speed: 2.24 img/s	Time: 0hrs:16min
[2026-02-10 23:25:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 36.166,382	LR: 0.000398	Loss: 1.111	Speed: 1005.51 img/s	Time: 0hrs:16min
[2026-02-10 23:26:02 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8345	MSE: 0.804	Speed: 8.4247img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.937     34  Train
0  0.804     34   Test

[2026-02-10 23:26:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 36.828,389	LR: 0.000383	Loss: 0.749	Speed: 2.23 img/s	Time: 0hrs:17min
[2026-02-10 23:26:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 37.207,393	LR: 0.000374	Loss: 0.895	Speed: 1070.85 img/s	Time: 0hrs:17min
[2026-02-10 23:26:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8606	MSE: 0.839	Speed: 8.3313img/s	Time: 14.40s

     MSE  Epoch Cohort
0  0.881     35  Train
0  0.839     35   Test

[2026-02-10 23:26:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 37.870,400	LR: 0.000358	Loss: 1.021	Speed: 2.23 img/s	Time: 0hrs:17min
[2026-02-10 23:26:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 38.249,404	LR: 0.000349	Loss: 0.787	Speed: 1021.47 img/s	Time: 0hrs:17min
[2026-02-10 23:27:00 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8320	MSE: 0.788	Speed: 8.4561img/s	Time: 14.19s

     MSE  Epoch Cohort
0  0.933     36  Train
0  0.788     36   Test

[2026-02-10 23:27:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 38.911,411	LR: 0.000334	Loss: 1.053	Speed: 2.24 img/s	Time: 0hrs:17min
[2026-02-10 23:27:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 39.290,415	LR: 0.000325	Loss: 0.886	Speed: 1014.61 img/s	Time: 0hrs:17min
[2026-02-10 23:27:28 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7983	MSE: 0.782	Speed: 8.4345img/s	Time: 14.23s

     MSE  Epoch Cohort
0  0.933     37  Train
0  0.782     37   Test

[2026-02-10 23:27:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 39.953,422	LR: 0.000310	Loss: 1.035	Speed: 2.23 img/s	Time: 0hrs:18min
[2026-02-10 23:27:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 40.331,426	LR: 0.000301	Loss: 0.779	Speed: 1023.22 img/s	Time: 0hrs:18min
[2026-02-10 23:27:57 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8046	MSE: 0.782	Speed: 8.4325img/s	Time: 14.23s

     MSE  Epoch Cohort
0  0.936     38  Train
0  0.782     38   Test

[2026-02-10 23:28:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 40.994,433	LR: 0.000286	Loss: 0.940	Speed: 2.23 img/s	Time: 0hrs:18min
[2026-02-10 23:28:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 41.373,437	LR: 0.000278	Loss: 0.866	Speed: 1085.04 img/s	Time: 0hrs:18min
[2026-02-10 23:28:26 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8098	MSE: 0.787	Speed: 8.4072img/s	Time: 14.27s

     MSE  Epoch Cohort
0  0.927     39  Train
0  0.787     39   Test

[2026-02-10 23:28:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 42.036,444	LR: 0.000264	Loss: 0.860	Speed: 2.23 img/s	Time: 0hrs:19min
[2026-02-10 23:28:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 42.414,448	LR: 0.000255	Loss: 1.013	Speed: 1084.32 img/s	Time: 0hrs:19min
[2026-02-10 23:28:55 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8195	MSE: 0.784	Speed: 8.4283img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.871     40  Train
0  0.784     40   Test

[2026-02-10 23:29:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 43.077,455	LR: 0.000241	Loss: 0.901	Speed: 2.23 img/s	Time: 0hrs:19min
[2026-02-10 23:29:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 43.456,459	LR: 0.000233	Loss: 0.958	Speed: 1068.32 img/s	Time: 0hrs:19min
[2026-02-10 23:29:24 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7968	MSE: 0.786	Speed: 8.4271img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.959     41  Train
0  0.786     41   Test

[2026-02-10 23:29:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 44.118,466	LR: 0.000220	Loss: 0.725	Speed: 2.24 img/s	Time: 0hrs:20min
[2026-02-10 23:29:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 44.497,470	LR: 0.000212	Loss: 1.032	Speed: 1050.19 img/s	Time: 0hrs:20min
[2026-02-10 23:29:52 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8355	MSE: 0.785	Speed: 8.4267img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.895     42  Train
0  0.785     42   Test

[2026-02-10 23:30:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 45.160,477	LR: 0.000199	Loss: 0.915	Speed: 2.24 img/s	Time: 0hrs:20min
[2026-02-10 23:30:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 45.538,481	LR: 0.000192	Loss: 0.832	Speed: 1110.32 img/s	Time: 0hrs:20min
[2026-02-10 23:30:21 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8124	MSE: 0.800	Speed: 8.4157img/s	Time: 14.26s

     MSE  Epoch Cohort
0  0.921     43  Train
0  0.800     43   Test

[2026-02-10 23:30:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 46.201,488	LR: 0.000179	Loss: 0.806	Speed: 2.23 img/s	Time: 0hrs:21min
[2026-02-10 23:30:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 46.580,492	LR: 0.000172	Loss: 1.023	Speed: 1084.31 img/s	Time: 0hrs:21min
[2026-02-10 23:30:50 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8089	MSE: 0.781	Speed: 8.4101img/s	Time: 14.27s

     MSE  Epoch Cohort
0  0.903     44  Train
0  0.781     44   Test

[2026-02-10 23:31:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 47.243,499	LR: 0.000160	Loss: 0.966	Speed: 2.24 img/s	Time: 0hrs:21min
[2026-02-10 23:31:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 47.621,503	LR: 0.000153	Loss: 0.888	Speed: 1083.96 img/s	Time: 0hrs:21min
[2026-02-10 23:31:18 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8143	MSE: 0.778	Speed: 8.4277img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.892     45  Train
0  0.778     45   Test

[2026-02-10 23:31:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 48.284,510	LR: 0.000142	Loss: 1.024	Speed: 2.24 img/s	Time: 0hrs:22min
[2026-02-10 23:31:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 48.663,514	LR: 0.000135	Loss: 0.872	Speed: 1025.58 img/s	Time: 0hrs:22min
[2026-02-10 23:31:47 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8118	MSE: 0.772	Speed: 8.4255img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.953     46  Train
0  0.772     46   Test

[2026-02-10 23:32:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 49.325,521	LR: 0.000124	Loss: 0.908	Speed: 2.23 img/s	Time: 0hrs:22min
[2026-02-10 23:32:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 49.704,525	LR: 0.000118	Loss: 0.917	Speed: 1063.50 img/s	Time: 0hrs:22min
[2026-02-10 23:32:16 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8042	MSE: 0.779	Speed: 8.4404img/s	Time: 14.22s

     MSE  Epoch Cohort
0  0.905     47  Train
0  0.779     47   Test

[2026-02-10 23:32:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 50.367,532	LR: 0.000108	Loss: 0.884	Speed: 2.24 img/s	Time: 0hrs:23min
[2026-02-10 23:32:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 50.746,536	LR: 0.000102	Loss: 0.814	Speed: 1078.60 img/s	Time: 0hrs:23min
[2026-02-10 23:32:44 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8422	MSE: 0.790	Speed: 8.4351img/s	Time: 14.23s

     MSE  Epoch Cohort
0  0.868     48  Train
0  0.790     48   Test

[2026-02-10 23:32:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 51.408,543	LR: 0.000093	Loss: 0.697	Speed: 2.23 img/s	Time: 0hrs:23min
[2026-02-10 23:32:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 51.787,547	LR: 0.000087	Loss: 1.107	Speed: 937.08 img/s	Time: 0hrs:23min
[2026-02-10 23:33:13 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7887	MSE: 0.779	Speed: 8.3438img/s	Time: 14.38s

     MSE  Epoch Cohort
0  0.944     49  Train
0  0.779     49   Test

[2026-02-10 23:33:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 52.450,554	LR: 0.000078	Loss: 0.963	Speed: 2.21 img/s	Time: 0hrs:24min
[2026-02-10 23:33:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 52.828,558	LR: 0.000073	Loss: 0.868	Speed: 1099.50 img/s	Time: 0hrs:24min
[2026-02-10 23:33:42 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8306	MSE: 0.777	Speed: 8.1993img/s	Time: 14.64s

     MSE  Epoch Cohort
0  0.940     50  Train
0  0.777     50   Test

[2026-02-10 23:33:57 - run_regression.py: 178]	INFO	Phase: train	Epoch: 53.491,565	LR: 0.000065	Loss: 0.813	Speed: 2.17 img/s	Time: 0hrs:24min
[2026-02-10 23:33:57 - run_regression.py: 178]	INFO	Phase: train	Epoch: 53.870,569	LR: 0.000061	Loss: 0.959	Speed: 971.96 img/s	Time: 0hrs:24min
[2026-02-10 23:34:12 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8430	MSE: 0.781	Speed: 8.2175img/s	Time: 14.60s

     MSE  Epoch Cohort
0  0.936     51  Train
0  0.781     51   Test

[2026-02-10 23:34:26 - run_regression.py: 178]	INFO	Phase: train	Epoch: 54.533,576	LR: 0.000053	Loss: 0.914	Speed: 2.20 img/s	Time: 0hrs:25min
[2026-02-10 23:34:26 - run_regression.py: 178]	INFO	Phase: train	Epoch: 54.911,580	LR: 0.000049	Loss: 0.917	Speed: 1090.21 img/s	Time: 0hrs:25min
[2026-02-10 23:34:41 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8308	MSE: 0.786	Speed: 8.4195img/s	Time: 14.25s

     MSE  Epoch Cohort
0  0.880     52  Train
0  0.786     52   Test

[2026-02-10 23:34:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 55.574,587	LR: 0.000042	Loss: 0.947	Speed: 2.23 img/s	Time: 0hrs:25min
[2026-02-10 23:34:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 55.953,591	LR: 0.000039	Loss: 0.877	Speed: 1005.59 img/s	Time: 0hrs:25min
[2026-02-10 23:35:09 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8178	MSE: 0.787	Speed: 8.4230img/s	Time: 14.25s

     MSE  Epoch Cohort
0  0.925     53  Train
0  0.787     53   Test

[2026-02-10 23:35:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 56.615,598	LR: 0.000032	Loss: 0.894	Speed: 2.23 img/s	Time: 0hrs:26min
[2026-02-10 23:35:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 56.994,602	LR: 0.000029	Loss: 0.795	Speed: 1092.45 img/s	Time: 0hrs:26min
[2026-02-10 23:35:38 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8301	MSE: 0.781	Speed: 8.3098img/s	Time: 14.44s

     MSE  Epoch Cohort
0  0.873     54  Train
0  0.781     54   Test

[2026-02-10 23:35:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 57.657,609	LR: 0.000024	Loss: 0.728	Speed: 2.23 img/s	Time: 0hrs:26min
[2026-02-10 23:35:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 58.036,613	LR: 0.000021	Loss: 0.973	Speed: 1099.63 img/s	Time: 0hrs:26min
[2026-02-10 23:36:07 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8064	MSE: 0.781	Speed: 8.3174img/s	Time: 14.43s

     MSE  Epoch Cohort
0  0.907     55  Train
0  0.781     55   Test

[2026-02-10 23:36:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 58.698,620	LR: 0.000017	Loss: 0.967	Speed: 2.21 img/s	Time: 0hrs:27min
[2026-02-10 23:36:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 59.077,624	LR: 0.000015	Loss: 0.843	Speed: 1040.24 img/s	Time: 0hrs:27min
[2026-02-10 23:36:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8487	MSE: 0.781	Speed: 8.4328img/s	Time: 14.23s

     MSE  Epoch Cohort
0  0.920     56  Train
0  0.781     56   Test

[2026-02-10 23:36:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 59.740,631	LR: 0.000011	Loss: 0.813	Speed: 2.23 img/s	Time: 0hrs:27min
[2026-02-10 23:36:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 60.118,635	LR: 0.000009	Loss: 0.951	Speed: 1073.16 img/s	Time: 0hrs:27min
[2026-02-10 23:37:05 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8276	MSE: 0.783	Speed: 8.4332img/s	Time: 14.23s

     MSE  Epoch Cohort
0  0.936     57  Train
0  0.783     57   Test

[2026-02-10 23:37:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 60.781,642	LR: 0.000006	Loss: 0.808	Speed: 2.23 img/s	Time: 0hrs:28min
[2026-02-10 23:37:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 61.160,646	LR: 0.000005	Loss: 1.076	Speed: 1074.64 img/s	Time: 0hrs:28min
[2026-02-10 23:37:34 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8011	MSE: 0.786	Speed: 8.4245img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.860     58  Train
0  0.786     58   Test

[2026-02-10 23:37:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 61.822,653	LR: 0.000003	Loss: 0.916	Speed: 2.23 img/s	Time: 0hrs:28min
[2026-02-10 23:37:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 62.201,657	LR: 0.000002	Loss: 0.912	Speed: 1107.32 img/s	Time: 0hrs:28min
[2026-02-10 23:38:02 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8493	MSE: 0.786	Speed: 8.4274img/s	Time: 14.24s

     MSE  Epoch Cohort
0  0.909     59  Train
0  0.786     59   Test

[2026-02-10 23:38:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 62.864,664	LR: 0.000001	Loss: 0.903	Speed: 2.23 img/s	Time: 0hrs:29min
[2026-02-10 23:38:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 63.243,668	LR: 0.000000	Loss: 0.918	Speed: 1088.85 img/s	Time: 0hrs:29min
[2026-02-10 23:38:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7989	MSE: 0.783	Speed: 8.4179img/s	Time: 14.26s

     MSE  Epoch Cohort
0  0.874     60  Train
0  0.783     60   Test

[2026-02-10 23:38:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 63.905,675	LR: 0.000000	Loss: 0.939	Speed: 2.23 img/s	Time: 0hrs:29min
[2026-02-10 23:38:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 64.284,679	LR: 0.000000	Loss: 0.880	Speed: 1005.75 img/s	Time: 0hrs:29min
[2026-02-10 23:39:00 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8101	MSE: 0.796	Speed: 8.3391img/s	Time: 14.39s

     MSE  Epoch Cohort
0  0.931     61  Train
0  0.796     61   Test

[2026-02-10 23:39:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 64.947,686	LR: 0.000001	Loss: 1.017	Speed: 2.21 img/s	Time: 0hrs:29min
[2026-02-10 23:39:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 65.325,690	LR: 0.000001	Loss: 0.817	Speed: 1037.96 img/s	Time: 0hrs:30min
[2026-02-10 23:39:29 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8382	MSE: 0.798	Speed: 8.3308img/s	Time: 14.40s

     MSE  Epoch Cohort
0  0.924     62  Train
0  0.798     62   Test

[2026-02-10 23:39:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 65.988,697	LR: 0.000002	Loss: 0.797	Speed: 2.20 img/s	Time: 0hrs:30min
[2026-02-10 23:39:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 66.367,701	LR: 0.000003	Loss: 0.974	Speed: 1054.02 img/s	Time: 0hrs:30min
[2026-02-10 23:39:59 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8590	MSE: 0.788	Speed: 8.2140img/s	Time: 14.61s

     MSE  Epoch Cohort
0  0.931     63  Train
0  0.788     63   Test

[2026-02-10 23:39:59 - run_regression.py: 369]	INFO	Done for training. Best metric is 1.0965294812570414@1 epoch. Average for last 5 iters is 0.790074846860375
[2026-02-10 23:39:59 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-0.txt
[2026-02-10 23:39:59 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-0.txt
[2026-02-10 23:39:59 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-0.txt
[2026-02-10 23:39:59 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-0.txt
[2026-02-10 23:39:59 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-02-10 23:39:59 - about_log.py: 149]	INFO		Number of samples: 169
[2026-02-10 23:39:59 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-10 23:39:59 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task2\split_info\labels.txt
[2026-02-10 23:39:59 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-02-10 23:39:59 - about_log.py: 149]	INFO		Number of samples: 120
[2026-02-10 23:39:59 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-10 23:39:59 - run_regression.py: 305]	INFO	Creating model resnet101...
[2026-02-10 23:39:59 - resnet.py: 271]	INFO	Pretrained model loaded!
[2026-02-10 23:39:59 - run_regression.py: 352]	INFO	Start training...
[2026-02-10 23:40:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.379,4	LR: 0.001000	Loss: 1.297	Speed: 4.41 img/s	Time: 0hrs:0min
[2026-02-10 23:40:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.757,8	LR: 0.001000	Loss: 0.800	Speed: 278.57 img/s	Time: 0hrs:0min
[2026-02-10 23:40:29 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1488	MSE: 1.126	Speed: 8.1031img/s	Time: 14.81s

     MSE  Epoch Cohort
0  1.036      0  Train
0  1.126      0   Test

[2026-02-10 23:40:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.420,15	LR: 0.000999	Loss: 0.923	Speed: 2.09 img/s	Time: 0hrs:0min
[2026-02-10 23:40:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.799,19	LR: 0.000998	Loss: 0.977	Speed: 272.64 img/s	Time: 0hrs:0min
[2026-02-10 23:41:00 - run_regression.py: 233]	INFO	Phase: valid	loss:1.3849	MSE: 1.369	Speed: 8.1328img/s	Time: 14.76s

     MSE  Epoch Cohort
0  0.961      1  Train
0  1.369      1   Test

[2026-02-10 23:41:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.462,26	LR: 0.000996	Loss: 1.021	Speed: 2.14 img/s	Time: 0hrs:1min
[2026-02-10 23:41:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.840,30	LR: 0.000995	Loss: 1.063	Speed: 278.82 img/s	Time: 0hrs:1min
[2026-02-10 23:41:30 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9761	MSE: 0.894	Speed: 8.1020img/s	Time: 14.81s

     MSE  Epoch Cohort
0  0.990      2  Train
0  0.894      2   Test

[2026-02-10 23:41:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.503,37	LR: 0.000993	Loss: 0.929	Speed: 2.14 img/s	Time: 0hrs:1min
[2026-02-10 23:41:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.882,41	LR: 0.000991	Loss: 0.976	Speed: 272.93 img/s	Time: 0hrs:1min
[2026-02-10 23:42:01 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8077	MSE: 0.784	Speed: 8.1372img/s	Time: 14.75s

     MSE  Epoch Cohort
0  0.956      3  Train
0  0.784      3   Test

[2026-02-10 23:42:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.544,48	LR: 0.000988	Loss: 0.885	Speed: 2.12 img/s	Time: 0hrs:2min
[2026-02-10 23:42:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.923,52	LR: 0.000985	Loss: 0.956	Speed: 283.03 img/s	Time: 0hrs:2min
[2026-02-10 23:42:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8638	MSE: 0.796	Speed: 8.1174img/s	Time: 14.78s

     MSE  Epoch Cohort
0  0.914      4  Train
0  0.796      4   Test

[2026-02-10 23:42:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.586,59	LR: 0.000981	Loss: 0.981	Speed: 2.14 img/s	Time: 0hrs:2min
[2026-02-10 23:42:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.964,63	LR: 0.000979	Loss: 0.836	Speed: 278.29 img/s	Time: 0hrs:2min
[2026-02-10 23:43:01 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8369	MSE: 0.761	Speed: 8.0755img/s	Time: 14.86s

     MSE  Epoch Cohort
0  0.936      5  Train
0  0.761      5   Test

[2026-02-10 23:43:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.627,70	LR: 0.000974	Loss: 0.897	Speed: 2.12 img/s	Time: 0hrs:3min
[2026-02-10 23:43:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.006,74	LR: 0.000971	Loss: 0.879	Speed: 267.67 img/s	Time: 0hrs:3min
[2026-02-10 23:43:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9012	MSE: 0.798	Speed: 8.1436img/s	Time: 14.74s

     MSE  Epoch Cohort
0  0.917      6  Train
0  0.798      6   Test

[2026-02-10 23:43:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.669,81	LR: 0.000965	Loss: 0.834	Speed: 2.14 img/s	Time: 0hrs:3min
[2026-02-10 23:43:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.047,85	LR: 0.000961	Loss: 0.869	Speed: 281.95 img/s	Time: 0hrs:3min
[2026-02-10 23:44:02 - run_regression.py: 233]	INFO	Phase: valid	loss:1.0683	MSE: 1.002	Speed: 8.1371img/s	Time: 14.75s

     MSE  Epoch Cohort
0  0.871      7  Train
0  1.002      7   Test

[2026-02-10 23:44:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.710,92	LR: 0.000955	Loss: 1.016	Speed: 2.12 img/s	Time: 0hrs:4min
[2026-02-10 23:44:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.089,96	LR: 0.000951	Loss: 0.957	Speed: 267.53 img/s	Time: 0hrs:4min
[2026-02-10 23:44:32 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8781	MSE: 0.777	Speed: 8.0191img/s	Time: 14.96s

     MSE  Epoch Cohort
0  1.024      8  Train
0  0.777      8   Test

[2026-02-10 23:44:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.751,103	LR: 0.000944	Loss: 0.847	Speed: 2.12 img/s	Time: 0hrs:4min
[2026-02-10 23:44:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.130,107	LR: 0.000939	Loss: 0.946	Speed: 263.50 img/s	Time: 0hrs:4min
[2026-02-10 23:45:03 - run_regression.py: 233]	INFO	Phase: valid	loss:1.1075	MSE: 1.040	Speed: 8.0759img/s	Time: 14.86s

     MSE  Epoch Cohort
0  0.941      9  Train
0  1.040      9   Test

[2026-02-10 23:45:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.793,114	LR: 0.000931	Loss: 0.729	Speed: 2.12 img/s	Time: 0hrs:5min
[2026-02-10 23:45:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.172,118	LR: 0.000927	Loss: 0.923	Speed: 281.03 img/s	Time: 0hrs:5min
[2026-02-10 23:45:33 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9248	MSE: 0.876	Speed: 8.1392img/s	Time: 14.74s

     MSE  Epoch Cohort
0  0.899     10  Train
0  0.876     10   Test

[2026-02-10 23:45:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.834,125	LR: 0.000918	Loss: 0.791	Speed: 2.14 img/s	Time: 0hrs:5min
[2026-02-10 23:45:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.213,129	LR: 0.000913	Loss: 1.038	Speed: 272.97 img/s	Time: 0hrs:5min
[2026-02-10 23:46:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8646	MSE: 0.791	Speed: 8.1215img/s	Time: 14.78s

     MSE  Epoch Cohort
0  0.897     11  Train
0  0.791     11   Test

[2026-02-10 23:46:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.876,136	LR: 0.000903	Loss: 1.055	Speed: 2.15 img/s	Time: 0hrs:6min
[2026-02-10 23:46:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.254,140	LR: 0.000898	Loss: 0.756	Speed: 276.96 img/s	Time: 0hrs:6min
[2026-02-10 23:46:33 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8127	MSE: 0.792	Speed: 8.2327img/s	Time: 14.58s

     MSE  Epoch Cohort
0  0.876     12  Train
0  0.792     12   Test

[2026-02-10 23:46:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.917,147	LR: 0.000888	Loss: 0.919	Speed: 2.16 img/s	Time: 0hrs:6min
[2026-02-10 23:46:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.296,151	LR: 0.000882	Loss: 0.804	Speed: 281.55 img/s	Time: 0hrs:6min
[2026-02-10 23:47:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9014	MSE: 0.901	Speed: 8.2393img/s	Time: 14.56s

     MSE  Epoch Cohort
0  0.909     13  Train
0  0.901     13   Test

[2026-02-10 23:47:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.959,158	LR: 0.000871	Loss: 0.939	Speed: 2.17 img/s	Time: 0hrs:7min
[2026-02-10 23:47:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 15.337,162	LR: 0.000865	Loss: 0.863	Speed: 274.60 img/s	Time: 0hrs:7min
[2026-02-10 23:47:32 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8102	MSE: 0.768	Speed: 8.2484img/s	Time: 14.55s

     MSE  Epoch Cohort
0  0.913     14  Train
0  0.768     14   Test

[2026-02-10 23:47:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.000,169	LR: 0.000854	Loss: 0.832	Speed: 2.15 img/s	Time: 0hrs:7min
[2026-02-10 23:47:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.379,173	LR: 0.000847	Loss: 0.893	Speed: 279.14 img/s	Time: 0hrs:7min
[2026-02-10 23:48:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9751	MSE: 0.906	Speed: 8.1275img/s	Time: 14.76s

     MSE  Epoch Cohort
0  0.939     15  Train
0  0.906     15   Test

[2026-02-10 23:48:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.041,180	LR: 0.000835	Loss: 0.878	Speed: 2.15 img/s	Time: 0hrs:8min
[2026-02-10 23:48:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.420,184	LR: 0.000828	Loss: 0.967	Speed: 281.23 img/s	Time: 0hrs:8min
[2026-02-10 23:48:32 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8053	MSE: 0.774	Speed: 8.2216img/s	Time: 14.60s

     MSE  Epoch Cohort
0  0.990     16  Train
0  0.774     16   Test

[2026-02-10 23:48:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.083,191	LR: 0.000816	Loss: 0.838	Speed: 2.16 img/s	Time: 0hrs:8min
[2026-02-10 23:48:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.462,195	LR: 0.000808	Loss: 1.055	Speed: 282.86 img/s	Time: 0hrs:8min
[2026-02-10 23:49:02 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8459	MSE: 0.792	Speed: 8.1181img/s	Time: 14.78s

     MSE  Epoch Cohort
0  0.935     17  Train
0  0.792     17   Test

[2026-02-10 23:49:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.124,202	LR: 0.000795	Loss: 0.793	Speed: 2.15 img/s	Time: 0hrs:9min
[2026-02-10 23:49:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.503,206	LR: 0.000788	Loss: 0.947	Speed: 275.81 img/s	Time: 0hrs:9min
[2026-02-10 23:49:32 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9581	MSE: 0.943	Speed: 8.1490img/s	Time: 14.73s

     MSE  Epoch Cohort
0  0.930     18  Train
0  0.943     18   Test

[2026-02-10 23:49:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.166,213	LR: 0.000774	Loss: 0.898	Speed: 2.14 img/s	Time: 0hrs:9min
[2026-02-10 23:49:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.544,217	LR: 0.000767	Loss: 0.875	Speed: 282.35 img/s	Time: 0hrs:9min
[2026-02-10 23:50:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8284	MSE: 0.809	Speed: 7.8535img/s	Time: 15.28s

     MSE  Epoch Cohort
0  0.862     19  Train
0  0.809     19   Test

[2026-02-10 23:50:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.207,224	LR: 0.000753	Loss: 0.879	Speed: 2.09 img/s	Time: 0hrs:10min
[2026-02-10 23:50:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.586,228	LR: 0.000745	Loss: 0.876	Speed: 265.20 img/s	Time: 0hrs:10min
[2026-02-10 23:50:37 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8078	MSE: 0.786	Speed: 6.6391img/s	Time: 18.07s

     MSE  Epoch Cohort
0  0.898     20  Train
0  0.786     20   Test

[2026-02-10 23:50:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.249,235	LR: 0.000730	Loss: 0.860	Speed: 1.87 img/s	Time: 0hrs:10min
[2026-02-10 23:50:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.627,239	LR: 0.000722	Loss: 0.926	Speed: 212.09 img/s	Time: 0hrs:10min
[2026-02-10 23:51:08 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8637	MSE: 0.805	Speed: 7.9825img/s	Time: 15.03s

     MSE  Epoch Cohort
0  0.923     21  Train
0  0.805     21   Test

[2026-02-10 23:51:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.290,246	LR: 0.000707	Loss: 0.792	Speed: 2.11 img/s	Time: 0hrs:11min
[2026-02-10 23:51:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.669,250	LR: 0.000699	Loss: 0.890	Speed: 277.11 img/s	Time: 0hrs:11min
[2026-02-10 23:51:38 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8034	MSE: 0.764	Speed: 8.1286img/s	Time: 14.76s

     MSE  Epoch Cohort
0  0.880     22  Train
0  0.764     22   Test

[2026-02-10 23:51:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.331,257	LR: 0.000684	Loss: 0.829	Speed: 2.17 img/s	Time: 0hrs:11min
[2026-02-10 23:51:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.710,261	LR: 0.000675	Loss: 0.934	Speed: 285.78 img/s	Time: 0hrs:11min
[2026-02-10 23:52:08 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8195	MSE: 0.789	Speed: 8.3664img/s	Time: 14.34s

     MSE  Epoch Cohort
0  0.873     23  Train
0  0.789     23   Test

[2026-02-10 23:52:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.373,268	LR: 0.000660	Loss: 0.987	Speed: 2.16 img/s	Time: 0hrs:12min
[2026-02-10 23:52:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.751,272	LR: 0.000651	Loss: 0.885	Speed: 276.29 img/s	Time: 0hrs:12min
[2026-02-10 23:52:38 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8157	MSE: 0.781	Speed: 7.9886img/s	Time: 15.02s

     MSE  Epoch Cohort
0  0.907     24  Train
0  0.781     24   Test

[2026-02-10 23:52:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.414,279	LR: 0.000635	Loss: 0.947	Speed: 2.08 img/s	Time: 0hrs:12min
[2026-02-10 23:52:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.793,283	LR: 0.000626	Loss: 0.880	Speed: 271.86 img/s	Time: 0hrs:12min
[2026-02-10 23:53:09 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8253	MSE: 0.775	Speed: 8.0805img/s	Time: 14.85s

     MSE  Epoch Cohort
0  0.900     25  Train
0  0.775     25   Test

[2026-02-10 23:53:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.456,290	LR: 0.000611	Loss: 0.812	Speed: 2.11 img/s	Time: 0hrs:13min
[2026-02-10 23:53:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.834,294	LR: 0.000602	Loss: 0.928	Speed: 285.95 img/s	Time: 0hrs:13min
[2026-02-10 23:53:40 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7820	MSE: 0.774	Speed: 7.8839img/s	Time: 15.22s

     MSE  Epoch Cohort
0  0.905     26  Train
0  0.774     26   Test

[2026-02-10 23:53:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.497,301	LR: 0.000586	Loss: 0.949	Speed: 2.09 img/s	Time: 0hrs:13min
[2026-02-10 23:53:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.876,305	LR: 0.000576	Loss: 0.940	Speed: 271.15 img/s	Time: 0hrs:13min
[2026-02-10 23:54:10 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8117	MSE: 0.777	Speed: 8.1481img/s	Time: 14.73s

     MSE  Epoch Cohort
0  0.887     27  Train
0  0.777     27   Test

[2026-02-10 23:54:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.538,312	LR: 0.000560	Loss: 0.838	Speed: 2.14 img/s	Time: 0hrs:14min
[2026-02-10 23:54:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.917,316	LR: 0.000551	Loss: 0.963	Speed: 269.36 img/s	Time: 0hrs:14min
[2026-02-10 23:54:40 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9899	MSE: 0.950	Speed: 8.1292img/s	Time: 14.76s

     MSE  Epoch Cohort
0  0.923     28  Train
0  0.950     28   Test

[2026-02-10 23:54:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.580,323	LR: 0.000535	Loss: 0.838	Speed: 2.15 img/s	Time: 0hrs:14min
[2026-02-10 23:54:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.959,327	LR: 0.000526	Loss: 0.746	Speed: 277.68 img/s	Time: 0hrs:14min
[2026-02-10 23:55:10 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8667	MSE: 0.831	Speed: 8.1505img/s	Time: 14.72s

     MSE  Epoch Cohort
0  0.925     29  Train
0  0.831     29   Test

[2026-02-10 23:55:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.621,334	LR: 0.000509	Loss: 0.903	Speed: 2.17 img/s	Time: 0hrs:15min
[2026-02-10 23:55:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.000,338	LR: 0.000500	Loss: 0.971	Speed: 277.51 img/s	Time: 0hrs:15min
[2026-02-10 23:55:40 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8257	MSE: 0.770	Speed: 8.3584img/s	Time: 14.36s

     MSE  Epoch Cohort
0  0.897     30  Train
0  0.770     30   Test

[2026-02-10 23:55:54 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.663,345	LR: 0.000484	Loss: 0.789	Speed: 2.20 img/s	Time: 0hrs:15min
[2026-02-10 23:55:54 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.041,349	LR: 0.000474	Loss: 1.027	Speed: 278.03 img/s	Time: 0hrs:15min
[2026-02-10 23:56:09 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8224	MSE: 0.755	Speed: 8.3190img/s	Time: 14.42s

     MSE  Epoch Cohort
0  0.897     31  Train
0  0.755     31   Test

[2026-02-10 23:56:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.704,356	LR: 0.000458	Loss: 0.856	Speed: 2.18 img/s	Time: 0hrs:16min
[2026-02-10 23:56:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.083,360	LR: 0.000449	Loss: 0.950	Speed: 284.63 img/s	Time: 0hrs:16min
[2026-02-10 23:56:39 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8074	MSE: 0.764	Speed: 8.3518img/s	Time: 14.37s

     MSE  Epoch Cohort
0  0.920     32  Train
0  0.764     32   Test

[2026-02-10 23:56:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.746,367	LR: 0.000433	Loss: 0.844	Speed: 2.19 img/s	Time: 0hrs:16min
[2026-02-10 23:56:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 35.124,371	LR: 0.000424	Loss: 0.968	Speed: 279.41 img/s	Time: 0hrs:16min
[2026-02-10 23:57:08 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8208	MSE: 0.758	Speed: 8.3466img/s	Time: 14.38s

     MSE  Epoch Cohort
0  0.894     33  Train
0  0.758     33   Test

[2026-02-10 23:57:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 35.787,378	LR: 0.000408	Loss: 0.754	Speed: 2.19 img/s	Time: 0hrs:17min
[2026-02-10 23:57:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 36.166,382	LR: 0.000398	Loss: 0.884	Speed: 281.44 img/s	Time: 0hrs:17min
[2026-02-10 23:57:38 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8050	MSE: 0.776	Speed: 8.3341img/s	Time: 14.40s

     MSE  Epoch Cohort
0  0.881     34  Train
0  0.776     34   Test

[2026-02-10 23:57:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 36.828,389	LR: 0.000383	Loss: 0.899	Speed: 2.19 img/s	Time: 0hrs:17min
[2026-02-10 23:57:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 37.207,393	LR: 0.000374	Loss: 0.850	Speed: 281.65 img/s	Time: 0hrs:17min
[2026-02-10 23:58:07 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7823	MSE: 0.768	Speed: 8.3545img/s	Time: 14.36s

     MSE  Epoch Cohort
0  0.879     35  Train
0  0.768     35   Test

[2026-02-10 23:58:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 37.870,400	LR: 0.000358	Loss: 0.851	Speed: 2.19 img/s	Time: 0hrs:18min
[2026-02-10 23:58:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 38.249,404	LR: 0.000349	Loss: 0.921	Speed: 284.29 img/s	Time: 0hrs:18min
[2026-02-10 23:58:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7824	MSE: 0.755	Speed: 8.3305img/s	Time: 14.40s

     MSE  Epoch Cohort
0  0.920     36  Train
0  0.755     36   Test

[2026-02-10 23:58:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 38.911,411	LR: 0.000334	Loss: 0.800	Speed: 2.19 img/s	Time: 0hrs:18min
[2026-02-10 23:58:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 39.290,415	LR: 0.000325	Loss: 0.914	Speed: 280.92 img/s	Time: 0hrs:18min
[2026-02-10 23:59:06 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8249	MSE: 0.753	Speed: 8.3266img/s	Time: 14.41s

     MSE  Epoch Cohort
0  0.885     37  Train
0  0.753     37   Test

[2026-02-10 23:59:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 39.953,422	LR: 0.000310	Loss: 0.961	Speed: 2.18 img/s	Time: 0hrs:19min
[2026-02-10 23:59:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 40.331,426	LR: 0.000301	Loss: 0.971	Speed: 283.57 img/s	Time: 0hrs:19min
[2026-02-10 23:59:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8201	MSE: 0.772	Speed: 8.2291img/s	Time: 14.58s

     MSE  Epoch Cohort
0  0.862     38  Train
0  0.772     38   Test

[2026-02-10 23:59:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 40.994,433	LR: 0.000286	Loss: 0.892	Speed: 2.17 img/s	Time: 0hrs:19min
[2026-02-10 23:59:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 41.373,437	LR: 0.000278	Loss: 0.920	Speed: 275.29 img/s	Time: 0hrs:19min
[2026-02-11 00:00:05 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7612	MSE: 0.757	Speed: 8.3413img/s	Time: 14.39s

     MSE  Epoch Cohort
0  0.863     39  Train
0  0.757     39   Test

[2026-02-11 00:00:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 42.036,444	LR: 0.000264	Loss: 0.827	Speed: 2.19 img/s	Time: 0hrs:20min
[2026-02-11 00:00:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 42.414,448	LR: 0.000255	Loss: 0.867	Speed: 278.15 img/s	Time: 0hrs:20min
[2026-02-11 00:00:35 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8019	MSE: 0.759	Speed: 8.3491img/s	Time: 14.37s

     MSE  Epoch Cohort
0  0.865     40  Train
0  0.759     40   Test

[2026-02-11 00:00:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 43.077,455	LR: 0.000241	Loss: 0.983	Speed: 2.19 img/s	Time: 0hrs:20min
[2026-02-11 00:00:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 43.456,459	LR: 0.000233	Loss: 0.776	Speed: 275.39 img/s	Time: 0hrs:20min
[2026-02-11 00:01:04 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7942	MSE: 0.768	Speed: 8.3521img/s	Time: 14.37s

     MSE  Epoch Cohort
0  0.887     41  Train
0  0.768     41   Test

[2026-02-11 00:01:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 44.118,466	LR: 0.000220	Loss: 0.947	Speed: 2.20 img/s	Time: 0hrs:21min
[2026-02-11 00:01:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 44.497,470	LR: 0.000212	Loss: 0.858	Speed: 282.87 img/s	Time: 0hrs:21min
[2026-02-11 00:01:34 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8216	MSE: 0.760	Speed: 8.2191img/s	Time: 14.60s

     MSE  Epoch Cohort
0  0.884     42  Train
0  0.760     42   Test

[2026-02-11 00:01:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 45.160,477	LR: 0.000199	Loss: 0.884	Speed: 2.18 img/s	Time: 0hrs:21min
[2026-02-11 00:01:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 45.538,481	LR: 0.000192	Loss: 0.911	Speed: 283.64 img/s	Time: 0hrs:21min
[2026-02-11 00:02:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7764	MSE: 0.757	Speed: 8.3373img/s	Time: 14.39s

     MSE  Epoch Cohort
0  0.908     43  Train
0  0.757     43   Test

[2026-02-11 00:02:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 46.201,488	LR: 0.000179	Loss: 0.912	Speed: 2.18 img/s	Time: 0hrs:22min
[2026-02-11 00:02:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 46.580,492	LR: 0.000172	Loss: 0.911	Speed: 280.97 img/s	Time: 0hrs:22min
[2026-02-11 00:02:32 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8460	MSE: 0.760	Speed: 8.3393img/s	Time: 14.39s

     MSE  Epoch Cohort
0  0.895     44  Train
0  0.760     44   Test

[2026-02-11 00:02:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 47.243,499	LR: 0.000160	Loss: 0.832	Speed: 2.19 img/s	Time: 0hrs:22min
[2026-02-11 00:02:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 47.621,503	LR: 0.000153	Loss: 0.923	Speed: 275.72 img/s	Time: 0hrs:22min
[2026-02-11 00:03:02 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8005	MSE: 0.769	Speed: 8.2269img/s	Time: 14.59s

     MSE  Epoch Cohort
0  0.861     45  Train
0  0.769     45   Test

[2026-02-11 00:03:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 48.284,510	LR: 0.000142	Loss: 0.738	Speed: 2.18 img/s	Time: 0hrs:23min
[2026-02-11 00:03:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 48.663,514	LR: 0.000135	Loss: 0.954	Speed: 270.99 img/s	Time: 0hrs:23min
[2026-02-11 00:03:32 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7883	MSE: 0.763	Speed: 8.2505img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.881     46  Train
0  0.763     46   Test

[2026-02-11 00:03:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 49.325,521	LR: 0.000124	Loss: 0.927	Speed: 2.18 img/s	Time: 0hrs:23min
[2026-02-11 00:03:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 49.704,525	LR: 0.000118	Loss: 0.776	Speed: 273.32 img/s	Time: 0hrs:23min
[2026-02-11 00:04:01 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7869	MSE: 0.760	Speed: 8.2556img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.878     47  Train
0  0.760     47   Test

[2026-02-11 00:04:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 50.367,532	LR: 0.000108	Loss: 0.789	Speed: 2.17 img/s	Time: 0hrs:24min
[2026-02-11 00:04:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 50.746,536	LR: 0.000102	Loss: 0.887	Speed: 280.06 img/s	Time: 0hrs:24min
[2026-02-11 00:04:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7818	MSE: 0.754	Speed: 8.2161img/s	Time: 14.61s

     MSE  Epoch Cohort
0  0.881     48  Train
0  0.754     48   Test

[2026-02-11 00:04:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 51.408,543	LR: 0.000093	Loss: 0.893	Speed: 2.16 img/s	Time: 0hrs:24min
[2026-02-11 00:04:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 51.787,547	LR: 0.000087	Loss: 0.943	Speed: 274.29 img/s	Time: 0hrs:24min
[2026-02-11 00:05:01 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7798	MSE: 0.755	Speed: 8.2596img/s	Time: 14.53s

     MSE  Epoch Cohort
0  0.872     49  Train
0  0.755     49   Test

[2026-02-11 00:05:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 52.450,554	LR: 0.000078	Loss: 0.861	Speed: 2.15 img/s	Time: 0hrs:25min
[2026-02-11 00:05:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 52.828,558	LR: 0.000073	Loss: 0.751	Speed: 282.06 img/s	Time: 0hrs:25min
[2026-02-11 00:05:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7981	MSE: 0.752	Speed: 8.2078img/s	Time: 14.62s

     MSE  Epoch Cohort
0  0.897     50  Train
0  0.752     50   Test

[2026-02-11 00:05:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 53.491,565	LR: 0.000065	Loss: 0.862	Speed: 2.17 img/s	Time: 0hrs:25min
[2026-02-11 00:05:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 53.870,569	LR: 0.000061	Loss: 0.963	Speed: 281.99 img/s	Time: 0hrs:25min
[2026-02-11 00:06:01 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8036	MSE: 0.757	Speed: 8.2240img/s	Time: 14.59s

     MSE  Epoch Cohort
0  0.867     51  Train
0  0.757     51   Test

[2026-02-11 00:06:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 54.533,576	LR: 0.000053	Loss: 0.855	Speed: 2.15 img/s	Time: 0hrs:26min
[2026-02-11 00:06:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 54.911,580	LR: 0.000049	Loss: 0.769	Speed: 275.83 img/s	Time: 0hrs:26min
[2026-02-11 00:06:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7918	MSE: 0.758	Speed: 8.2300img/s	Time: 14.58s

     MSE  Epoch Cohort
0  0.881     52  Train
0  0.758     52   Test

[2026-02-11 00:06:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 55.574,587	LR: 0.000042	Loss: 0.885	Speed: 2.16 img/s	Time: 0hrs:26min
[2026-02-11 00:06:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 55.953,591	LR: 0.000039	Loss: 0.933	Speed: 282.89 img/s	Time: 0hrs:26min
[2026-02-11 00:07:00 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7980	MSE: 0.760	Speed: 8.3589img/s	Time: 14.36s

     MSE  Epoch Cohort
0  0.862     53  Train
0  0.760     53   Test

[2026-02-11 00:07:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 56.615,598	LR: 0.000032	Loss: 0.736	Speed: 2.19 img/s	Time: 0hrs:27min
[2026-02-11 00:07:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 56.994,602	LR: 0.000029	Loss: 0.880	Speed: 280.16 img/s	Time: 0hrs:27min
[2026-02-11 00:07:30 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7897	MSE: 0.754	Speed: 8.2310img/s	Time: 14.58s

     MSE  Epoch Cohort
0  0.870     54  Train
0  0.754     54   Test

[2026-02-11 00:07:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 57.657,609	LR: 0.000024	Loss: 1.013	Speed: 2.18 img/s	Time: 0hrs:27min
[2026-02-11 00:07:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 58.036,613	LR: 0.000021	Loss: 0.800	Speed: 280.17 img/s	Time: 0hrs:27min
[2026-02-11 00:07:59 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8024	MSE: 0.754	Speed: 8.2236img/s	Time: 14.59s

     MSE  Epoch Cohort
0  0.874     55  Train
0  0.754     55   Test

[2026-02-11 00:08:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 58.698,620	LR: 0.000017	Loss: 0.930	Speed: 2.17 img/s	Time: 0hrs:28min
[2026-02-11 00:08:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 59.077,624	LR: 0.000015	Loss: 0.902	Speed: 278.96 img/s	Time: 0hrs:28min
[2026-02-11 00:08:29 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8128	MSE: 0.754	Speed: 8.3339img/s	Time: 14.40s

     MSE  Epoch Cohort
0  0.874     56  Train
0  0.754     56   Test

[2026-02-11 00:08:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 59.740,631	LR: 0.000011	Loss: 0.756	Speed: 2.19 img/s	Time: 0hrs:28min
[2026-02-11 00:08:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 60.118,635	LR: 0.000009	Loss: 0.849	Speed: 276.38 img/s	Time: 0hrs:28min
[2026-02-11 00:08:58 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8227	MSE: 0.764	Speed: 8.3674img/s	Time: 14.34s

     MSE  Epoch Cohort
0  0.881     57  Train
0  0.764     57   Test

[2026-02-11 00:09:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 60.781,642	LR: 0.000006	Loss: 0.847	Speed: 2.19 img/s	Time: 0hrs:29min
[2026-02-11 00:09:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 61.160,646	LR: 0.000005	Loss: 0.868	Speed: 283.19 img/s	Time: 0hrs:29min
[2026-02-11 00:09:28 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7968	MSE: 0.760	Speed: 8.3387img/s	Time: 14.39s

     MSE  Epoch Cohort
0  0.871     58  Train
0  0.760     58   Test

[2026-02-11 00:09:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 61.822,653	LR: 0.000003	Loss: 0.887	Speed: 2.19 img/s	Time: 0hrs:29min
[2026-02-11 00:09:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 62.201,657	LR: 0.000002	Loss: 0.823	Speed: 276.03 img/s	Time: 0hrs:29min
[2026-02-11 00:09:57 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7760	MSE: 0.754	Speed: 8.3562img/s	Time: 14.36s

     MSE  Epoch Cohort
0  0.869     59  Train
0  0.754     59   Test

[2026-02-11 00:10:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 62.864,664	LR: 0.000001	Loss: 0.960	Speed: 2.19 img/s	Time: 0hrs:30min
[2026-02-11 00:10:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 63.243,668	LR: 0.000000	Loss: 0.756	Speed: 280.78 img/s	Time: 0hrs:30min
[2026-02-11 00:10:27 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7857	MSE: 0.752	Speed: 8.3493img/s	Time: 14.37s

     MSE  Epoch Cohort
0  0.875     60  Train
0  0.752     60   Test

[2026-02-11 00:10:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 63.905,675	LR: 0.000000	Loss: 0.881	Speed: 2.20 img/s	Time: 0hrs:30min
[2026-02-11 00:10:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 64.284,679	LR: 0.000000	Loss: 0.872	Speed: 281.61 img/s	Time: 0hrs:30min
[2026-02-11 00:10:56 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8125	MSE: 0.754	Speed: 8.3412img/s	Time: 14.39s

     MSE  Epoch Cohort
0  0.860     61  Train
0  0.754     61   Test

[2026-02-11 00:11:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 64.947,686	LR: 0.000001	Loss: 0.776	Speed: 2.19 img/s	Time: 0hrs:31min
[2026-02-11 00:11:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 65.325,690	LR: 0.000001	Loss: 0.866	Speed: 276.88 img/s	Time: 0hrs:31min
[2026-02-11 00:11:25 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8227	MSE: 0.759	Speed: 8.3390img/s	Time: 14.39s

     MSE  Epoch Cohort
0  0.858     62  Train
0  0.759     62   Test

[2026-02-11 00:11:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 65.988,697	LR: 0.000002	Loss: 0.868	Speed: 2.18 img/s	Time: 0hrs:31min
[2026-02-11 00:11:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 66.367,701	LR: 0.000003	Loss: 0.915	Speed: 282.34 img/s	Time: 0hrs:31min
[2026-02-11 00:11:55 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7785	MSE: 0.758	Speed: 8.2222img/s	Time: 14.59s

     MSE  Epoch Cohort
0  0.862     63  Train
0  0.758     63   Test

[2026-02-11 00:11:55 - run_regression.py: 369]	INFO	Done for training. Best metric is 1.3689145096070416@2 epoch. Average for last 5 iters is 0.7554734975870416
[2026-02-11 00:11:55 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-0.txt
[2026-02-11 00:11:55 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-0.txt
[2026-02-11 00:11:55 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-0.txt
[2026-02-11 00:11:55 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-0.txt
[2026-02-11 00:11:55 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-02-11 00:11:55 - about_log.py: 149]	INFO		Number of samples: 169
[2026-02-11 00:11:55 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-11 00:11:55 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task2\split_info\labels.txt
[2026-02-11 00:11:55 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-02-11 00:11:55 - about_log.py: 149]	INFO		Number of samples: 120
[2026-02-11 00:11:55 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-11 00:11:55 - run_regression.py: 305]	INFO	Creating model densenet121...
[2026-02-11 00:11:55 - densenet.py: 260]	INFO	loading pretrained model
[2026-02-11 00:11:55 - run_regression.py: 352]	INFO	Start training...
[2026-02-11 00:12:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.379,4	LR: 0.001000	Loss: 1.038	Speed: 4.54 img/s	Time: 0hrs:0min
[2026-02-11 00:12:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.757,8	LR: 0.001000	Loss: 0.913	Speed: 302.45 img/s	Time: 0hrs:0min
[2026-02-11 00:12:25 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8469	MSE: 0.910	Speed: 8.3547img/s	Time: 14.36s

     MSE  Epoch Cohort
0  1.056      0  Train
0  0.910      0   Test

[2026-02-11 00:12:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.420,15	LR: 0.000999	Loss: 0.797	Speed: 2.21 img/s	Time: 0hrs:0min
[2026-02-11 00:12:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.799,19	LR: 0.000998	Loss: 1.071	Speed: 268.09 img/s	Time: 0hrs:0min
[2026-02-11 00:12:54 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8417	MSE: 0.811	Speed: 8.2981img/s	Time: 14.46s

     MSE  Epoch Cohort
0  0.956      1  Train
0  0.811      1   Test

[2026-02-11 00:13:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.462,26	LR: 0.000996	Loss: 1.188	Speed: 2.18 img/s	Time: 0hrs:1min
[2026-02-11 00:13:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.840,30	LR: 0.000995	Loss: 0.882	Speed: 296.80 img/s	Time: 0hrs:1min
[2026-02-11 00:13:24 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8930	MSE: 0.786	Speed: 8.3756img/s	Time: 14.33s

     MSE  Epoch Cohort
0  0.935      2  Train
0  0.786      2   Test

[2026-02-11 00:13:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.503,37	LR: 0.000993	Loss: 1.129	Speed: 2.21 img/s	Time: 0hrs:1min
[2026-02-11 00:13:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.882,41	LR: 0.000991	Loss: 0.813	Speed: 300.39 img/s	Time: 0hrs:1min
[2026-02-11 00:13:53 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8391	MSE: 0.793	Speed: 8.2722img/s	Time: 14.51s

     MSE  Epoch Cohort
0  0.931      3  Train
0  0.793      3   Test

[2026-02-11 00:14:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.544,48	LR: 0.000988	Loss: 0.858	Speed: 2.19 img/s	Time: 0hrs:2min
[2026-02-11 00:14:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.923,52	LR: 0.000985	Loss: 0.933	Speed: 304.22 img/s	Time: 0hrs:2min
[2026-02-11 00:14:22 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8236	MSE: 0.798	Speed: 8.3970img/s	Time: 14.29s

     MSE  Epoch Cohort
0  0.940      4  Train
0  0.798      4   Test

[2026-02-11 00:14:36 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.586,59	LR: 0.000981	Loss: 0.994	Speed: 2.21 img/s	Time: 0hrs:2min
[2026-02-11 00:14:36 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.964,63	LR: 0.000979	Loss: 0.903	Speed: 275.95 img/s	Time: 0hrs:2min
[2026-02-11 00:14:51 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8234	MSE: 0.797	Speed: 8.3154img/s	Time: 14.43s

     MSE  Epoch Cohort
0  0.973      5  Train
0  0.797      5   Test

[2026-02-11 00:15:05 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.627,70	LR: 0.000974	Loss: 0.922	Speed: 2.20 img/s	Time: 0hrs:3min
[2026-02-11 00:15:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.006,74	LR: 0.000971	Loss: 0.964	Speed: 256.71 img/s	Time: 0hrs:3min
[2026-02-11 00:15:21 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8493	MSE: 0.809	Speed: 8.2998img/s	Time: 14.46s

     MSE  Epoch Cohort
0  0.885      6  Train
0  0.809      6   Test

[2026-02-11 00:15:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.669,81	LR: 0.000965	Loss: 0.847	Speed: 2.20 img/s	Time: 0hrs:3min
[2026-02-11 00:15:35 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.047,85	LR: 0.000961	Loss: 0.993	Speed: 305.78 img/s	Time: 0hrs:3min
[2026-02-11 00:15:50 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8758	MSE: 0.859	Speed: 8.2888img/s	Time: 14.48s

     MSE  Epoch Cohort
0  0.883      7  Train
0  0.859      7   Test

[2026-02-11 00:16:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.710,92	LR: 0.000955	Loss: 1.037	Speed: 2.19 img/s	Time: 0hrs:4min
[2026-02-11 00:16:05 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.089,96	LR: 0.000951	Loss: 0.752	Speed: 267.39 img/s	Time: 0hrs:4min
[2026-02-11 00:16:20 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8923	MSE: 0.858	Speed: 8.3143img/s	Time: 14.43s

     MSE  Epoch Cohort
0  0.916      8  Train
0  0.858      8   Test

[2026-02-11 00:16:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.751,103	LR: 0.000944	Loss: 1.064	Speed: 2.20 img/s	Time: 0hrs:4min
[2026-02-11 00:16:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.130,107	LR: 0.000939	Loss: 0.848	Speed: 298.14 img/s	Time: 0hrs:4min
[2026-02-11 00:16:49 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8201	MSE: 0.802	Speed: 8.2807img/s	Time: 14.49s

     MSE  Epoch Cohort
0  0.946      9  Train
0  0.802      9   Test

[2026-02-11 00:17:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.793,114	LR: 0.000931	Loss: 0.891	Speed: 2.19 img/s	Time: 0hrs:5min
[2026-02-11 00:17:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.172,118	LR: 0.000927	Loss: 0.952	Speed: 288.21 img/s	Time: 0hrs:5min
[2026-02-11 00:17:18 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8359	MSE: 0.811	Speed: 8.4051img/s	Time: 14.28s

     MSE  Epoch Cohort
0  0.899     10  Train
0  0.811     10   Test

[2026-02-11 00:17:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.834,125	LR: 0.000918	Loss: 1.057	Speed: 2.21 img/s	Time: 0hrs:5min
[2026-02-11 00:17:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.213,129	LR: 0.000913	Loss: 0.795	Speed: 277.21 img/s	Time: 0hrs:5min
[2026-02-11 00:17:48 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8678	MSE: 0.799	Speed: 8.2943img/s	Time: 14.47s

     MSE  Epoch Cohort
0  0.940     11  Train
0  0.799     11   Test

[2026-02-11 00:18:02 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.876,136	LR: 0.000903	Loss: 0.818	Speed: 2.20 img/s	Time: 0hrs:6min
[2026-02-11 00:18:02 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.254,140	LR: 0.000898	Loss: 1.001	Speed: 294.97 img/s	Time: 0hrs:6min
[2026-02-11 00:18:17 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8775	MSE: 0.795	Speed: 8.4401img/s	Time: 14.22s

     MSE  Epoch Cohort
0  0.948     12  Train
0  0.795     12   Test

[2026-02-11 00:18:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.917,147	LR: 0.000888	Loss: 0.957	Speed: 2.21 img/s	Time: 0hrs:6min
[2026-02-11 00:18:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.296,151	LR: 0.000882	Loss: 0.787	Speed: 300.04 img/s	Time: 0hrs:6min
[2026-02-11 00:18:46 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8100	MSE: 0.787	Speed: 8.3949img/s	Time: 14.29s

     MSE  Epoch Cohort
0  0.956     13  Train
0  0.787     13   Test

[2026-02-11 00:19:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.959,158	LR: 0.000871	Loss: 0.843	Speed: 2.21 img/s	Time: 0hrs:7min
[2026-02-11 00:19:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 15.337,162	LR: 0.000865	Loss: 0.931	Speed: 250.49 img/s	Time: 0hrs:7min
[2026-02-11 00:19:15 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8375	MSE: 0.798	Speed: 8.3330img/s	Time: 14.40s

     MSE  Epoch Cohort
0  0.932     14  Train
0  0.798     14   Test

[2026-02-11 00:19:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.000,169	LR: 0.000854	Loss: 1.005	Speed: 2.20 img/s	Time: 0hrs:7min
[2026-02-11 00:19:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.379,173	LR: 0.000847	Loss: 0.738	Speed: 287.08 img/s	Time: 0hrs:7min
[2026-02-11 00:19:45 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8758	MSE: 0.822	Speed: 8.3914img/s	Time: 14.30s

     MSE  Epoch Cohort
0  0.951     15  Train
0  0.822     15   Test

[2026-02-11 00:19:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.041,180	LR: 0.000835	Loss: 0.931	Speed: 2.21 img/s	Time: 0hrs:8min
[2026-02-11 00:19:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.420,184	LR: 0.000828	Loss: 0.898	Speed: 299.54 img/s	Time: 0hrs:8min
[2026-02-11 00:20:14 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8337	MSE: 0.836	Speed: 8.3788img/s	Time: 14.32s

     MSE  Epoch Cohort
0  0.929     16  Train
0  0.836     16   Test

[2026-02-11 00:20:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.083,191	LR: 0.000816	Loss: 0.961	Speed: 2.21 img/s	Time: 0hrs:8min
[2026-02-11 00:20:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.462,195	LR: 0.000808	Loss: 0.796	Speed: 300.31 img/s	Time: 0hrs:8min
[2026-02-11 00:20:43 - run_regression.py: 233]	INFO	Phase: valid	loss:0.9003	MSE: 0.887	Speed: 8.2746img/s	Time: 14.50s

     MSE  Epoch Cohort
0  0.877     17  Train
0  0.887     17   Test

[2026-02-11 00:20:57 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.124,202	LR: 0.000795	Loss: 0.840	Speed: 2.19 img/s	Time: 0hrs:9min
[2026-02-11 00:20:57 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.503,206	LR: 0.000788	Loss: 0.836	Speed: 252.97 img/s	Time: 0hrs:9min
[2026-02-11 00:21:13 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8768	MSE: 0.867	Speed: 8.3018img/s	Time: 14.45s

     MSE  Epoch Cohort
0  0.855     18  Train
0  0.867     18   Test

[2026-02-11 00:21:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.166,213	LR: 0.000774	Loss: 1.020	Speed: 2.20 img/s	Time: 0hrs:9min
[2026-02-11 00:21:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.544,217	LR: 0.000767	Loss: 0.910	Speed: 294.22 img/s	Time: 0hrs:9min
[2026-02-11 00:21:42 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8179	MSE: 0.819	Speed: 8.3065img/s	Time: 14.45s

     MSE  Epoch Cohort
0  0.860     19  Train
0  0.819     19   Test

[2026-02-11 00:21:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.207,224	LR: 0.000753	Loss: 0.901	Speed: 2.20 img/s	Time: 0hrs:10min
[2026-02-11 00:21:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.586,228	LR: 0.000745	Loss: 0.941	Speed: 268.60 img/s	Time: 0hrs:10min
[2026-02-11 00:22:11 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8148	MSE: 0.807	Speed: 8.3138img/s	Time: 14.43s

     MSE  Epoch Cohort
0  0.940     20  Train
0  0.807     20   Test

[2026-02-11 00:22:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.249,235	LR: 0.000730	Loss: 0.936	Speed: 2.20 img/s	Time: 0hrs:10min
[2026-02-11 00:22:26 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.627,239	LR: 0.000722	Loss: 0.837	Speed: 303.50 img/s	Time: 0hrs:10min
[2026-02-11 00:22:40 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8110	MSE: 0.808	Speed: 8.3794img/s	Time: 14.32s

     MSE  Epoch Cohort
0  0.927     21  Train
0  0.808     21   Test

[2026-02-11 00:22:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.290,246	LR: 0.000707	Loss: 0.796	Speed: 2.21 img/s	Time: 0hrs:10min
[2026-02-11 00:22:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.669,250	LR: 0.000699	Loss: 1.022	Speed: 273.64 img/s	Time: 0hrs:10min
[2026-02-11 00:23:10 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8179	MSE: 0.794	Speed: 8.4057img/s	Time: 14.28s

     MSE  Epoch Cohort
0  0.883     22  Train
0  0.794     22   Test

[2026-02-11 00:23:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.331,257	LR: 0.000684	Loss: 0.853	Speed: 2.21 img/s	Time: 0hrs:11min
[2026-02-11 00:23:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.710,261	LR: 0.000675	Loss: 1.011	Speed: 293.58 img/s	Time: 0hrs:11min
[2026-02-11 00:23:39 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8130	MSE: 0.827	Speed: 8.3835img/s	Time: 14.31s

     MSE  Epoch Cohort
0  0.914     23  Train
0  0.827     23   Test

[2026-02-11 00:23:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.373,268	LR: 0.000660	Loss: 0.819	Speed: 2.21 img/s	Time: 0hrs:11min
[2026-02-11 00:23:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.751,272	LR: 0.000651	Loss: 0.815	Speed: 304.37 img/s	Time: 0hrs:11min
[2026-02-11 00:24:08 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8299	MSE: 0.802	Speed: 8.1630img/s	Time: 14.70s

     MSE  Epoch Cohort
0  0.878     24  Train
0  0.802     24   Test

[2026-02-11 00:24:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.414,279	LR: 0.000635	Loss: 0.867	Speed: 2.18 img/s	Time: 0hrs:12min
[2026-02-11 00:24:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.793,283	LR: 0.000626	Loss: 0.954	Speed: 303.28 img/s	Time: 0hrs:12min
[2026-02-11 00:24:38 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8721	MSE: 0.801	Speed: 8.3767img/s	Time: 14.33s

     MSE  Epoch Cohort
0  0.900     25  Train
0  0.801     25   Test

[2026-02-11 00:24:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.456,290	LR: 0.000611	Loss: 0.848	Speed: 2.21 img/s	Time: 0hrs:12min
[2026-02-11 00:24:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.834,294	LR: 0.000602	Loss: 0.995	Speed: 278.69 img/s	Time: 0hrs:12min
[2026-02-11 00:25:07 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8408	MSE: 0.786	Speed: 8.2949img/s	Time: 14.47s

     MSE  Epoch Cohort
0  0.869     26  Train
0  0.786     26   Test

[2026-02-11 00:25:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.497,301	LR: 0.000586	Loss: 0.910	Speed: 2.19 img/s	Time: 0hrs:13min
[2026-02-11 00:25:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.876,305	LR: 0.000576	Loss: 0.849	Speed: 293.64 img/s	Time: 0hrs:13min
[2026-02-11 00:25:37 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8139	MSE: 0.774	Speed: 8.1104img/s	Time: 14.80s

     MSE  Epoch Cohort
0  0.867     27  Train
0  0.774     27   Test

[2026-02-11 00:25:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.538,312	LR: 0.000560	Loss: 0.854	Speed: 2.15 img/s	Time: 0hrs:13min
[2026-02-11 00:25:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.917,316	LR: 0.000551	Loss: 0.907	Speed: 289.64 img/s	Time: 0hrs:13min
[2026-02-11 00:26:06 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8185	MSE: 0.778	Speed: 8.2930img/s	Time: 14.47s

     MSE  Epoch Cohort
0  0.842     28  Train
0  0.778     28   Test

[2026-02-11 00:26:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.580,323	LR: 0.000535	Loss: 0.935	Speed: 2.18 img/s	Time: 0hrs:14min
[2026-02-11 00:26:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.959,327	LR: 0.000526	Loss: 0.899	Speed: 294.99 img/s	Time: 0hrs:14min
[2026-02-11 00:26:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7934	MSE: 0.766	Speed: 8.1202img/s	Time: 14.78s

     MSE  Epoch Cohort
0  0.903     29  Train
0  0.766     29   Test

[2026-02-11 00:26:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.621,334	LR: 0.000509	Loss: 0.788	Speed: 2.16 img/s	Time: 0hrs:14min
[2026-02-11 00:26:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.000,338	LR: 0.000500	Loss: 0.999	Speed: 262.45 img/s	Time: 0hrs:14min
[2026-02-11 00:27:06 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7980	MSE: 0.771	Speed: 8.3105img/s	Time: 14.44s

     MSE  Epoch Cohort
0  0.930     30  Train
0  0.771     30   Test

[2026-02-11 00:27:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.663,345	LR: 0.000484	Loss: 1.072	Speed: 2.20 img/s	Time: 0hrs:15min
[2026-02-11 00:27:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.041,349	LR: 0.000474	Loss: 0.767	Speed: 309.17 img/s	Time: 0hrs:15min
[2026-02-11 00:27:35 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7912	MSE: 0.758	Speed: 8.3666img/s	Time: 14.34s

     MSE  Epoch Cohort
0  0.883     31  Train
0  0.758     31   Test

[2026-02-11 00:27:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.704,356	LR: 0.000458	Loss: 0.889	Speed: 2.18 img/s	Time: 0hrs:15min
[2026-02-11 00:27:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.083,360	LR: 0.000449	Loss: 1.014	Speed: 264.75 img/s	Time: 0hrs:15min
[2026-02-11 00:28:05 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7771	MSE: 0.760	Speed: 8.1612img/s	Time: 14.70s

     MSE  Epoch Cohort
0  0.902     32  Train
0  0.760     32   Test

[2026-02-11 00:28:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.746,367	LR: 0.000433	Loss: 0.862	Speed: 2.18 img/s	Time: 0hrs:16min
[2026-02-11 00:28:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 35.124,371	LR: 0.000424	Loss: 0.912	Speed: 301.09 img/s	Time: 0hrs:16min
[2026-02-11 00:28:34 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7835	MSE: 0.751	Speed: 8.2125img/s	Time: 14.61s

     MSE  Epoch Cohort
0  0.817     33  Train
0  0.751     33   Test

[2026-02-11 00:28:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 35.787,378	LR: 0.000408	Loss: 0.932	Speed: 2.18 img/s	Time: 0hrs:16min
[2026-02-11 00:28:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 36.166,382	LR: 0.000398	Loss: 0.898	Speed: 265.91 img/s	Time: 0hrs:16min
[2026-02-11 00:29:04 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8041	MSE: 0.755	Speed: 8.2986img/s	Time: 14.46s

     MSE  Epoch Cohort
0  0.884     34  Train
0  0.755     34   Test

[2026-02-11 00:29:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 36.828,389	LR: 0.000383	Loss: 0.931	Speed: 2.20 img/s	Time: 0hrs:17min
[2026-02-11 00:29:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 37.207,393	LR: 0.000374	Loss: 0.955	Speed: 276.91 img/s	Time: 0hrs:17min
[2026-02-11 00:29:33 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7947	MSE: 0.762	Speed: 8.2808img/s	Time: 14.49s

     MSE  Epoch Cohort
0  0.890     35  Train
0  0.762     35   Test

[2026-02-11 00:29:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 37.870,400	LR: 0.000358	Loss: 0.937	Speed: 2.19 img/s	Time: 0hrs:17min
[2026-02-11 00:29:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 38.249,404	LR: 0.000349	Loss: 0.827	Speed: 308.26 img/s	Time: 0hrs:17min
[2026-02-11 00:30:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8033	MSE: 0.766	Speed: 8.2605img/s	Time: 14.53s

     MSE  Epoch Cohort
0  0.864     36  Train
0  0.766     36   Test

[2026-02-11 00:30:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 38.911,411	LR: 0.000334	Loss: 0.910	Speed: 2.19 img/s	Time: 0hrs:18min
[2026-02-11 00:30:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 39.290,415	LR: 0.000325	Loss: 0.806	Speed: 308.51 img/s	Time: 0hrs:18min
[2026-02-11 00:30:32 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8341	MSE: 0.781	Speed: 8.3782img/s	Time: 14.32s

     MSE  Epoch Cohort
0  0.923     37  Train
0  0.781     37   Test

[2026-02-11 00:30:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 39.953,422	LR: 0.000310	Loss: 0.759	Speed: 2.21 img/s	Time: 0hrs:18min
[2026-02-11 00:30:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 40.331,426	LR: 0.000301	Loss: 0.976	Speed: 268.51 img/s	Time: 0hrs:18min
[2026-02-11 00:31:01 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7987	MSE: 0.768	Speed: 8.2813img/s	Time: 14.49s

     MSE  Epoch Cohort
0  0.882     38  Train
0  0.768     38   Test

[2026-02-11 00:31:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 40.994,433	LR: 0.000286	Loss: 0.973	Speed: 2.17 img/s	Time: 0hrs:19min
[2026-02-11 00:31:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 41.373,437	LR: 0.000278	Loss: 0.853	Speed: 291.89 img/s	Time: 0hrs:19min
[2026-02-11 00:31:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7999	MSE: 0.759	Speed: 8.1615img/s	Time: 14.70s

     MSE  Epoch Cohort
0  0.890     39  Train
0  0.759     39   Test

[2026-02-11 00:31:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 42.036,444	LR: 0.000264	Loss: 0.879	Speed: 2.18 img/s	Time: 0hrs:19min
[2026-02-11 00:31:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 42.414,448	LR: 0.000255	Loss: 0.899	Speed: 301.70 img/s	Time: 0hrs:19min
[2026-02-11 00:32:01 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7870	MSE: 0.764	Speed: 8.1495img/s	Time: 14.72s

     MSE  Epoch Cohort
0  0.920     40  Train
0  0.764     40   Test

[2026-02-11 00:32:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 43.077,455	LR: 0.000241	Loss: 0.850	Speed: 2.16 img/s	Time: 0hrs:20min
[2026-02-11 00:32:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 43.456,459	LR: 0.000233	Loss: 0.950	Speed: 303.82 img/s	Time: 0hrs:20min
[2026-02-11 00:32:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8035	MSE: 0.768	Speed: 8.2708img/s	Time: 14.51s

     MSE  Epoch Cohort
0  0.892     41  Train
0  0.768     41   Test

[2026-02-11 00:32:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 44.118,466	LR: 0.000220	Loss: 0.918	Speed: 2.19 img/s	Time: 0hrs:20min
[2026-02-11 00:32:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 44.497,470	LR: 0.000212	Loss: 0.902	Speed: 280.46 img/s	Time: 0hrs:20min
[2026-02-11 00:33:00 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7933	MSE: 0.771	Speed: 8.2103img/s	Time: 14.62s

     MSE  Epoch Cohort
0  0.917     42  Train
0  0.771     42   Test

[2026-02-11 00:33:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 45.160,477	LR: 0.000199	Loss: 0.761	Speed: 2.17 img/s	Time: 0hrs:21min
[2026-02-11 00:33:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 45.538,481	LR: 0.000192	Loss: 0.877	Speed: 293.92 img/s	Time: 0hrs:21min
[2026-02-11 00:33:30 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7752	MSE: 0.771	Speed: 8.1597img/s	Time: 14.71s

     MSE  Epoch Cohort
0  0.920     43  Train
0  0.771     43   Test

[2026-02-11 00:33:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 46.201,488	LR: 0.000179	Loss: 0.893	Speed: 2.15 img/s	Time: 0hrs:21min
[2026-02-11 00:33:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 46.580,492	LR: 0.000172	Loss: 0.842	Speed: 288.16 img/s	Time: 0hrs:21min
[2026-02-11 00:34:00 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8392	MSE: 0.782	Speed: 8.2619img/s	Time: 14.52s

     MSE  Epoch Cohort
0  0.893     44  Train
0  0.782     44   Test

[2026-02-11 00:34:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 47.243,499	LR: 0.000160	Loss: 0.801	Speed: 2.18 img/s	Time: 0hrs:22min
[2026-02-11 00:34:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 47.621,503	LR: 0.000153	Loss: 0.878	Speed: 294.08 img/s	Time: 0hrs:22min
[2026-02-11 00:34:29 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7915	MSE: 0.777	Speed: 8.2722img/s	Time: 14.51s

     MSE  Epoch Cohort
0  0.877     45  Train
0  0.777     45   Test

[2026-02-11 00:34:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 48.284,510	LR: 0.000142	Loss: 0.894	Speed: 2.18 img/s	Time: 0hrs:22min
[2026-02-11 00:34:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 48.663,514	LR: 0.000135	Loss: 0.790	Speed: 302.26 img/s	Time: 0hrs:22min
[2026-02-11 00:34:59 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8305	MSE: 0.771	Speed: 8.2635img/s	Time: 14.52s

     MSE  Epoch Cohort
0  0.933     46  Train
0  0.771     46   Test

[2026-02-11 00:35:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 49.325,521	LR: 0.000124	Loss: 0.937	Speed: 2.18 img/s	Time: 0hrs:23min
[2026-02-11 00:35:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 49.704,525	LR: 0.000118	Loss: 0.898	Speed: 272.16 img/s	Time: 0hrs:23min
[2026-02-11 00:35:28 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7821	MSE: 0.769	Speed: 8.2873img/s	Time: 14.48s

     MSE  Epoch Cohort
0  0.889     47  Train
0  0.769     47   Test

[2026-02-11 00:35:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 50.367,532	LR: 0.000108	Loss: 0.714	Speed: 2.20 img/s	Time: 0hrs:23min
[2026-02-11 00:35:43 - run_regression.py: 178]	INFO	Phase: train	Epoch: 50.746,536	LR: 0.000102	Loss: 1.026	Speed: 311.97 img/s	Time: 0hrs:23min
[2026-02-11 00:35:58 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7839	MSE: 0.772	Speed: 8.2770img/s	Time: 14.50s

     MSE  Epoch Cohort
0  0.860     48  Train
0  0.772     48   Test

[2026-02-11 00:36:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 51.408,543	LR: 0.000093	Loss: 0.884	Speed: 2.18 img/s	Time: 0hrs:24min
[2026-02-11 00:36:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 51.787,547	LR: 0.000087	Loss: 0.866	Speed: 299.41 img/s	Time: 0hrs:24min
[2026-02-11 00:36:27 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7957	MSE: 0.767	Speed: 8.2427img/s	Time: 14.56s

     MSE  Epoch Cohort
0  0.872     49  Train
0  0.767     49   Test

[2026-02-11 00:36:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 52.450,554	LR: 0.000078	Loss: 0.840	Speed: 2.18 img/s	Time: 0hrs:24min
[2026-02-11 00:36:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 52.828,558	LR: 0.000073	Loss: 1.060	Speed: 269.24 img/s	Time: 0hrs:24min
[2026-02-11 00:36:57 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7758	MSE: 0.764	Speed: 8.1707img/s	Time: 14.69s

     MSE  Epoch Cohort
0  0.858     50  Train
0  0.764     50   Test

[2026-02-11 00:37:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 53.491,565	LR: 0.000065	Loss: 1.002	Speed: 2.16 img/s	Time: 0hrs:25min
[2026-02-11 00:37:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 53.870,569	LR: 0.000061	Loss: 0.833	Speed: 302.57 img/s	Time: 0hrs:25min
[2026-02-11 00:37:27 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7892	MSE: 0.763	Speed: 8.2711img/s	Time: 14.51s

     MSE  Epoch Cohort
0  0.875     51  Train
0  0.763     51   Test

[2026-02-11 00:37:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 54.533,576	LR: 0.000053	Loss: 1.028	Speed: 2.18 img/s	Time: 0hrs:25min
[2026-02-11 00:37:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 54.911,580	LR: 0.000049	Loss: 0.828	Speed: 302.98 img/s	Time: 0hrs:25min
[2026-02-11 00:37:57 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8275	MSE: 0.765	Speed: 8.1496img/s	Time: 14.72s

     MSE  Epoch Cohort
0  0.914     52  Train
0  0.765     52   Test

[2026-02-11 00:38:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 55.574,587	LR: 0.000042	Loss: 0.853	Speed: 2.16 img/s	Time: 0hrs:26min
[2026-02-11 00:38:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 55.953,591	LR: 0.000039	Loss: 0.934	Speed: 306.88 img/s	Time: 0hrs:26min
[2026-02-11 00:38:26 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8007	MSE: 0.760	Speed: 8.3724img/s	Time: 14.33s

     MSE  Epoch Cohort
0  0.919     53  Train
0  0.760     53   Test

[2026-02-11 00:38:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 56.615,598	LR: 0.000032	Loss: 1.075	Speed: 2.21 img/s	Time: 0hrs:26min
[2026-02-11 00:38:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 56.994,602	LR: 0.000029	Loss: 0.716	Speed: 246.71 img/s	Time: 0hrs:26min
[2026-02-11 00:38:56 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8029	MSE: 0.771	Speed: 8.1913img/s	Time: 14.65s

     MSE  Epoch Cohort
0  0.900     54  Train
0  0.771     54   Test

[2026-02-11 00:39:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 57.657,609	LR: 0.000024	Loss: 0.987	Speed: 2.17 img/s	Time: 0hrs:27min
[2026-02-11 00:39:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 58.036,613	LR: 0.000021	Loss: 0.693	Speed: 280.36 img/s	Time: 0hrs:27min
[2026-02-11 00:39:25 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8122	MSE: 0.770	Speed: 8.1814img/s	Time: 14.67s

     MSE  Epoch Cohort
0  0.901     55  Train
0  0.770     55   Test

[2026-02-11 00:39:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 58.698,620	LR: 0.000017	Loss: 0.914	Speed: 2.17 img/s	Time: 0hrs:27min
[2026-02-11 00:39:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 59.077,624	LR: 0.000015	Loss: 0.958	Speed: 288.09 img/s	Time: 0hrs:27min
[2026-02-11 00:39:55 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8006	MSE: 0.770	Speed: 8.2806img/s	Time: 14.49s

     MSE  Epoch Cohort
0  0.882     56  Train
0  0.770     56   Test

[2026-02-11 00:40:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 59.740,631	LR: 0.000011	Loss: 0.887	Speed: 2.18 img/s	Time: 0hrs:28min
[2026-02-11 00:40:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 60.118,635	LR: 0.000009	Loss: 0.972	Speed: 305.46 img/s	Time: 0hrs:28min
[2026-02-11 00:40:25 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8045	MSE: 0.764	Speed: 8.2645img/s	Time: 14.52s

     MSE  Epoch Cohort
0  0.852     57  Train
0  0.764     57   Test

[2026-02-11 00:40:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 60.781,642	LR: 0.000006	Loss: 0.865	Speed: 2.18 img/s	Time: 0hrs:28min
[2026-02-11 00:40:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 61.160,646	LR: 0.000005	Loss: 1.014	Speed: 301.17 img/s	Time: 0hrs:28min
[2026-02-11 00:40:54 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8436	MSE: 0.774	Speed: 8.2708img/s	Time: 14.51s

     MSE  Epoch Cohort
0  0.880     58  Train
0  0.774     58   Test

[2026-02-11 00:41:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 61.822,653	LR: 0.000003	Loss: 0.838	Speed: 2.19 img/s	Time: 0hrs:29min
[2026-02-11 00:41:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 62.201,657	LR: 0.000002	Loss: 0.894	Speed: 273.29 img/s	Time: 0hrs:29min
[2026-02-11 00:41:24 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8049	MSE: 0.768	Speed: 8.3031img/s	Time: 14.45s

     MSE  Epoch Cohort
0  0.881     59  Train
0  0.768     59   Test

[2026-02-11 00:41:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 62.864,664	LR: 0.000001	Loss: 0.876	Speed: 2.18 img/s	Time: 0hrs:29min
[2026-02-11 00:41:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 63.243,668	LR: 0.000000	Loss: 0.872	Speed: 306.01 img/s	Time: 0hrs:29min
[2026-02-11 00:41:53 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7999	MSE: 0.766	Speed: 8.2545img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.868     60  Train
0  0.766     60   Test

[2026-02-11 00:42:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 63.905,675	LR: 0.000000	Loss: 0.955	Speed: 2.18 img/s	Time: 0hrs:30min
[2026-02-11 00:42:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 64.284,679	LR: 0.000000	Loss: 0.725	Speed: 302.55 img/s	Time: 0hrs:30min
[2026-02-11 00:42:23 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7975	MSE: 0.766	Speed: 8.2653img/s	Time: 14.52s

     MSE  Epoch Cohort
0  0.913     61  Train
0  0.766     61   Test

[2026-02-11 00:42:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 64.947,686	LR: 0.000001	Loss: 0.975	Speed: 2.18 img/s	Time: 0hrs:30min
[2026-02-11 00:42:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 65.325,690	LR: 0.000001	Loss: 0.916	Speed: 298.30 img/s	Time: 0hrs:30min
[2026-02-11 00:42:52 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7750	MSE: 0.772	Speed: 8.3060img/s	Time: 14.45s

     MSE  Epoch Cohort
0  0.856     62  Train
0  0.772     62   Test

[2026-02-11 00:43:06 - run_regression.py: 178]	INFO	Phase: train	Epoch: 65.988,697	LR: 0.000002	Loss: 0.830	Speed: 2.20 img/s	Time: 0hrs:31min
[2026-02-11 00:43:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 66.367,701	LR: 0.000003	Loss: 0.899	Speed: 305.36 img/s	Time: 0hrs:31min
[2026-02-11 00:43:22 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7816	MSE: 0.775	Speed: 8.3725img/s	Time: 14.33s

     MSE  Epoch Cohort
0  0.895     63  Train
0  0.775     63   Test

[2026-02-11 00:43:22 - run_regression.py: 369]	INFO	Done for training. Best metric is 0.9104278030737082@1 epoch. Average for last 5 iters is 0.7693372419970417
[2026-02-11 00:43:22 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-0.txt
[2026-02-11 00:43:22 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-0.txt
[2026-02-11 00:43:22 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-0.txt
[2026-02-11 00:43:22 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-0.txt
[2026-02-11 00:43:22 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-02-11 00:43:22 - about_log.py: 149]	INFO		Number of samples: 169
[2026-02-11 00:43:22 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-11 00:43:22 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task2\split_info\labels.txt
[2026-02-11 00:43:22 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-02-11 00:43:22 - about_log.py: 149]	INFO		Number of samples: 120
[2026-02-11 00:43:22 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-11 00:43:22 - run_regression.py: 305]	INFO	Creating model vgg19...
[2026-02-11 00:43:22 - run_regression.py: 352]	INFO	Start training...
[2026-02-11 00:43:36 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.379,4	LR: 0.001000	Loss: 1.224	Speed: 4.52 img/s	Time: 0hrs:0min
[2026-02-11 00:43:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.757,8	LR: 0.001000	Loss: 1.151	Speed: 223.36 img/s	Time: 0hrs:0min
[2026-02-11 00:43:53 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7907	MSE: 0.735	Speed: 8.1862img/s	Time: 14.66s

     MSE  Epoch Cohort
0  1.088      0  Train
0  0.735      0   Test

[2026-02-11 00:44:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.420,15	LR: 0.000999	Loss: 0.837	Speed: 2.12 img/s	Time: 0hrs:0min
[2026-02-11 00:44:07 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.799,19	LR: 0.000998	Loss: 1.084	Speed: 211.10 img/s	Time: 0hrs:0min
[2026-02-11 00:44:23 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7900	MSE: 0.730	Speed: 8.1387img/s	Time: 14.74s

     MSE  Epoch Cohort
0  0.934      1  Train
0  0.730      1   Test

[2026-02-11 00:44:37 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.462,26	LR: 0.000996	Loss: 0.888	Speed: 2.12 img/s	Time: 0hrs:1min
[2026-02-11 00:44:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.840,30	LR: 0.000995	Loss: 0.868	Speed: 225.87 img/s	Time: 0hrs:1min
[2026-02-11 00:44:53 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7985	MSE: 0.736	Speed: 8.2645img/s	Time: 14.52s

     MSE  Epoch Cohort
0  0.910      2  Train
0  0.736      2   Test

[2026-02-11 00:45:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.503,37	LR: 0.000993	Loss: 0.938	Speed: 2.14 img/s	Time: 0hrs:1min
[2026-02-11 00:45:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.882,41	LR: 0.000991	Loss: 0.977	Speed: 221.20 img/s	Time: 0hrs:1min
[2026-02-11 00:45:24 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7783	MSE: 0.725	Speed: 8.1739img/s	Time: 14.68s

     MSE  Epoch Cohort
0  0.922      3  Train
0  0.725      3   Test

[2026-02-11 00:45:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.544,48	LR: 0.000988	Loss: 0.765	Speed: 2.13 img/s	Time: 0hrs:2min
[2026-02-11 00:45:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.923,52	LR: 0.000985	Loss: 1.009	Speed: 226.27 img/s	Time: 0hrs:2min
[2026-02-11 00:45:54 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8166	MSE: 0.736	Speed: 8.2596img/s	Time: 14.53s

     MSE  Epoch Cohort
0  0.855      4  Train
0  0.736      4   Test

[2026-02-11 00:46:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.586,59	LR: 0.000981	Loss: 0.910	Speed: 2.14 img/s	Time: 0hrs:2min
[2026-02-11 00:46:08 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.964,63	LR: 0.000979	Loss: 0.928	Speed: 226.82 img/s	Time: 0hrs:2min
[2026-02-11 00:46:24 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7826	MSE: 0.727	Speed: 8.2615img/s	Time: 14.53s

     MSE  Epoch Cohort
0  0.919      5  Train
0  0.727      5   Test

[2026-02-11 00:46:38 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.627,70	LR: 0.000974	Loss: 1.068	Speed: 2.14 img/s	Time: 0hrs:3min
[2026-02-11 00:46:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.006,74	LR: 0.000971	Loss: 0.787	Speed: 225.27 img/s	Time: 0hrs:3min
[2026-02-11 00:46:54 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8222	MSE: 0.726	Speed: 8.2544img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.932      6  Train
0  0.726      6   Test

[2026-02-11 00:47:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.669,81	LR: 0.000965	Loss: 0.951	Speed: 2.14 img/s	Time: 0hrs:3min
[2026-02-11 00:47:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.047,85	LR: 0.000961	Loss: 0.802	Speed: 225.99 img/s	Time: 0hrs:3min
[2026-02-11 00:47:25 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7819	MSE: 0.730	Speed: 8.2565img/s	Time: 14.53s

    MSE  Epoch Cohort
0  0.93      7  Train
0  0.73      7   Test

[2026-02-11 00:47:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.710,92	LR: 0.000955	Loss: 0.908	Speed: 2.14 img/s	Time: 0hrs:4min
[2026-02-11 00:47:39 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.089,96	LR: 0.000951	Loss: 0.782	Speed: 225.03 img/s	Time: 0hrs:4min
[2026-02-11 00:47:55 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7905	MSE: 0.725	Speed: 8.1680img/s	Time: 14.69s

     MSE  Epoch Cohort
0  0.897      8  Train
0  0.725      8   Test

[2026-02-11 00:48:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 9.751,103	LR: 0.000944	Loss: 0.942	Speed: 2.13 img/s	Time: 0hrs:4min
[2026-02-11 00:48:09 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.130,107	LR: 0.000939	Loss: 0.797	Speed: 226.00 img/s	Time: 0hrs:4min
[2026-02-11 00:48:25 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7570	MSE: 0.724	Speed: 8.1441img/s	Time: 14.73s

     MSE  Epoch Cohort
0  0.917      9  Train
0  0.724      9   Test

[2026-02-11 00:48:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 10.793,114	LR: 0.000931	Loss: 0.828	Speed: 2.13 img/s	Time: 0hrs:5min
[2026-02-11 00:48:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.172,118	LR: 0.000927	Loss: 0.989	Speed: 225.20 img/s	Time: 0hrs:5min
[2026-02-11 00:48:56 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7830	MSE: 0.724	Speed: 8.1428img/s	Time: 14.74s

     MSE  Epoch Cohort
0  0.885     10  Train
0  0.724     10   Test

[2026-02-11 00:49:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 11.834,125	LR: 0.000918	Loss: 0.926	Speed: 2.12 img/s	Time: 0hrs:5min
[2026-02-11 00:49:10 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.213,129	LR: 0.000913	Loss: 0.901	Speed: 224.71 img/s	Time: 0hrs:5min
[2026-02-11 00:49:26 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7776	MSE: 0.726	Speed: 8.2539img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.907     11  Train
0  0.726     11   Test

[2026-02-11 00:49:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 12.876,136	LR: 0.000903	Loss: 0.956	Speed: 2.14 img/s	Time: 0hrs:6min
[2026-02-11 00:49:40 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.254,140	LR: 0.000898	Loss: 0.875	Speed: 225.21 img/s	Time: 0hrs:6min
[2026-02-11 00:49:56 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7828	MSE: 0.727	Speed: 8.1610img/s	Time: 14.70s

     MSE  Epoch Cohort
0  0.930     12  Train
0  0.727     12   Test

[2026-02-11 00:50:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 13.917,147	LR: 0.000888	Loss: 0.899	Speed: 2.13 img/s	Time: 0hrs:6min
[2026-02-11 00:50:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.296,151	LR: 0.000882	Loss: 0.890	Speed: 226.13 img/s	Time: 0hrs:6min
[2026-02-11 00:50:27 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7814	MSE: 0.730	Speed: 8.1590img/s	Time: 14.71s

     MSE  Epoch Cohort
0  0.894     13  Train
0  0.730     13   Test

[2026-02-11 00:50:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 14.959,158	LR: 0.000871	Loss: 0.771	Speed: 2.14 img/s	Time: 0hrs:7min
[2026-02-11 00:50:41 - run_regression.py: 178]	INFO	Phase: train	Epoch: 15.337,162	LR: 0.000865	Loss: 1.009	Speed: 224.96 img/s	Time: 0hrs:7min
[2026-02-11 00:50:57 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8062	MSE: 0.732	Speed: 8.2560img/s	Time: 14.53s

     MSE  Epoch Cohort
0  0.931     14  Train
0  0.732     14   Test

[2026-02-11 00:51:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.000,169	LR: 0.000854	Loss: 0.755	Speed: 2.14 img/s	Time: 0hrs:7min
[2026-02-11 00:51:11 - run_regression.py: 178]	INFO	Phase: train	Epoch: 16.379,173	LR: 0.000847	Loss: 0.838	Speed: 224.80 img/s	Time: 0hrs:7min
[2026-02-11 00:51:27 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7951	MSE: 0.738	Speed: 8.0468img/s	Time: 14.91s

     MSE  Epoch Cohort
0  0.892     15  Train
0  0.738     15   Test

[2026-02-11 00:51:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.041,180	LR: 0.000835	Loss: 0.752	Speed: 2.10 img/s	Time: 0hrs:8min
[2026-02-11 00:51:42 - run_regression.py: 178]	INFO	Phase: train	Epoch: 17.420,184	LR: 0.000828	Loss: 0.912	Speed: 224.30 img/s	Time: 0hrs:8min
[2026-02-11 00:51:58 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8020	MSE: 0.728	Speed: 8.0494img/s	Time: 14.91s

     MSE  Epoch Cohort
0  0.894     16  Train
0  0.728     16   Test

[2026-02-11 00:52:12 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.083,191	LR: 0.000816	Loss: 0.784	Speed: 2.10 img/s	Time: 0hrs:8min
[2026-02-11 00:52:13 - run_regression.py: 178]	INFO	Phase: train	Epoch: 18.462,195	LR: 0.000808	Loss: 1.076	Speed: 225.01 img/s	Time: 0hrs:8min
[2026-02-11 00:52:29 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7682	MSE: 0.727	Speed: 8.0361img/s	Time: 14.93s

     MSE  Epoch Cohort
0  0.907     17  Train
0  0.727     17   Test

[2026-02-11 00:52:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.124,202	LR: 0.000795	Loss: 0.824	Speed: 2.07 img/s	Time: 0hrs:9min
[2026-02-11 00:52:44 - run_regression.py: 178]	INFO	Phase: train	Epoch: 19.503,206	LR: 0.000788	Loss: 0.914	Speed: 223.98 img/s	Time: 0hrs:9min
[2026-02-11 00:53:00 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7510	MSE: 0.728	Speed: 8.1259img/s	Time: 14.77s

     MSE  Epoch Cohort
0  0.875     18  Train
0  0.728     18   Test

[2026-02-11 00:53:14 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.166,213	LR: 0.000774	Loss: 0.948	Speed: 2.10 img/s	Time: 0hrs:9min
[2026-02-11 00:53:15 - run_regression.py: 178]	INFO	Phase: train	Epoch: 20.544,217	LR: 0.000767	Loss: 0.852	Speed: 219.02 img/s	Time: 0hrs:9min
[2026-02-11 00:53:31 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7677	MSE: 0.728	Speed: 8.0375img/s	Time: 14.93s

     MSE  Epoch Cohort
0  0.883     19  Train
0  0.728     19   Test

[2026-02-11 00:53:45 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.207,224	LR: 0.000753	Loss: 0.987	Speed: 2.10 img/s	Time: 0hrs:10min
[2026-02-11 00:53:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 21.586,228	LR: 0.000745	Loss: 0.870	Speed: 225.49 img/s	Time: 0hrs:10min
[2026-02-11 00:54:01 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7792	MSE: 0.728	Speed: 8.1722img/s	Time: 14.68s

     MSE  Epoch Cohort
0  0.905     20  Train
0  0.728     20   Test

[2026-02-11 00:54:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.249,235	LR: 0.000730	Loss: 0.827	Speed: 2.11 img/s	Time: 0hrs:10min
[2026-02-11 00:54:16 - run_regression.py: 178]	INFO	Phase: train	Epoch: 22.627,239	LR: 0.000722	Loss: 0.831	Speed: 215.88 img/s	Time: 0hrs:10min
[2026-02-11 00:54:32 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7840	MSE: 0.728	Speed: 8.1994img/s	Time: 14.64s

     MSE  Epoch Cohort
0  0.890     21  Train
0  0.728     21   Test

[2026-02-11 00:54:46 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.290,246	LR: 0.000707	Loss: 0.955	Speed: 2.13 img/s	Time: 0hrs:11min
[2026-02-11 00:54:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 23.669,250	LR: 0.000699	Loss: 0.899	Speed: 225.04 img/s	Time: 0hrs:11min
[2026-02-11 00:55:02 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7718	MSE: 0.724	Speed: 8.1448img/s	Time: 14.73s

     MSE  Epoch Cohort
0  0.919     22  Train
0  0.724     22   Test

[2026-02-11 00:55:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.331,257	LR: 0.000684	Loss: 0.846	Speed: 2.12 img/s	Time: 0hrs:11min
[2026-02-11 00:55:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 24.710,261	LR: 0.000675	Loss: 0.892	Speed: 225.46 img/s	Time: 0hrs:11min
[2026-02-11 00:55:33 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7803	MSE: 0.728	Speed: 8.1665img/s	Time: 14.69s

     MSE  Epoch Cohort
0  0.869     23  Train
0  0.728     23   Test

[2026-02-11 00:55:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.373,268	LR: 0.000660	Loss: 0.701	Speed: 2.13 img/s	Time: 0hrs:12min
[2026-02-11 00:55:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 25.751,272	LR: 0.000651	Loss: 1.004	Speed: 225.55 img/s	Time: 0hrs:12min
[2026-02-11 00:56:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8046	MSE: 0.724	Speed: 8.2455img/s	Time: 14.55s

     MSE  Epoch Cohort
0  0.887     24  Train
0  0.724     24   Test

[2026-02-11 00:56:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.414,279	LR: 0.000635	Loss: 0.853	Speed: 2.14 img/s	Time: 0hrs:12min
[2026-02-11 00:56:17 - run_regression.py: 178]	INFO	Phase: train	Epoch: 26.793,283	LR: 0.000626	Loss: 0.972	Speed: 225.66 img/s	Time: 0hrs:12min
[2026-02-11 00:56:33 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8135	MSE: 0.723	Speed: 8.2456img/s	Time: 14.55s

     MSE  Epoch Cohort
0  0.901     25  Train
0  0.723     25   Test

[2026-02-11 00:56:47 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.456,290	LR: 0.000611	Loss: 0.897	Speed: 2.14 img/s	Time: 0hrs:13min
[2026-02-11 00:56:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 27.834,294	LR: 0.000602	Loss: 0.872	Speed: 225.80 img/s	Time: 0hrs:13min
[2026-02-11 00:57:03 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8003	MSE: 0.723	Speed: 8.2534img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.895     26  Train
0  0.723     26   Test

[2026-02-11 00:57:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.497,301	LR: 0.000586	Loss: 0.942	Speed: 2.14 img/s	Time: 0hrs:13min
[2026-02-11 00:57:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 28.876,305	LR: 0.000576	Loss: 0.822	Speed: 225.50 img/s	Time: 0hrs:13min
[2026-02-11 00:57:34 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7842	MSE: 0.723	Speed: 8.1497img/s	Time: 14.72s

     MSE  Epoch Cohort
0  0.879     27  Train
0  0.723     27   Test

[2026-02-11 00:57:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.538,312	LR: 0.000560	Loss: 0.838	Speed: 2.12 img/s	Time: 0hrs:14min
[2026-02-11 00:57:48 - run_regression.py: 178]	INFO	Phase: train	Epoch: 29.917,316	LR: 0.000551	Loss: 1.048	Speed: 224.40 img/s	Time: 0hrs:14min
[2026-02-11 00:58:04 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7660	MSE: 0.727	Speed: 8.2622img/s	Time: 14.52s

     MSE  Epoch Cohort
0  0.888     28  Train
0  0.727     28   Test

[2026-02-11 00:58:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.580,323	LR: 0.000535	Loss: 0.975	Speed: 2.14 img/s	Time: 0hrs:14min
[2026-02-11 00:58:18 - run_regression.py: 178]	INFO	Phase: train	Epoch: 30.959,327	LR: 0.000526	Loss: 0.752	Speed: 225.30 img/s	Time: 0hrs:14min
[2026-02-11 00:58:34 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7973	MSE: 0.723	Speed: 8.1594img/s	Time: 14.71s

     MSE  Epoch Cohort
0  0.873     29  Train
0  0.723     29   Test

[2026-02-11 00:58:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 31.621,334	LR: 0.000509	Loss: 0.828	Speed: 2.13 img/s	Time: 0hrs:15min
[2026-02-11 00:58:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.000,338	LR: 0.000500	Loss: 0.871	Speed: 224.60 img/s	Time: 0hrs:15min
[2026-02-11 00:59:05 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8080	MSE: 0.725	Speed: 8.1594img/s	Time: 14.71s

     MSE  Epoch Cohort
0  0.883     30  Train
0  0.725     30   Test

[2026-02-11 00:59:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 32.663,345	LR: 0.000484	Loss: 0.895	Speed: 2.13 img/s	Time: 0hrs:15min
[2026-02-11 00:59:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.041,349	LR: 0.000474	Loss: 0.798	Speed: 223.94 img/s	Time: 0hrs:15min
[2026-02-11 00:59:35 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7742	MSE: 0.723	Speed: 8.2510img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.860     31  Train
0  0.723     31   Test

[2026-02-11 00:59:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 33.704,356	LR: 0.000458	Loss: 0.922	Speed: 2.14 img/s	Time: 0hrs:16min
[2026-02-11 00:59:49 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.083,360	LR: 0.000449	Loss: 0.895	Speed: 225.56 img/s	Time: 0hrs:16min
[2026-02-11 01:00:05 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7681	MSE: 0.725	Speed: 8.2536img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.888     32  Train
0  0.725     32   Test

[2026-02-11 01:00:19 - run_regression.py: 178]	INFO	Phase: train	Epoch: 34.746,367	LR: 0.000433	Loss: 0.792	Speed: 2.14 img/s	Time: 0hrs:16min
[2026-02-11 01:00:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 35.124,371	LR: 0.000424	Loss: 0.939	Speed: 225.45 img/s	Time: 0hrs:16min
[2026-02-11 01:00:35 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7686	MSE: 0.723	Speed: 8.2523img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.877     33  Train
0  0.723     33   Test

[2026-02-11 01:00:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 35.787,378	LR: 0.000408	Loss: 0.915	Speed: 2.14 img/s	Time: 0hrs:17min
[2026-02-11 01:00:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 36.166,382	LR: 0.000398	Loss: 0.772	Speed: 225.55 img/s	Time: 0hrs:17min
[2026-02-11 01:01:06 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7532	MSE: 0.724	Speed: 8.1677img/s	Time: 14.69s

     MSE  Epoch Cohort
0  0.863     34  Train
0  0.724     34   Test

[2026-02-11 01:01:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 36.828,389	LR: 0.000383	Loss: 1.139	Speed: 2.14 img/s	Time: 0hrs:17min
[2026-02-11 01:01:20 - run_regression.py: 178]	INFO	Phase: train	Epoch: 37.207,393	LR: 0.000374	Loss: 0.673	Speed: 224.47 img/s	Time: 0hrs:17min
[2026-02-11 01:01:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7732	MSE: 0.724	Speed: 8.1995img/s	Time: 14.64s

     MSE  Epoch Cohort
0  0.876     35  Train
0  0.724     35   Test

[2026-02-11 01:01:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 37.870,400	LR: 0.000358	Loss: 0.909	Speed: 2.13 img/s	Time: 0hrs:18min
[2026-02-11 01:01:50 - run_regression.py: 178]	INFO	Phase: train	Epoch: 38.249,404	LR: 0.000349	Loss: 0.929	Speed: 225.74 img/s	Time: 0hrs:18min
[2026-02-11 01:02:06 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7671	MSE: 0.725	Speed: 8.1643img/s	Time: 14.70s

     MSE  Epoch Cohort
0  0.881     36  Train
0  0.725     36   Test

[2026-02-11 01:02:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 38.911,411	LR: 0.000334	Loss: 0.941	Speed: 2.13 img/s	Time: 0hrs:18min
[2026-02-11 01:02:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 39.290,415	LR: 0.000325	Loss: 0.878	Speed: 225.92 img/s	Time: 0hrs:18min
[2026-02-11 01:02:36 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7831	MSE: 0.728	Speed: 8.2649img/s	Time: 14.52s

     MSE  Epoch Cohort
0  0.882     37  Train
0  0.728     37   Test

[2026-02-11 01:02:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 39.953,422	LR: 0.000310	Loss: 0.865	Speed: 2.14 img/s	Time: 0hrs:19min
[2026-02-11 01:02:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 40.331,426	LR: 0.000301	Loss: 0.947	Speed: 224.74 img/s	Time: 0hrs:19min
[2026-02-11 01:03:07 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8168	MSE: 0.724	Speed: 8.1884img/s	Time: 14.65s

     MSE  Epoch Cohort
0  0.879     38  Train
0  0.724     38   Test

[2026-02-11 01:03:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 40.994,433	LR: 0.000286	Loss: 0.796	Speed: 2.13 img/s	Time: 0hrs:19min
[2026-02-11 01:03:21 - run_regression.py: 178]	INFO	Phase: train	Epoch: 41.373,437	LR: 0.000278	Loss: 0.941	Speed: 224.42 img/s	Time: 0hrs:19min
[2026-02-11 01:03:37 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7707	MSE: 0.725	Speed: 8.1363img/s	Time: 14.75s

     MSE  Epoch Cohort
0  0.870     39  Train
0  0.725     39   Test

[2026-02-11 01:03:51 - run_regression.py: 178]	INFO	Phase: train	Epoch: 42.036,444	LR: 0.000264	Loss: 0.954	Speed: 2.13 img/s	Time: 0hrs:20min
[2026-02-11 01:03:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 42.414,448	LR: 0.000255	Loss: 0.847	Speed: 223.25 img/s	Time: 0hrs:20min
[2026-02-11 01:04:07 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7806	MSE: 0.724	Speed: 8.2534img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.875     40  Train
0  0.724     40   Test

[2026-02-11 01:04:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 43.077,455	LR: 0.000241	Loss: 0.844	Speed: 2.14 img/s	Time: 0hrs:20min
[2026-02-11 01:04:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 43.456,459	LR: 0.000233	Loss: 0.969	Speed: 224.64 img/s	Time: 0hrs:20min
[2026-02-11 01:04:38 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7704	MSE: 0.724	Speed: 8.2590img/s	Time: 14.53s

     MSE  Epoch Cohort
0  0.865     41  Train
0  0.724     41   Test

[2026-02-11 01:04:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 44.118,466	LR: 0.000220	Loss: 1.019	Speed: 2.15 img/s	Time: 0hrs:21min
[2026-02-11 01:04:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 44.497,470	LR: 0.000212	Loss: 0.824	Speed: 225.63 img/s	Time: 0hrs:21min
[2026-02-11 01:05:08 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7670	MSE: 0.723	Speed: 8.1818img/s	Time: 14.67s

     MSE  Epoch Cohort
0  0.893     42  Train
0  0.723     42   Test

[2026-02-11 01:05:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 45.160,477	LR: 0.000199	Loss: 0.867	Speed: 2.13 img/s	Time: 0hrs:21min
[2026-02-11 01:05:22 - run_regression.py: 178]	INFO	Phase: train	Epoch: 45.538,481	LR: 0.000192	Loss: 0.853	Speed: 226.13 img/s	Time: 0hrs:22min
[2026-02-11 01:05:38 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7975	MSE: 0.724	Speed: 8.1533img/s	Time: 14.72s

     MSE  Epoch Cohort
0  0.877     43  Train
0  0.724     43   Test

[2026-02-11 01:05:52 - run_regression.py: 178]	INFO	Phase: train	Epoch: 46.201,488	LR: 0.000179	Loss: 0.867	Speed: 2.12 img/s	Time: 0hrs:22min
[2026-02-11 01:05:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 46.580,492	LR: 0.000172	Loss: 0.912	Speed: 226.05 img/s	Time: 0hrs:22min
[2026-02-11 01:06:08 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7642	MSE: 0.723	Speed: 8.2483img/s	Time: 14.55s

     MSE  Epoch Cohort
0  0.893     44  Train
0  0.723     44   Test

[2026-02-11 01:06:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 47.243,499	LR: 0.000160	Loss: 0.898	Speed: 2.14 img/s	Time: 0hrs:23min
[2026-02-11 01:06:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 47.621,503	LR: 0.000153	Loss: 0.871	Speed: 226.36 img/s	Time: 0hrs:23min
[2026-02-11 01:06:39 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7631	MSE: 0.723	Speed: 8.2515img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.836     45  Train
0  0.723     45   Test

[2026-02-11 01:06:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 48.284,510	LR: 0.000142	Loss: 0.890	Speed: 2.14 img/s	Time: 0hrs:23min
[2026-02-11 01:06:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 48.663,514	LR: 0.000135	Loss: 0.831	Speed: 226.18 img/s	Time: 0hrs:23min
[2026-02-11 01:07:09 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8122	MSE: 0.724	Speed: 8.2347img/s	Time: 14.57s

     MSE  Epoch Cohort
0  0.840     46  Train
0  0.724     46   Test

[2026-02-11 01:07:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 49.325,521	LR: 0.000124	Loss: 0.944	Speed: 2.14 img/s	Time: 0hrs:24min
[2026-02-11 01:07:23 - run_regression.py: 178]	INFO	Phase: train	Epoch: 49.704,525	LR: 0.000118	Loss: 0.793	Speed: 225.34 img/s	Time: 0hrs:24min
[2026-02-11 01:07:39 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7618	MSE: 0.724	Speed: 8.1596img/s	Time: 14.71s

     MSE  Epoch Cohort
0  0.868     47  Train
0  0.724     47   Test

[2026-02-11 01:07:53 - run_regression.py: 178]	INFO	Phase: train	Epoch: 50.367,532	LR: 0.000108	Loss: 0.885	Speed: 2.13 img/s	Time: 0hrs:24min
[2026-02-11 01:07:54 - run_regression.py: 178]	INFO	Phase: train	Epoch: 50.746,536	LR: 0.000102	Loss: 0.864	Speed: 225.34 img/s	Time: 0hrs:24min
[2026-02-11 01:08:10 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7696	MSE: 0.724	Speed: 8.1663img/s	Time: 14.69s

     MSE  Epoch Cohort
0  0.873     48  Train
0  0.724     48   Test

[2026-02-11 01:08:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 51.408,543	LR: 0.000093	Loss: 0.966	Speed: 2.12 img/s	Time: 0hrs:25min
[2026-02-11 01:08:24 - run_regression.py: 178]	INFO	Phase: train	Epoch: 51.787,547	LR: 0.000087	Loss: 0.827	Speed: 225.99 img/s	Time: 0hrs:25min
[2026-02-11 01:08:40 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8000	MSE: 0.724	Speed: 8.0532img/s	Time: 14.90s

     MSE  Epoch Cohort
0  0.878     49  Train
0  0.724     49   Test

[2026-02-11 01:08:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 52.450,554	LR: 0.000078	Loss: 0.850	Speed: 2.10 img/s	Time: 0hrs:25min
[2026-02-11 01:08:55 - run_regression.py: 178]	INFO	Phase: train	Epoch: 52.828,558	LR: 0.000073	Loss: 0.864	Speed: 216.86 img/s	Time: 0hrs:25min
[2026-02-11 01:09:11 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7684	MSE: 0.724	Speed: 8.0583img/s	Time: 14.89s

     MSE  Epoch Cohort
0  0.864     50  Train
0  0.724     50   Test

[2026-02-11 01:09:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 53.491,565	LR: 0.000065	Loss: 0.845	Speed: 2.11 img/s	Time: 0hrs:26min
[2026-02-11 01:09:25 - run_regression.py: 178]	INFO	Phase: train	Epoch: 53.870,569	LR: 0.000061	Loss: 0.906	Speed: 223.58 img/s	Time: 0hrs:26min
[2026-02-11 01:09:41 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7747	MSE: 0.724	Speed: 8.1616img/s	Time: 14.70s

     MSE  Epoch Cohort
0  0.849     51  Train
0  0.724     51   Test

[2026-02-11 01:09:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 54.533,576	LR: 0.000053	Loss: 0.883	Speed: 2.13 img/s	Time: 0hrs:26min
[2026-02-11 01:09:56 - run_regression.py: 178]	INFO	Phase: train	Epoch: 54.911,580	LR: 0.000049	Loss: 0.755	Speed: 223.28 img/s	Time: 0hrs:26min
[2026-02-11 01:10:12 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7588	MSE: 0.724	Speed: 8.2914img/s	Time: 14.47s

     MSE  Epoch Cohort
0  0.864     52  Train
0  0.724     52   Test

[2026-02-11 01:10:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 55.574,587	LR: 0.000042	Loss: 0.829	Speed: 2.08 img/s	Time: 0hrs:27min
[2026-02-11 01:10:27 - run_regression.py: 178]	INFO	Phase: train	Epoch: 55.953,591	LR: 0.000039	Loss: 1.003	Speed: 224.94 img/s	Time: 0hrs:27min
[2026-02-11 01:10:44 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7605	MSE: 0.724	Speed: 8.2307img/s	Time: 14.58s

     MSE  Epoch Cohort
0  0.902     53  Train
0  0.724     53   Test

[2026-02-11 01:10:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 56.615,598	LR: 0.000032	Loss: 0.873	Speed: 2.07 img/s	Time: 0hrs:27min
[2026-02-11 01:10:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 56.994,602	LR: 0.000029	Loss: 0.752	Speed: 223.92 img/s	Time: 0hrs:27min
[2026-02-11 01:11:14 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7678	MSE: 0.724	Speed: 8.3037img/s	Time: 14.45s

     MSE  Epoch Cohort
0  0.855     54  Train
0  0.724     54   Test

[2026-02-11 01:11:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 57.657,609	LR: 0.000024	Loss: 0.813	Speed: 2.15 img/s	Time: 0hrs:28min
[2026-02-11 01:11:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 58.036,613	LR: 0.000021	Loss: 0.913	Speed: 222.77 img/s	Time: 0hrs:28min
[2026-02-11 01:11:44 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7663	MSE: 0.724	Speed: 8.1971img/s	Time: 14.64s

     MSE  Epoch Cohort
0  0.884     55  Train
0  0.724     55   Test

[2026-02-11 01:11:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 58.698,620	LR: 0.000017	Loss: 0.961	Speed: 2.13 img/s	Time: 0hrs:28min
[2026-02-11 01:11:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 59.077,624	LR: 0.000015	Loss: 0.920	Speed: 223.52 img/s	Time: 0hrs:28min
[2026-02-11 01:12:14 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7678	MSE: 0.724	Speed: 8.2677img/s	Time: 14.51s

     MSE  Epoch Cohort
0  0.898     56  Train
0  0.724     56   Test

[2026-02-11 01:12:28 - run_regression.py: 178]	INFO	Phase: train	Epoch: 59.740,631	LR: 0.000011	Loss: 0.761	Speed: 2.14 img/s	Time: 0hrs:29min
[2026-02-11 01:12:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 60.118,635	LR: 0.000009	Loss: 1.008	Speed: 223.66 img/s	Time: 0hrs:29min
[2026-02-11 01:12:44 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7665	MSE: 0.724	Speed: 8.2579img/s	Time: 14.53s

     MSE  Epoch Cohort
0  0.861     57  Train
0  0.724     57   Test

[2026-02-11 01:12:58 - run_regression.py: 178]	INFO	Phase: train	Epoch: 60.781,642	LR: 0.000006	Loss: 0.990	Speed: 2.14 img/s	Time: 0hrs:29min
[2026-02-11 01:12:59 - run_regression.py: 178]	INFO	Phase: train	Epoch: 61.160,646	LR: 0.000005	Loss: 0.814	Speed: 224.03 img/s	Time: 0hrs:29min
[2026-02-11 01:13:14 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7527	MSE: 0.724	Speed: 8.2518img/s	Time: 14.54s

     MSE  Epoch Cohort
0  0.877     58  Train
0  0.724     58   Test

[2026-02-11 01:13:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 61.822,653	LR: 0.000003	Loss: 0.894	Speed: 2.14 img/s	Time: 0hrs:30min
[2026-02-11 01:13:29 - run_regression.py: 178]	INFO	Phase: train	Epoch: 62.201,657	LR: 0.000002	Loss: 0.905	Speed: 223.17 img/s	Time: 0hrs:30min
[2026-02-11 01:13:45 - run_regression.py: 233]	INFO	Phase: valid	loss:0.8484	MSE: 0.724	Speed: 7.9801img/s	Time: 15.04s

     MSE  Epoch Cohort
0  0.878     59  Train
0  0.724     59   Test

[2026-02-11 01:14:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 62.864,664	LR: 0.000001	Loss: 0.833	Speed: 2.07 img/s	Time: 0hrs:30min
[2026-02-11 01:14:00 - run_regression.py: 178]	INFO	Phase: train	Epoch: 63.243,668	LR: 0.000000	Loss: 0.881	Speed: 223.24 img/s	Time: 0hrs:30min
[2026-02-11 01:14:16 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7626	MSE: 0.724	Speed: 8.2643img/s	Time: 14.52s

     MSE  Epoch Cohort
0  0.866     60  Train
0  0.724     60   Test

[2026-02-11 01:14:30 - run_regression.py: 178]	INFO	Phase: train	Epoch: 63.905,675	LR: 0.000000	Loss: 0.875	Speed: 2.13 img/s	Time: 0hrs:31min
[2026-02-11 01:14:31 - run_regression.py: 178]	INFO	Phase: train	Epoch: 64.284,679	LR: 0.000000	Loss: 0.832	Speed: 224.03 img/s	Time: 0hrs:31min
[2026-02-11 01:14:46 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7664	MSE: 0.724	Speed: 8.1499img/s	Time: 14.72s

     MSE  Epoch Cohort
0  0.874     61  Train
0  0.724     61   Test

[2026-02-11 01:15:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 64.947,686	LR: 0.000001	Loss: 0.876	Speed: 2.11 img/s	Time: 0hrs:31min
[2026-02-11 01:15:01 - run_regression.py: 178]	INFO	Phase: train	Epoch: 65.325,690	LR: 0.000001	Loss: 0.867	Speed: 215.43 img/s	Time: 0hrs:31min
[2026-02-11 01:15:17 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7620	MSE: 0.724	Speed: 8.0910img/s	Time: 14.83s

     MSE  Epoch Cohort
0  0.884     62  Train
0  0.724     62   Test

[2026-02-11 01:15:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 65.988,697	LR: 0.000002	Loss: 0.893	Speed: 2.09 img/s	Time: 0hrs:32min
[2026-02-11 01:15:32 - run_regression.py: 178]	INFO	Phase: train	Epoch: 66.367,701	LR: 0.000003	Loss: 0.783	Speed: 217.04 img/s	Time: 0hrs:32min
[2026-02-11 01:15:48 - run_regression.py: 233]	INFO	Phase: valid	loss:0.7728	MSE: 0.724	Speed: 8.0827img/s	Time: 14.85s

     MSE  Epoch Cohort
0  0.897     63  Train
0  0.724     63   Test

[2026-02-11 01:15:49 - run_regression.py: 369]	INFO	Done for training. Best metric is 0.7376974297070417@16 epoch. Average for last 5 iters is 0.723667773670375
[2026-02-11 01:15:49 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\train-RND-0.txt
[2026-02-11 01:15:49 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\train-RND-0.txt
[2026-02-11 01:15:49 - RegressionDataset.py:  83]	INFO	Parsing record file split_info\val-RND-0.txt
[2026-02-11 01:15:49 - RegressionDataset.py:  86]	INFO		Checking file exists in split_info\val-RND-0.txt
[2026-02-11 01:15:49 - about_log.py: 149]	INFO	Train:Dataset is ListDataset
[2026-02-11 01:15:49 - about_log.py: 149]	INFO		Number of samples: 169
[2026-02-11 01:15:49 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-11 01:15:49 - about_log.py: 149]	INFO		Labels file is stored in C:\Users\onekey\BaiduSyncdisk\Task2025\TaskSpec440-fenghexin_fuxin\Task2\split_info\labels.txt
[2026-02-11 01:15:49 - about_log.py: 149]	INFO	Valid:Dataset is ListDataset
[2026-02-11 01:15:49 - about_log.py: 149]	INFO		Number of samples: 120
[2026-02-11 01:15:49 - about_log.py: 149]	INFO		Root location: D:\\20251014-fenghexin_fuxin\L
[2026-02-11 01:15:49 - run_regression.py: 305]	INFO	Creating model inception_v3...
[2026-02-11 01:15:50 - run_regression.py: 352]	INFO	Start training...
[2026-02-11 01:16:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.379,4	LR: 0.001000	Loss: 4.208	Speed: 4.44 img/s	Time: 0hrs:0min
[2026-02-11 01:16:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 0.757,8	LR: 0.001000	Loss: 3.522	Speed: 279.92 img/s	Time: 0hrs:0min
[2026-02-11 01:16:20 - run_regression.py: 233]	INFO	Phase: valid	loss:1.5337	MSE: 1.284	Speed: 8.1056img/s	Time: 14.80s

     MSE  Epoch Cohort
0  3.730      0  Train
0  1.284      0   Test

[2026-02-11 01:16:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.420,15	LR: 0.000999	Loss: 4.276	Speed: 2.15 img/s	Time: 0hrs:0min
[2026-02-11 01:16:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 1.799,19	LR: 0.000998	Loss: 4.550	Speed: 270.01 img/s	Time: 0hrs:0min
[2026-02-11 01:16:49 - run_regression.py: 233]	INFO	Phase: valid	loss:1.5711	MSE: 1.540	Speed: 8.2076img/s	Time: 14.62s

     MSE  Epoch Cohort
0  4.398      1  Train
0  1.540      1   Test

[2026-02-11 01:17:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.462,26	LR: 0.000996	Loss: 4.970	Speed: 2.17 img/s	Time: 0hrs:1min
[2026-02-11 01:17:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 2.840,30	LR: 0.000995	Loss: 4.439	Speed: 274.96 img/s	Time: 0hrs:1min
[2026-02-11 01:17:20 - run_regression.py: 233]	INFO	Phase: valid	loss:1.2880	MSE: 1.275	Speed: 8.0705img/s	Time: 14.87s

     MSE  Epoch Cohort
0  4.018      2  Train
0  1.275      2   Test

[2026-02-11 01:17:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.503,37	LR: 0.000993	Loss: 3.880	Speed: 2.15 img/s	Time: 0hrs:1min
[2026-02-11 01:17:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 3.882,41	LR: 0.000991	Loss: 3.662	Speed: 281.58 img/s	Time: 0hrs:1min
[2026-02-11 01:17:49 - run_regression.py: 233]	INFO	Phase: valid	loss:1.3900	MSE: 1.224	Speed: 8.1732img/s	Time: 14.68s

     MSE  Epoch Cohort
0  3.466      3  Train
0  1.224      3   Test

[2026-02-11 01:18:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.544,48	LR: 0.000988	Loss: 3.845	Speed: 2.16 img/s	Time: 0hrs:2min
[2026-02-11 01:18:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 4.923,52	LR: 0.000985	Loss: 2.646	Speed: 297.30 img/s	Time: 0hrs:2min
[2026-02-11 01:18:19 - run_regression.py: 233]	INFO	Phase: valid	loss:1.3873	MSE: 1.256	Speed: 8.2630img/s	Time: 14.52s

     MSE  Epoch Cohort
0  3.592      4  Train
0  1.256      4   Test

[2026-02-11 01:18:33 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.586,59	LR: 0.000981	Loss: 3.810	Speed: 2.16 img/s	Time: 0hrs:2min
[2026-02-11 01:18:34 - run_regression.py: 178]	INFO	Phase: train	Epoch: 5.964,63	LR: 0.000979	Loss: 3.184	Speed: 284.76 img/s	Time: 0hrs:2min
[2026-02-11 01:18:49 - run_regression.py: 233]	INFO	Phase: valid	loss:1.2954	MSE: 1.172	Speed: 8.1492img/s	Time: 14.73s

     MSE  Epoch Cohort
0  3.588      5  Train
0  1.172      5   Test

[2026-02-11 01:19:03 - run_regression.py: 178]	INFO	Phase: train	Epoch: 6.627,70	LR: 0.000974	Loss: 3.026	Speed: 2.15 img/s	Time: 0hrs:3min
[2026-02-11 01:19:04 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.006,74	LR: 0.000971	Loss: 4.523	Speed: 295.82 img/s	Time: 0hrs:3min
[2026-02-11 01:19:19 - run_regression.py: 233]	INFO	Phase: valid	loss:1.2210	MSE: 1.095	Speed: 8.2738img/s	Time: 14.50s

     MSE  Epoch Cohort
0  3.501      6  Train
0  1.095      6   Test

[2026-02-11 01:19:33 - run_regression.py: 178]	INFO	Phase: train	Epoch: 7.669,81	LR: 0.000965	Loss: 3.539	Speed: 2.16 img/s	Time: 0hrs:3min
[2026-02-11 01:19:33 - run_regression.py: 178]	INFO	Phase: train	Epoch: 8.047,85	LR: 0.000961	Loss: 3.606	Speed: 271.99 img/s	Time: 0hrs:3min